### ISSUE TITLE
Can't unhide a character after hiding it.

### ISSUE THREAD

**Issue by FinnishWarchief** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#10]
**Describe the bug**
I chose a vampire lord from the undead list and I right cicked on the model and clicked 'Hide.'
When I tried to right click again, the character did not respond to the click. I can move the character still, just not interact with it in any way.

**To Reproduce**
1. Choose a character from the list of premade characters
2. Right click and choose 'Hide'
3. ???
4. Can't un-hide character

**Comment by creadth** [comment]
@FinnishWarchief Press Tab. It will highlight it back

**Comment by FinnishWarchief** [comment]
Cheers, for some reason tab was the last button I tried to press.

**Comment by Sebdevar** [comment]
Issue resolved, can be closed. Adding tag to the help menu would be a nice addition.
