### ISSUE TITLE
As GM lost control of tokens

### ISSUE THREAD

**Issue by NocanDu** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1009]
**Describe the bug**
I set up my very first encounter, wolves hidden.  asked a friend to joined. Success! I gave him control over his token.  As he wandered around I sprung my trap but found when I selected (L-click)a wolf token it went transparent and i could not use the CTRL or ALT options.  It just stuck a ghosted version to my cursor and I can only L-click drop it or esc out. 

Now every campaign I have made has this problem.  Uninstall/Reinstall did not help.  

**Screenshots/Videos/Twitch Clips**

![TS Error](https://user-images.githubusercontent.com/87026404/124626784-f9842580-de4c-11eb-8024-1b52e20e77d4.JPG)

**Additional context**
This this what happens when you L-click on a token.  You can not use keyboard bound directions either

**Comment by LuPro** [comment]
That's the teleport function - is it possible the Shift key may be stuck? (Or Ctrl, forgot which one was used for teleporting)

**Comment by NocanDu** [comment]
OMG TY!  The hotkey for teleport got switched to LMB.  Solved.  I was not aware of Teleport.
