### ISSUE TITLE
Percentile Dice Don't Add Correctly

### ISSUE THREAD

**Issue by LordAshes** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1010]
When rolling percentile dice (i.e. a D10x10 and D10) the total is not correct when the D10 rolls a 0 because it is treated like a 10 instead of a 0. This is correct behavior for a D10 roll but not when it is being combined with the D10x10 die.

For example, if the D10x10 die shows 90 and the D10 shows 0 then TS totals that as 100 but actually it should be 90. The "0" side on a D10 has a value of 10 when rolling as a D10 but it has a value of 0 when rolling as part of a percentile roll.

Note: I am calling the ten sides die that has sides 00, 10, 20, ... 90 a D10x10 die because calling it a D100 is not correct (since you can buy D100 dice which actually have a hundred sides).

**Comment by LuPro** [comment]
As far as I know it's not "wrong" just "different" - TS percentile dice range from 1-100 while the typical way to count them in dnd is 0-99 IIRC, there's been some talk about this in the discord, possibly it's worth creating a toggle to switch between the systems at some point (unless there's something else I'm misunderstanding here)

**Comment by LordAshes** [comment]
Percentile dice ranged from 1-100. That is correct. However, a D10 has
sides 0 to 9 (not 1 to 10). When rolling a D10 on its own, the 0 side is
typically treated as 10 but not normally for percentile dice.

For example:

D10 rolls 1. Result is usually treated as 1.
D10 rolls 2. Result is usually treated as 2.
D10 rolls 3. Result is usually treated as 3.
D10 rolls 4. Result is usually treated as 4.
D10 rolls 5. Result is usually treated as 5.
D10 rolls 6. Result is usually treated as 6.
D10 rolls 7. Result is usually treated as 7.
D10 rolls 8. Result is usually treated as 8.
D10 rolls 9. Result is usually treated as 9.
*D10 rolls 0. Result is usually treated as 10.*

*D10x10 rolls a 0 and D10 rolls a 0. Result is usually treated as 100 (not
10).*
D10x10 rolls a 0 and D10 rolls a 1. Result is usually treated as 1.
D10x10 rolls a 0 and D10 rolls a 2. Result is usually treated as 2.
...
*D10x10 rolls a 1 and D10 rolls a 0. Result is usually treated as 10 (not
20). *
D10x10 rolls a 1 and D10 rolls a 1. Result is usually treated as 11.
...
*D10x10 rolls a 2 and D10 rolls a 0. Result is usually treated as 20 (not
30). *
D10x10 rolls a 2 and D10 rolls a 1. Result is usually treated as 21.
...
*D10x10 rolls a 9 and D10 rolls a 0. Result is usually treated as 90
(not 100). *
D10x10 rolls a 9 and D10 rolls a 1. Result is usually treated as 91.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
I believe this is the convention for most if not all D&D editions. If other
game system use an alternate method then a toggle might be a good option
but definitely the D&D convention should be supported since a lot of your
user base is likely to be D&D players.

Best Regards,

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by baggers-br** [comment]
While this report makes it's case well, the dice are working as designed.
When we add dice modding we will have to make sure we can support people adding this approach.

Thanks for taking the time to document this so clearly.
