### ISSUE TITLE
I have dungeon filler pieces that have become intangible. Cannot affect them in any way.

### ISSUE THREAD

**Issue by Kodiaksmack** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1011]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

I placed a filler piece so I could properly box in the slab I was using. I placed 6 or so of them, rotating them to break up the texture of the walls. Some (about half) of the pieces became intangible, they were always just below another of the exact piece.  It seems as though the game  doesn't register it as being there at all. You cannot see in the screenshots, but when you hover over a normal piece the cursor turns into a hand. It remains as a pointer when hovered over the intangible piece. 

**To Reproduce**
1. Create a circle using only filler pieces.
2. Place another dungeon filler piece in a nearby tile to use as clicking point for creating your slab.
3. Paste 6 or more slabs on top of each other to create a tower (using m3 to rotate the slab 180 degrees every other placement. (1,1,2,2,1,1)
4. Be unable to click some of the pieces used as anchors for your slab.

**Screenshots/Videos/Twitch Clips**
![20210710132031_1](https://user-images.githubusercontent.com/87241312/125171452-513ecb80-e182-11eb-8148-6cc25ad63df0.jpg)

**Additional context**
Love Talespire so far, want a few more pieces in each "castle" tile set, like half walls or bricks. Overall great program. Keep crushing it!

**Comment by LuPro** [comment]
Is it possible to delete them with volume selection maybe?

**Comment by Kodiaksmack** [comment]
So I tried that and they were still unable to be selected. Quitting to the
menu and rejoining the board didn't fix the issue either. I quit out of the
program and rejoined the board and the tiles that were previously
"intangible" were just gone and the issue resolved. Still very weird that
just pasting slabs on repeat would cause it. Sorry if you spent a lot of
time on a issue fixable with a restart.

**Comment by LuPro** [comment]
No worries, it's a bug after all and has to be fixed at some point :)

**Comment by baggers-br** [comment]
Hi @Kodiaksmack, thanks for the great report. I've not been able to replicate this yet. You you still have this board? If you could copy a slab and paste it here it might be very helpful in triggering the issue on my side too.
Cheers!

**Comment by baggers-br** [comment]
Hi! This was a bug in the paste system that we fixed a little while back. Sorry for not revisiting this sooner.
Hope this finds you well and thank you again for the report!
