### ISSUE TITLE
Model gets of kilter with magic missile attack

### ISSUE THREAD

**Issue by tylers1st** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1014]
I have found that if somebody attacks with magic missile and gets attacked while in the middle of the animation, the model gets stuck in a slightly tilted state
![off kilter](https://user-images.githubusercontent.com/47163941/126108332-881ee3ce-5cb1-4985-b472-4184b72a9718.PNG)

**Comment by LuPro** [comment]
duplicate of #791
