### ISSUE TITLE
Black box of death

### ISSUE THREAD

**Issue by SpartaTeddybear** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1016]
Got this black box that I cannot interact with.

![Screenshot_3](https://user-images.githubusercontent.com/87852644/126755569-577558a5-2691-4e76-8fa1-d92a50596c1c.png)

**Comment by LuPro** [comment]
This is the experimental fog of war, could you check the settings if you accidentally set a keybind for it? (there you'll also find a keybind for removing the fog of war again)

**Comment by SpartaTeddybear** [comment]
Ahhh, yes I figured it out. Thanks a lot!
