### ISSUE TITLE
Switched to a new PC and now I am unable to access my campaigns

### ISSUE THREAD

**Issue by miguelriospr** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1020]
I upgraded to a new PC and now when I run Talespire and try to get into my campaign none of the maps will load for me. I get an error with the following ID: 94E9020C-0B3D-4290-9905-362C12B2B1D0 and I get sent to the void.
My players can still access the maps fine.
I was able to create a new campaign but after building a new map, if I try to close Talespire it just crashes with no error code or anything and it will not save any changes I made to the map.

**To Reproduce**
It happens every time in my new PC. If I use a different PC everything works as intended.

**Additional context**
my new pc: 
CUK OMEN 30L Gaming Desktop (AMD Ryzen 5, 32GB RAM, 1TB NVMe SSD + 2TB HDD, NVIDIA GeForce RTX 3070 8GB

**Comment by miguelriospr** [comment]
![image](https://user-images.githubusercontent.com/88116412/127405691-32184ab6-9489-4bbd-aad4-aaa699948ba3.png)
Tried it a few more times and got a different error code but same issue.

**Comment by baggers-br** [comment]
Hi @miguelriospr, really sorry to hear about this. It's very odd as we work across multiple machines without this issue.

Looking up the error it states that it's related to a missing dll. How are you installing TaleSpire on these additional machines? Are you using Steam, or copying the files manually?

**Comment by miguelriospr** [comment]
I used Steam. Somehow a few days after I posted the error it just started
working again. I am assuming maybe a windows update installed the missing
dll, I don't know. My apologies for not going back and closing out the
ticket.

**Comment by baggers-br** [comment]
No worries at all, as you can see you have much better response times that I did 😬 
Hope this finds you well.
