### ISSUE TITLE
Killing controlled token while it's moving gives controlling player's client an error

### ISSUE THREAD

**Issue by Spiderach** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1026]
"null reference exception  unityengine.transform.get_position() @{pos}"

Reproduce by:
Have a player controlled token move while the GM deletes  #it.

![bugreport](https://user-images.githubusercontent.com/25784628/127783464-cdbfdad4-846c-4309-83d2-1e072efa192f.png)

Seems related to a similar bug with a permanent tilt being applied to tokens if they move when an animation is activeated ( #917)

**Comment by baggers-br** [comment]
I've just tested this and it seems to no longer cause this error. I'll tentatively close this for now.

Thanks so much for the report and if you see it return please feel free to bug us!
