### ISSUE TITLE
Doors are missing after the latest patch (24.08.2021)

### ISSUE THREAD

**Issue by PrezWaste** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1029]
After the latest patch, Early Access Patch 17 (the one that introduced knockdown), doors are gone. Whenever you try to place one door, it doesnt show up half of the time. If you place certain double doors, it's only the outer rim that it present.

Example:
![Dørene har ikke dører](https://user-images.githubusercontent.com/82775110/130647233-1cfb4afc-87d1-42f9-bf6f-62fbfb782406.png)

This should be easy to replicate by trying to place doors on a board, or look at exisiting doors on a board.

**Comment by LuPro** [comment]
Bug reporting has moved to HelloNext, see #1028 for details :) Also, there's been a hotfix for this already.
