### ISSUE TITLE
Prop search keeping tags between campaigns

### ISSUE THREAD

**Issue by Omoz** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#103]
After building with a friend in his campaign, I searched 'Tavern' in the prop search and then left his campaign without clearing the search tag. I then created a new campaign and the prop search is retaining the 'tavern' search tag but does not show the tag in the search area.

**Comment by flpa** [comment]
I only experienced this problem, only restarting the game seems to clear the search term that's stuck somewhere internally.

**Comment by Pruegeleisen** [comment]
For now you can clear the tags without having to restart the game by simply pressing the backspace key repeatedly. The old tags will show up in the text field and can be deleted.

**Comment by cbaggers** [comment]
Thanks for report. Totally clear and was able to reproduce the issue easily.
I think it's fixed now, it will be in tomorrows patch.

**Comment by LuPro** [comment]
Just tested, can not reproduce anymore, everything works as expected for this now
