### ISSUE TITLE
Copy pasting with walls without floors mis-aligns content to grid

### ISSUE THREAD

**Issue by subliminalchords** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#106]
**Describe the bug**
I used walls to outline the room being created, so they were on the grid squares outside of the space. When I copied and pasted to move, i expected them to still line up the same way on the grid, but they aligned on the outside edges, mis-aligning everything within them by half a square

**To Reproduce**
1. Place a floor tile
2. Add walls outside the floor tile so they take up half of the adjacent grid squares\
3. Select the walls and floor and copy or cut
4. Paste block, see that the grid alignment has changed

**Screenshots/Videos/Twitch Clips**
Video in action: http://www.filedropper.com/talespire2020-04-1021-50-30

**Additional context**
Ideally walls shouldn't even take up half of a nearby square, they should just exist on the grid line

**Comment by cbaggers** [comment]
I have just pushed a patch that fixes some paste alignment issues I have been able to reproduce on other tickets. 
I was unable to see your video as the link isnt working for me, however, it might be worth trying again with the latest patch to see if it helps

**Comment by LuPro** [comment]
I haven't seen any further reports of this issue and it should have been fixed in the patch from 6 days ago. I'll consider this issue fixed, if it still persists for someone please comment so it can be reopened
