### ISSUE TITLE
Resolution in Fullscreen Menu Problem

### ISSUE THREAD

**Issue by Yangmarsh** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#110]
**Talespire is shrunken down to a resolution so small that it cannot be changed via normal menu options because they are either inaccessible or difficult to find**
Tale spire seemed like it was meant to run to full screen and adapt to the necessary resolution, even if it was stretched. However instead, the resolution zoomed in on the program to the extent that the UI was difficult to interact with, only allowing me to enter the game and leave, without being able to access campaigns. 

**To Reproduce**
1. Open Settings
2. Turn off Windowed Mode
3. Game is forced into Extremely low resolution without the ability to change back

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63484104/79033077-e5317a00-7b70-11ea-8eae-3a0fb756485f.png)
Accessing Settings: 
![image](https://user-images.githubusercontent.com/63484104/79033081-ef537880-7b70-11ea-95a9-fcdfde5061e2.png)
Quit Menu: 
![image](https://user-images.githubusercontent.com/63484104/79033083-f67a8680-7b70-11ea-9e76-5a96f1cc78ae.png)

**Additional context**
My system does normally run on 3000x2000 Resolution. I tried changing the resolution of my system to offset the issue, but regardless of my system's resolution, the game still displays in such a way that menus cannot function.

**Comment by Hojon28** [comment]
I have the exact same issue.  Uninstalling and Reinstalling isn't fixing it either.

**Comment by JFleming4** [comment]
I've done a bit of experimenting with this  and it looks like whenever I toggle from windowed to fullscreen it sets the resolution to 300x200. My native resolution is 2736x1824 (windows surface). Although if i set windowed version to 0 (false) and then manually change the resolution it displays properly. 

The settings I changed were at C:\Users\{myUser}\AppData\LocalLow\BouncyRock Entertainment\Talespire\TalespireSettings.json

I'm going to try and see if this happens on my other computer just as a quick sanity and I'll update this comment

**Comment by Hojon28** [comment]
That worked!  My native resolution was 1360x768.  I opened up that file with Notepad, changed the resolution, saved the file, and restarted the program.
![Capture3](https://user-images.githubusercontent.com/63484184/79047122-6113dc80-7bda-11ea-9752-bab88aea5c7d.PNG)

**Comment by LuPro** [comment]
Seems to not happen for all (for me for example, it worked as expected). Definitely a pretty common thing to happen though

**Comment by Yangmarsh** [comment]
Tried the fix. 
Initially I was trying to edit the Json File with Notepad and found it wasn't working. After manually opening it with notepad and modifying the settings, it's all clear! 
Thanks y'all!
