### ISSUE TITLE
 **crash**    TaleSpire - Unity 2019.3.0f3_6c9e2bfd6f81

### ISSUE THREAD

**Issue by jpb1894** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#114]
**Crashes to desktop**
Upon trying to add tiles, a box pops up with the error in the title and the app crashes to desktop. 

**To Reproduce**
1. Enter map
2. Select any tile type
3. Drag mouse to install tiles
4. TaleSpire crashes

**Comment by zhatten** [comment]
Seeing this issue as well, think my version might be from the PC being on windows 7, rest of the PC specs fit within the required specs for the game.

**Comment by jamogwe** [comment]
My computer is having the same issue. It is an older computer running on a Phenom X2 processor chip with only 8gb of ram. I have a second computer that is running the game just fine (more than one copy of Beta so that is not the issue).

**Comment by LuPro** [comment]
Seems similar (not equal though) to #7, #12 and #87, but hard to pin down a common denominator

**Comment by spec24** [comment]
> My computer is having the same issue. It is an older computer running on a Phenom X2 processor chip with only 8gb of ram. I have a second computer that is running the game just fine (more than one copy of Beta so that is not the issue).

I have a Phenom II X6 and Talespire will not run either. I have 16gb on it and a GeForce GTX 600 Ti. I have three other PC's running it no problem. Those are all Intel. I can even run it on a lowly laptop running some Intel onboard graphics.

**Comment by LuPro** [comment]
The latest update introduced a possible fix for this (if it really is the same issue as the ones I mentioned above). Could you please check if it works for you now?

**Comment by jamogwe** [comment]
I'm sorry, we updated the computer with new guts so I can't try again. It was 10 years old and needed some new life 😁

**Comment by LuPro** [comment]
Going to assume it is fixed for everyone now, if anyone still has the problem please comment and I'll reopen this issue
