### ISSUE TITLE
Spawning 160,000 hatches breaks the game.

### ISSUE THREAD

**Issue by Wolf1911** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#14]
At this number of hatches the game will lag uncontrollably to at most 6 fps, then the camera will sway back and forth to each world border over and over.

**Comment by Sebdevar** [comment]
Well... no shit Sherlock lol. Could you perhaps add your Computer Specs plz? This is most probably closely linked to it.

**Comment by Wolf1911** [comment]
> Well... no shit Sherlock lol. Could you perhaps add your Computer Specs plz? This is most probably closely linked to it.

Each of my friends also lagged then finally crashed when he spawned the hatches.

This is a thread for bug reports, not for being a dick.

AMD Ryzen 9 3900X
64 GB DDR4 2333 MHz RAM
GTX 1080 11GB
Samsung SSD 970 EVO 1TB NVMe M.2 SSD
10GB Network Interface Card with Gigabit connection
144 Hz Monitor @ 1920x1080 Resolution

**Comment by infinityman98** [comment]
> Well... no shit Sherlock lol. Could you perhaps add your Computer Specs plz? This is most probably closely linked to it.

While this is a Issue Tracker, its always good for game devs to know the extent of their games optimization. While we all know spawning 160k of anything in any game could probably break said game, its still a good idea to issue any and all crash reports to a game dev. Keeping devs in the loop is a good way for a game to improve faster.

**Comment by LuPro** [comment]
Can definitely reproduce (not much of a surprise here) with i7-4790k and a GTX 1080. Though at this point it might a question whether it really is a bug, or just hitting the limits of what Unity can do. GPU instancing might help with this issue, but if the rest of the game performs well enough, I doubt there will be dev time to fix just this particular issue (as in: placing lots of one thing).
Also, the cunked loading of boards (that is planned) might help with this, would be interesting to find out once that is done and released

**Comment by LuPro** [comment]
In light of the new Chimera release and the performance improvements it entailed, I can safely say this issue can be closed:
https://user-images.githubusercontent.com/20774976/113214186-5fbf4200-9279-11eb-8256-9ac455398583.mp4
