### ISSUE TITLE
Stone Wall Corners

### ISSUE THREAD

**Issue by RadDong** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#143]
![Screenshot (9)](https://user-images.githubusercontent.com/63489033/79036345-5cb8d680-7b7c-11ea-9622-551f8554b2d1.png)
![Screenshot (10)](https://user-images.githubusercontent.com/63489033/79036348-617d8a80-7b7c-11ea-84ff-4a6541d06a33.png)

Stone wall corner 2 not lining up with corners and have odd spaces

1. Place stone wall corner 2
2. Place stone wall
3. Not lined up properly and doesn't look aesthetic

It has an odd placing box which is different from regular walls since it seems a little thicker and almost seems like it takes up 3/4 of a square instead of 1/2 like a normal wall. 

Thanks!

Sincerely, 
Rad Dong

**Comment by LuPro** [comment]
This shouldn't be an issue anymore with the new prop system that just released :)
