### ISSUE TITLE
Dungeon Corner without Floors Collision has extra space above it

### ISSUE THREAD

**Issue by AnimationPig** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#144]
Dungeon Corner without Floors have extra space above where they end. I was trying to build a tower and noticed that the corners without floor have an extra space above it because it uses the same clipping as the one with floors. Lowering it by just one tile would allow you to stack them correctly, otherwise you have to use the single dungeon corner and put three of them in the corner

**Comment by PropForge** [comment]
I believe this is the same issue as 123?

**Comment by AnimationPig** [comment]
> I believe this is the same issue as [123](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/123)?

Yes it is. Sorry didn’t realize someone had posted it already
