### ISSUE TITLE
Unknown Initiative Combatant

### ISSUE THREAD

**Issue by Klaveen** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#152]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. Start initiative order
2. Have dice on game board (after rolling during combat)
3. Select another combatant to join the initiative.
4. Dice that are on the game board will appear in initiative order as '<unknown>
5. <unknown> combatant cannot be deleted.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![image](https://user-images.githubusercontent.com/63495240/79039873-457ef500-7c1f-11ea-83a0-e9acc3d46995.png)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Razial7** [comment]
I have this same issue and furthermore it carries this blank initiative from board to board and I cannot wipe it clean.

**Comment by Sendery** [comment]
I did reproduce this same issue by:
1.-select turnbase mode,
2.- edit the order,
3.- "ask for permission to one player over a NPC". 
4.- change from GameMaster to player Then NPC is shown as Unkwnon the others are fine (that NPC is an Unique Character with the name edited)
![152_unkwnon character](https://user-images.githubusercontent.com/10600957/79056146-87299300-7c53-11ea-9fa6-32cfa18a0aea.png)

**Comment by LuPro** [comment]
Is it really the dice being shown as unknown? Could it be miniatures on another board? In that case it would be similar to #83. Though the thing with GM switching to Player mode seems new

**Comment by cbaggers** [comment]
I think this will have been fixed in last Friday's update. If you have time please check it out and let us know if it still occurs. Cheers!

**Comment by LuPro** [comment]
Considering I haven't seen this issue be reported again and no further comments on this, I think this is fixed. If this error is still reachable please comment so the issue can be reopened
