### ISSUE TITLE
Maps don't load after reopening campaign

### ISSUE THREAD

**Issue by xRinzler** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#154]
My friends and I built a basic small town with a few buildings on one board. On another board we had a feast hall built. Initially, there was no trouble switching from both boards. However when we left the campaign and rejoined, we couldn't load our map or anything that was built. It was stuck on an infinite loading screen with "waiting for your adventure to begin".

**Comment by karekanol13** [comment]
Having this problem too, me and one other person worked for hours and when our third played got stuck loading, we all tried leaving and rejoining. Now all of us keep getting the "waiting for your adventure to begin". We only had one board.

**Comment by LuPro** [comment]
In the newest update there is a fix for many of those occurrences, could you check if this worked for you? if not, please send the contents of the dev console (triple click top left corner) here for more details. (also ignore me adding the asset issue tag :P)

**Comment by LuPro** [comment]
As I saw the comment on another similar issue of the OP that this was fixed, I'll close this issue now
