### ISSUE TITLE
Copy + Paste issue, specifically Tilled Earth.

### ISSUE THREAD

**Issue by ShibInu** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#159]
**Describe the bug**
I'm attempting to copy+paste the following string...
`H4sIAAAAAAAACzv369xFRgY2BqN/Ole3pYu7Lzr/dJZLk744LwMr+8sNRx9KvS/3npeYuP3MtK19LECx2zMWPvOs0/Wfy8l51n3hRzU2oJigKe+7xSrZ/jNj7ULuWdyzlgaKlRS7q+75VuG9LHF9p6J81SpmoFh2S49Vinmqw2ZL9Q3RLodLmYBiDAwKB///r7djYEhxYmBosAdiOzAt8yWfgcEBuxwTAxAYQOVi8Mj5oMr9B8nB7AtBlQMDBzxyE7CbGVjjiJBDcwsjSF8DVC4Cj5no9oExVC4Aj74UdDljhD50uYiDTMBwYWA4YI9kJhjzfPj/nwEul4Eix8HAAKQ7sMqxaEk2IORQzYTEgwpULswJyY32LMzIckmocmB9HlC5bCcGsP0wf4BABR65Pqxm8jA07EfIobqFpx6kT+MgRCwLZibIPKDfrYB8CxxyMHdikdu72xgU3jj02YP0QeLID00OEk8QuTRUOSZk++LwuCUKixzMLUmochMqrRBy6GZC3ILVTN7OrQi5MDz2BaHKGRcjmYnudxDIwB5maqn/EHJo4VKPrC8JS5hlYPcfihya/7rEPyHksPkvA7v/UOSwxW0Fdv+lpdkh5NDcyQFit0DTBJocuHxpwZHOQPb14EmfCUj5CJ5v7TjMQeUuLG/GIOUVYDnBjJzHUOVYwH4H2adgj3AnA9QtUw5C3IlNjmELxC0L7CHxsMABwp7gAAATQ6aunAYAAA==`

When I hit Ctrl+V the preview looks as it should, you can see the Tilled Earth blocks. When I actually click to paste everything except for the tilled earth copies over.

Copy:
![image](https://user-images.githubusercontent.com/63497361/79041212-f94e9900-7bbb-11ea-9ab1-4441422d1f5d.png)

Paste:
![image](https://user-images.githubusercontent.com/63497361/79041216-ffdd1080-7bbb-11ea-8b31-4fb8e1d19b43.png)

**To Reproduce**
1. Copy the above string.
2. Paste into a board in build mode.

**Screenshots/Videos/Twitch Clips**
See above.

**Additional context**
Loving Talespire so far :)

**Comment by Gladpus** [comment]
Most likely related to this issue
[https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/172](
https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/172)

Can you confirm whether the tilled earth tiles were initially placed by click+drag to place several, or individually placed? The common thread seems to be that floor tiles placed manually on ground level will occasionally not paste, if they are copied together with walls /some other tall assets

**Comment by ShibInu** [comment]
They were individually placed. I click+dragged most of the other floor tiles, but selectively placed the tilled earth.

And yeah, #172 looks like a much more cohesive report on this issue. I am building on the ground floor.

**Comment by LuPro** [comment]
I just realized this could have been fixed together with #172, could you try if this is fixed now?

**Comment by LuPro** [comment]
I'm going to assume this is fixed considering the issues look so similar to each other. If this is not the case please comment so this issue can be reopened.
