### ISSUE TITLE
Copy and paste 

### ISSUE THREAD

**Issue by MattiaQuartana** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#16]
I selected for copy 9 pieces of grass and one dead tree, but when I paste the group, but only 5 pieces and the dead tree have been pasted.

**To Reproduce**
1. selected the landscape  whit the left click of the mouse
2. pressed ctrl c
3. pressed the left click of the mouse

![woods](https://user-images.githubusercontent.com/46351490/79019285-50317f80-7b76-11ea-8247-dabfe3f1ab3c.png)

**Comment by BlappoSpawn** [comment]
cant tell which pieces should be or not.  could u reproduce it and show a before paste and after paste?

**Comment by MattiaQuartana** [comment]
The pieces are Grass Lush 2x2 floor grass and the dead tree is the 01 1x1.
I can't show you the old error but I get another.
![after](https://user-images.githubusercontent.com/46351490/79020503-4b21ff80-7b79-11ea-9f7d-ac8700132f25.png)
![before](https://user-images.githubusercontent.com/46351490/79020512-4d845980-7b79-11ea-80c1-388bdacab04d.png)

**Comment by MattiaQuartana** [comment]
![after](https://user-images.githubusercontent.com/46351490/79020556-6b51be80-7b79-11ea-86a3-4b9a9528bdb9.png)

**Comment by BlappoSpawn** [comment]
i have a bit of insight on this.  its that base "Build Plane" or BP  causing issues... if you raise the BP just 1 tick it suddenly places all tiles... i moved a whole inn, base BP problems, 1 or 2 ticks up  no problems.
https://youtu.be/bki41sys7GI

**Comment by LuPro** [comment]
#172 seems to have a good working theory on this issue

**Comment by MattiaQuartana** [comment]
Thanks
