### ISSUE TITLE
Props - Wooden Fence Corner

### ISSUE THREAD

**Issue by PoorSeal** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#162]
**Describe the bug**
The props, Wooden Fence Corner, is not able to put at the grip in a proper location. It shows me that it is not stick to the Grip.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63499740/79042554-56cdfe80-7c2b-11ea-9fc9-bc4b342da3b5.png)

**Comment by LuPro** [comment]
This shouldn't be an issue anymore with the new prop system that just released :)
