### ISSUE TITLE
Copied blocks displaying in selection but not being pasted

### ISSUE THREAD

**Issue by ellroch** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#164]
**Describe the bug**
watch the gif below in screenshots/vids. I build a quick staircase. select the blocks, copy, (all blocks are shown in the selection when I move my mouse) and paste. but when I paste several blocks are missing. I'm thinking that this is due to the missing blocks being partially shifted below / clipped into the 'board.'

**To Reproduce**
1. build a simple structure, say a single column of blocks. as high as you like. Just make sure that the bottom block is partially clipped into the board.
2. select the column, starting from the top, all the way to the bottom. (starting from the bottom will not select the lowest block since it is actually 'below the ground')
3. copy, and paste. even though the lowest block (or all blocks that were clipped below the board) is displayed in the selection, it is not pasted
4. also note that the pasted blocks are arranged properly, floating on one block's worth of empty air.

**Screenshots/Videos/Twitch Clips**
https://gyazo.com/d87284db3a40db945b59107e2d76589a
https://gyazo.com/5f4b1db564207e252ac8a8892014b6f2

another note: selecting from the bottom will not select the blocks clipped through the 'board' though it will select the bottom blocks when clipped through a standard floor block. say grass, or wood.:
https://gyazo.com/4bc95e18578d7fba6c35abc2a55392cb

**Additional context**

**Comment by LuPro** [comment]
I am pretty confident it might be the same issue as in #172 - check the description there for reproduction steps, could be a clue

**Comment by LuPro** [comment]
This should have been fixed together with #172, please check if this still persists for you

**Comment by LuPro** [comment]
I'll assume this issue is fixed, if this is not the case please comment so this issue can be reopened.
