### ISSUE TITLE
Draging tavern wall tiles misplacment. 

### ISSUE THREAD

**Issue by BlappoSpawn** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#17]
**Describe the bug**
I think this used to happen early in alpha. idk if it ever has been fixed.

When dragging out a few blocks to place they place offest from expected drop.

**To Reproduce**
1. Select a tile.
2. place a row of tiles
3. Attempt to place another row ontop of the existing row.
* i specifically was using 2x1 wall tavern "tavern wall 01" 

**Screenshots/Videos/Twitch Clips**
https://youtu.be/SXWGZUhAjvU

**Additional context**
most of my walls placed fine... something about this set triggered it. perhaps type of wall beneath the wall. or direction i placed it.

**Comment by makeshiftmousepad** [comment]
I encountered the same problem with the same wall tile. It occurred on all on all surfaces and didn't occur when placing one tile at a time in the exact same possitions.

**Comment by JSpinelli** [comment]
Same issue, with the same type of wall. It seems it happens when it should connect with something.

**Comment by LuPro** [comment]
Interestingly, I couldn't replicate this - might have something to do with the surroundings?I tried a variety of blocks beneath (walls with floor, without floor, corners) and placing grass on the outside, but dragging the tiles for the second floor worked as expected every time.
Might be some other issue, or at least other cause than just that, I think more testing is required.

**Comment by BlappoSpawn** [comment]
my assumption has been that walls are smaller that 1x1  they are actually  .5x1  this makes the grid selection ui more difficult to select where to place... but just musings.

**Comment by LuPro** [comment]
Just found out that Dungeon Wall 02 shows the same behavior

**Comment by maxumusprime** [comment]
This bug seems to affect everything that is 0.5x1 spaces and 0.5x2 spaces.
Tested with both castle ruins walls, every type of door, and the 0.5 dungeon walls.

**Comment by BerserkShirtBear** [comment]
I have been having this issue with Moorgoth walls

**Comment by IGJoshua** [comment]
As far as I can tell, this bug occurs with any half-block sized tile when it is drug out to multiple tiles wide when positioned in a particular direction. These tiles "prefer" to be on one half of the tile, and the only way to place them in the "wrong" half is to place them one at a time.

**Comment by PropForge** [comment]
I just found this bug with Tavern 1x1 No Floor tiles.

**Comment by jonnyree** [comment]
This should have been addressed in today's update 5124991.  I would love to get confirmation on this.

**Comment by IGJoshua** [comment]
Can confirm that this is fixed for me in the latest update.

**Comment by jonnyree** [comment]
Thank you for checking and confirming @IGJoshua I'm going to close this one now.
