### ISSUE TITLE
Fences

### ISSUE THREAD

**Issue by Jorhord** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#170]
Fences don't match well. Corner and wall fences.

**Comment by NerdyViking** [comment]
I have noticed this as well. https://i.pinimg.com/originals/43/b7/63/43b7630156f56c8661aa88a30fa6a8d1.jpg
Screenshot to view.

**Comment by ellroch** [comment]
I think this is another expression of the same bug I capture in reports https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/160 and  https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/157

**Comment by PropForge** [comment]
I believe this is the same issue as [this?](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/48)

**Comment by LuPro** [comment]
I'd put it to the same issue as PropForge did, pretty sure it's the same as #48, and not #157 or #160 - screenshots would help with confirming that

**Comment by LuPro** [comment]
Latest update fixed (most of) this. See #417 for the remaining issue
