### ISSUE TITLE
Copy/Paste > copied tiles on the ground that were placed without dragging don't paste

### ISSUE THREAD

**Issue by hanoldaa** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#172]
**Describe the bug**
When tiles are placed on the ground level without dragging them out (even if you drag out and back to 1 tile before placing), copying the tiles will show them as copied, but when you go to paste the ground tiles won't paste.

**To Reproduce**
1. Place a grass tile on the ground level (just by clicking)
2. Place another grass tile on top of it
3. Select the 2 tiles
4. Copy
5. Place the tiles on the board
6. Only the 2nd tile was placed **Fail**

**Screenshots/Videos/Twitch Clips**
![Simple copy-paste bug 2](https://user-images.githubusercontent.com/8760370/79045452-2f4e4600-7bd9-11ea-9563-4a9206f6cc3f.gif)

**Additional context**
Several notes about this bug:
1. This only happens on the ground level, moving up even .25 units and building off the ground is fine. Additionally, if I copy it when it's built off the ground and move the grid back to the ground before pasting, all tiles will paste properly.
![Simple copy-paste bug 2 workaround 2](https://user-images.githubusercontent.com/8760370/79045606-ff537280-7bd9-11ea-8187-79e9ddabcfbe.gif)

2. When I place the first tile on the ground, if I drag out first then return back to 1 tile, it'll copy and paste without issue. Which seems to indicate something about dragging is key to getting it to paste.
![Simple copy-paste bug 2 workaround](https://user-images.githubusercontent.com/8760370/79045459-3d03cb80-7bd9-11ea-840b-f84df06c12ae.gif)

**Comment by Gladpus** [comment]
Encountered similar behaviour, example strings included for testing purposes
 **Broken Paste String**
``H4sIAAAAAAAACzv369xFRgZBhrux3DON1a86rLdLdE3LF+FjZHhXPvNW9KJc3ns+O9sZP/zmOyEBEvsr9Gs171I+vxUy75V+T5PJAokdeGW2btP9Gb6TzJiPHrztxQ4S81XdcWoB1xaH9V4c044mMLuBxHYnJ5zPi2F33PxyDk/U8fAMkJhbus6z8+f2u3Ur/BC3+HhJAST2fKnR67eXvR0nLhGY+nZNFViMQZ/9reun5y5zVbNktsw4vQokdvGt8dudPza4zOXZLZ8gs+sISMzvO8vvqr/OTpN2GZxdvbC1BCR2wU7rr3ywo/NMw+ydE7/oa4PEnKY3CBwpWOk6OUDrhSjrLbCbM58nifrurnfe9KGkS+blu9UgsQf9yQpRmn0O0/12eGZymhuC7ejnyvDOmuK475Zj9uMja9xBYss6l9f+aFBwm7ciSINPaIYA2M0MFxz+//9vx8DwwYGBgcEejvkFGhgYJgDFGoD8DVC5BrAchxBIjsMRom8Dij4WXpDcAqCZ9UA5BUdGsJ4GO5BeHkGQ3AH7///3I9l3wA5spgjEPoi+BJh9YDkGTpAcA1SOAeomiJkMHCA5mB8O2CO7hYcb2Z0JqP7jQZZD1cfABZKbAbXnhQPcLhAthGwfqt8Z+JDlUO1j4UH2O0wfxO8MwshuwRkPSO5EhMuf///tYWGNHC48AgIN///Ph/rhAIiGshc4AAAZv7ezUAMAAA==``
Resulting behaviour:
https://i.gyazo.com/93ad3d0bb81a888deae37605fa637482.mp4

**Fixed String**
``H4sIAAAAAAAACzv369xFRgZBhrux3DON1a86rLdLdE3LF+FjZFi3eOat6EW5vPd8drYzfvjNd0ICJPZX6Ndq3qV8fitk3iv9niaTBRI78Mps3ab7M3wnmTEfPXjbix0k5qu649QCri0O6704ph1NYHYDie1OTjifF8PuuPnlHJ6o4+EZIDG3dJ1n58/td+tW+CFu8fGSAkjs+VKj128veztOXCIw9e2aKrAYgz77W9dPz13mqmbJbJlxehVI7OJb47c7f2xwmcuzWz5BZtcRkJjfd5bfVX+dnSbtMji7emFrCUjsgp3WX/lgR+eZhtk7J37R1waJOU1vEDhSsNJ1coDWC1HWW2A3Zz5PEvXdXe+86UNJl8zLd6tBYg/6kxWiNPscpvvt8MzkNDcE29HPleGdNcVx3y3H7MdH1riDxJZ1Lq/90aDgNm9FkAaf0AwBkBgTg4IDAwODPQPDl4MQGoYb7DmgNAMD0yEGOJsBKN5gz8gwAaoPJgfBLAztzqxgdQ12DAwPDjLC2Q32PAzsLv/+yx9gYDhgh7APxAaZye4CtQ/I54LZZwc1l+HP///7IXyBQwxIZoLkEH4QQnELD4o7uQ6h+o/dGSEnhCbHwMDB4AD177eDCLvA7kGyjwlNX4M9Qo4LLVw6nBB+h+k7YAfTh3ALzniwQ7gTES5AcAAW1gwoYQ0CDbA4A4WZA4S9wAEAtxLpKVADAAA=``
Resulting behaviour:
https://i.gyazo.com/2b497f833cf551bcd764be68d77e729d.mp4

**Comment by hanoldaa** [comment]
Not all assets are affected, here is a list of the ones that are:

**Castle**
Castle Floor 1
Castle Floor 2
Castle Floor 3

**Castle Ruins**
Castle Ruins Crenellation 1
Castle Ruins Crenellation 2
Castle Ruins Floor 01
Castle Ruins Floor - Small
Castle Ruins Pillar - Mid
Castle Ruins Pillar - Top
Castle Ruins Rockpile
Castle Ruins Stair
Castle Ruins Stairbox
Castle Ruins Wood 1
Castle Ruins Wood 2
Castle Ruins Wood 3
Castle Ruins Wood - Large
Castle Ruins Stone Floor 2
Castle Ruins Floor Stone 1
Castle Ruins Floor Stone 2

**Caverns**
Cavern Rock 01
Cavern Floor - Rock 01
Cavern Floor - Rock 2
Cavern Floor - Rock 03
Cavern Floor - Rock 04
Cavern Rails - Corner 01
Cavern Rails 01
Cavern Rails - Cart (Coal)
Cavern Rails - Cart (Empty)
Cavern Coal Pickaxe
Cavern Coal Heap

**Dungeon**
Dungeon Floor 01

**Light**
Brazier
Campfire
Candleabra - Single
Candleabra - Triple
Candleabra - Small
Lantern -Small
Bonfire

**Nature**
Rock - Small
Bush - Medium
Tilled Earth
Grass - Lush
Grassy Road
Grassy Road Corner
Grassy Road T
Grasst Road Crossroad
Grass - Sparse
Root 01
Root 02
Root 03
Stone Wall - Corner 01
Stone Wall 01

**Props**
Anvil
Barrel
Broken Dark Barrel 01
Broken Dark Barrel 02
Barrels
Apple Basket
Baskets
Bear Rug
Bench -Shabby
Bone Pile
Book Pile 01
Book Pile 02
Book Pile 03
Book Pile 04
Castle Chair
Castle Table
Cauldron
Cauldron With Handle
Lidded Cauldron With Handle
Cheese
Fancy Coffin
Basic Coffin
Crate - Large
Stacked Crates
Dark Crate Large 01
Dark Crate Large 02
Dark Crate Medium 01
Dark Crate Medium 02
Dark Crate Small 01
Dark Crate Small 02
Dirt Pile
Wooden Fence Corner
Wooden Fence
Gravestone 01
Gravestone 02
Gravestone 03
JackOLantern
Log Pile
Wooden Cart
Papers 01
Papers 02
Fruit Pie
Pumpkin Pie
Pig Roast
Pitcher
Plate
Large Pumpkin
Pumpkin
Rubble
Sacks
Sarcophagus
Side Table
Wooden Table 01
Wooden Bench - Small
Round Table With Chairs 01
Round Table with Chairs ... (02?)
Round Table With Food
Table With Chairs 01
Table With Chairs, Food A...
Table With Feast 01
Table With Feast 02
Stool_Torture_01
Treasure Pile - Small
Treasure Pile - Large
War Table
Wood Pile
Workbench

**Sewers**
Sewer Wall/Floor With La...
Sewer Wall/Floor With La... (2nd one)
Sewer Floor 01
Sewer Floor - Sluice 01
Sewer Floor 02
Sewer Floor 03
Sewer Floor Grate
Sewer Floor - Sluice End
Sewer Floor Sluice 02

**Tavern**
Chimney 01
Chimney 02
Village Roof Corner 01
Village Roof Inner Corner
Village Roof Side 01
Village Roof Side/Chimney
Blue Bed
Red Bed
Bar Counter
Bar Counter - Corner
Tavern Floor 01
Tavern Floor 02
Tavern Floor 03
Tavern Stairs
Tavern Stairs Block

**Comment by ellroch** [comment]
I've noticed this issue has some connection to the destination that the blocks are being pasted to. See gif:

https://gyazo.com/ad65e7844e0c194384057d2b4452ee7c

**Comment by laposheureux** [comment]
An example scenario where this manifests, copy this prefab text: https://talesbazaar.com/prefab/343

Initial preview:
![20200412164228_1](https://user-images.githubusercontent.com/13631960/79082702-6e65bf80-7cdd-11ea-8288-0325767fc994.jpg)

After click with preview hovering in the background:
![20200412164236_1](https://user-images.githubusercontent.com/13631960/79082714-77569100-7cdd-11ea-8034-1ffe49ed7d11.jpg)

Second click on -top- of first, everything appears properly:
![20200412164243_1](https://user-images.githubusercontent.com/13631960/79082718-83dae980-7cdd-11ea-93c1-44fed5ce93f6.jpg)

**Comment by viper5445** [comment]
I am having the same issue, this thread gave me an idea to try and work around until the bug can be identified. When an Item is copied off the ground level, when pasted back to the ground level the bug persists. Even when copied onto a notepad then pasted back on the the board the preview will look normal but the paste will not drop all of the tiles. If you drop the tiles above the ground level, then it will paste all tiles properly. You can then copy or cut those tiles from above ground to the ground level with no issues. Hope this helps.

**Comment by viper5445** [comment]
The hover of what is supposed to be dropped looks correct.
![20200413170417_1](https://user-images.githubusercontent.com/63489683/79104158-f5339e80-7da8-11ea-85b4-5c2867b04037.jpg)

What drops at ground level is missing tiles
![20200413170425_1](https://user-images.githubusercontent.com/63489683/79104272-32982c00-7da9-11ea-8691-9b64778088ad.jpg)

When dropped above ground level all tiles are present. Not shown but you can then copy those tiles to the ground level with no issue
![20200413170636_1](https://user-images.githubusercontent.com/63489683/79104313-48a5ec80-7da9-11ea-9f95-0c058c3bceff.jpg)

**Comment by cbaggers** [comment]
Great work folks. My current guess is the highlight tool is basing it's selection on the bounds of the object but the copy tool itself is looking at the lowest tile position. 

I'll clarify intended behaviour and then get on it :)

Might be related to https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/325

**Comment by cbaggers** [comment]
@Gladpus 
![TaleSpire - BuilderScene - PC, Mac   Linux Standalone - Unity 2019 3 0f3  PREVIEW PACKAGES IN USE  _DX11_ 2020-04-16 17 30 21](https://user-images.githubusercontent.com/1579326/79475560-1c3bdb80-8008-11ea-9b4f-ec707fc3dcc9.png)

progress!

**Comment by cbaggers** [comment]
I think I was wrong about my earlier bounds theory. It's probably all related to the fix I did with the discord community earlier today.

The TLDR was that due to floating point inaccuracies a tile may end up with a very slightly negative position, which means the paste tool doesnt paste it in the expected zone. However it also doesnt put it in the zone below as, from an earlier check, it believed that nothing should have been in that zone anyway (which is correct)

I think we should test this again when tomorrow's patch is out and see what varients of this issue remain
