### ISSUE TITLE
Percentile dice not adding correctly

### ISSUE THREAD

**Issue by nickom90** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#175]
**Describe the bug**
Rolling percentile dice does not add up correctly.

**To Reproduce**
1. Roll percentile dice
2. Check math

**Comment by hanoldaa** [comment]
More specifically, the 00 result on the d100 counts as 100, not 0.

**Comment by nickom90** [comment]
> More specifically, the 00 result on the d100 counts as 100, not 0.

Yes thank you, I couldn't remember last night what the specific math issue was

**Comment by DariusWolfe** [comment]
0 and 00 SHOULD count as 100. Are you saying that it's not, or that it is?

**Comment by l0calh05t** [comment]
Yes, the issue is only with the 00 which is always counted as 100, not only when the other die is 0

**Comment by kittiekatxmeow** [comment]
I was able to catch a screenshot of it

![image](https://user-images.githubusercontent.com/63488362/79051591-97f7eb80-7bf6-11ea-8dec-70fff19afcce.png)

**Comment by LuPro** [comment]
Duplicate to #37
