### ISSUE TITLE
When the second board is removed, all the options disappear

### ISSUE THREAD

**Issue by DaRuMe** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#19]
If you create a second board, and then, you delete it when this one is selected, it makes all the options disappear, you can't go back to the first board or anything, you have to exit to the main menu and enter again

To reproduce it
-Create a second board
-Open construction menu
-Select panels
-Eliminate the second board, which, you're
-See how the board is deleted and all the options disappear except for the configuration, help or exit

System:
Windows 10 64bit

**Comment by scherazade** [comment]
Came here to post this same issue. Had to Quit and to Main Menu and return to get tools to return.

**Comment by mgreco9** [comment]
You can press the space bar to access the board menu on the top left of the screen. But it's a bit inconvenient.
I think it could be improved by redirecting the user to another existing board or preventing the user from deleting the last existing board.

**Comment by LuPro** [comment]
Kind of the same as #5, check the description I gave there. Will reference #5 to this, because the enhancement idea I had is described here

**Comment by LuPro** [comment]
Happy to say that there should now be a UI information when you are in "board limbo" I think this is good enough, but would like to hear what you think - I would say this issue can be closed though :)
