### ISSUE TITLE
deleting the board your on breaks campaign

### ISSUE THREAD

**Issue by jmvanryn** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#193]
**Describe the bug**
I was on the board I was deleting, instead of moving me to the only existing board, it attempted to (I think) open a new board but broke the UI

I exited the game to the main screen and to the desktop but the campaign is in a bad state and always returns me to where I was.  It may have been the default board I was on/deleting. 

**To Reproduce**
1. make may boards
2. change default board
3. delete down to 2 boards
4. while on default board try to delete it. 

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![image](https://user-images.githubusercontent.com/3902567/79049907-63833000-7bf4-11ea-8606-42b8a540f77c.png)
[debug.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4465003/debug.log)

I could include the board files if I knew where to find them. 
**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Pruegeleisen** [comment]
I don't think the campaign is broken. Please try to press space and open the "Boards" menu in the upper left corner. From there you should be able to create new boards and set a new/old one as default. Let them know, if that worked. At least this works for me. This is still really unintuitive though.

**Comment by jmvanryn** [comment]
❤
![image](https://user-images.githubusercontent.com/3902567/79050697-c6c39100-7bf9-11ea-85c0-ef9502611528.png)
