### ISSUE TITLE
Token Tilts after walking over "uneven terrain" (bear rug)

### ISSUE THREAD

**Issue by Aeristoka** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#198]
**Describe the bug**
After walking my token over the Bear Rug, my token is stuck tilted

**To Reproduce**
1. Place Bear Rug
2. Step token over bear rug (done with Shift + Arrow Keys)
3. Token stuck tilted

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/7988297/79050387-e8ffe380-7be6-11ea-9188-fba8820bd354.png)

![image](https://user-images.githubusercontent.com/7988297/79050395-f4530f00-7be6-11ea-8628-c586613af8bb.png)

**Comment by LuPro** [comment]
Did you do any extra animations/requests? If so, it might be similar to #43

**Comment by Aeristoka** [comment]
That might've been it. I'd say you can probably close this as a duplicate of #43

**Comment by LuPro** [comment]
Recently tried getting both to work and didn't manage any - I only managed to get the thing with attacking and moving at the same time to introduce constant tilt to work. It might be both of those are still bugs, just more rare or you encountered this tilt accidentally while walking on a bear rug, I'll keep it open though until we can say for sure that it's nothing

**Comment by LuPro** [comment]
Closing this in favor of issue #791
