### ISSUE TITLE
Shift Movement moves camera far more than Token

### ISSUE THREAD

**Issue by Aeristoka** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#199]
**Describe the bug**
Shift + Arrow Keys/Shift + WASD movement moves camera far more than the token itself moves, causing the token to get lost

**To Reproduce**
1. Shift + Arrow Key movement/Shift + WASD movement

**Comment by Voidwalker1122** [comment]
Also having this issue. Very annoying when trying to play with my buddy and have him test out player mode.

**Comment by Razial7** [comment]
Also having this issue.

**Comment by LuPro** [comment]
Duplicate of #80
