### ISSUE TITLE
After deleting your only board, there does not seem to be any way to create a new board within the campaign

### ISSUE THREAD

**Issue by Maxnwil** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#20]
**Describe the bug**
After deleting your only board, there does not seem to be any way to create a new board within the campaign

**To Reproduce**
1. Create two boards
2. Delete both of them
3. UI Disappears, with no way to create new boards. Only option for escape seems to be "exit to Main Menu"

**Screenshots/Videos/Twitch Clips**

**Additional context**

**Comment by mgreco9** [comment]
Actually you can press the space bar to access the board menu on the top left of the screen. But it's a bit inconvenient.

**Comment by mgreco9** [comment]
Actually you can press the space bar to access the board menu on the top left of the screen. But it's a bit inconvenient.

**Comment by Maxnwil** [comment]
> Actually you can press the space bar to access the board menu on the top left of the screen. But it's a bit inconvenient.

Oh wow that's subtle
