### ISSUE TITLE
Copy Paste grass tiles dissapearing

### ISSUE THREAD

**Issue by Voidwalker1122** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#209]
When copying and pasting sections of terrain I have noticed tiles sometimes disappear, seemingly at random

**To Reproduce**
1. Create a large area of terrain. Grass possibly trees roads etc.
2. Mass select it all
3. Copy-paste onto a new area
4. Find missing tiles

<img width="960" alt="2020-04-11 (7)" src="https://user-images.githubusercontent.com/63479037/79052577-240d1180-7bfd-11ea-891d-efd659d167da.png">

**Comment by LuPro** [comment]
Could be a similar issue to #172, could you try following the steps there to confirm that? (both for reproducing and for avoiding it if possible)

**Comment by Voidwalker1122** [comment]
I was not able to reproduce the issues in #172, however, I only tried a handful of times. I was able to reproduce mine on the first try. And it has always worked on the first try to reproduce with mine as well. I also attempted to reproduce #172 on a larger scale by using around a 10 x 2 x 12 block area (5x2x6 lush grass tiles) and when doing that I had none disappear at all

**Comment by LuPro** [comment]
Together with the fixes that should have fixed #172 it might be that your issue got fixed as well, could you check if it still persists?

**Comment by LuPro** [comment]
As there hasn't been an answer in a while I'm going to assume this is fixed now. If the problem persists, please answer so this issue can be reopened
