### ISSUE TITLE
Dungeon corner issues

### ISSUE THREAD

**Issue by jhohen03** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#210]
Having issues with the dungeon pack, 1x1 corner + no floor block. when trying to place something on top of it, the new block is left floating a small gap above it. we have been able to fix it by deleting the corner and re-adding it, but have to do that every time we want to build above it.

**Comment by LuPro** [comment]
Possible duplicate of #123, needs screenshot to confirm

**Comment by jhohen03** [comment]
Yes it is. Thank you.
