### ISSUE TITLE
Table isn't loading

### ISSUE THREAD

**Issue by SirDaly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#215]
**Describe the bug**
I tried to load up my file but it's not loading anything - it's stuck on "Waiting for the adventure to begin"

**To Reproduce**
1. Open game
2. Select load file
3. Load

**Screenshots/Videos/Twitch Clips**
![Table not loading bug](https://user-images.githubusercontent.com/63475665/79054681-c8637800-7c3e-11ea-81a6-1ced65c9fea8.PNG)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Newest update put out a fix for many causes of this error. Can you check if it fixed it for you?

**Comment by LuPro** [comment]
As it has been 5 days, I'm going to assume this issue is resolved (as everyone who had this issue and who answered back had it resolved). If you still experience this, please comment so I can reopen the issue.
