### ISSUE TITLE
UploadBoardToBackend failure point 0: 3 - lots of work lost

### ISSUE THREAD

**Issue by PurpleGranite** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#220]
**Describe the bug**
Lots of work building out a board lost after exit.  Console constantly scrolling messages:
`UploadBoardToBackend failure point 0: 3`
`Board sync restarting`

**To Reproduce**
1. Spend a long time working on a board
2. Select all objects, copy
3. Paste string into a text editor for backup
4. Return to TaleSpire, open dev console
5. Observe error described

**Screenshots/Videos/Twitch Clips**
![Console Error](https://user-images.githubusercontent.com/8159386/79055432-f6e45180-7c44-11ea-863b-75dfb5342990.png)
The error being shown on the console.  These two lines are shown between once and twice a second.

![State Before Exit to Main Menu](https://user-images.githubusercontent.com/8159386/79055444-0d8aa880-7c45-11ea-9cf8-895003684735.png)
This is what my board looked like before selecting Exit to Main Menu. (Yes, that's a re-imagining of Cragmaw Castle from Lost Mine of Phandelver as a double-size board and squared off since there's no radiused / round walls).

![Console at Main Menu](https://user-images.githubusercontent.com/8159386/79055460-40cd3780-7c45-11ea-8366-3dc0c29baf4f.png)
This error was displayed on the console after exiting to the main menu.

![State after Reload](https://user-images.githubusercontent.com/8159386/79055480-60646000-7c45-11ea-83a3-a83bfe40f5bb.png)
This is what was on the board after reloading.

![State after Pasting copied object string](https://user-images.githubusercontent.com/8159386/79055505-90abfe80-7c45-11ea-9f10-9deec93cfcf6.png)
This is what was pasted from the object string I'd copied earlier as a backup.

![Console after Pasting object string](https://user-images.githubusercontent.com/8159386/79055533-ba652580-7c45-11ea-925c-003885d05a00.png)
This is what the console looked like after pasting in the object string.

Below is the object string copied as a backup.

```H4sIAAAAAAAAC7WdD3CcR3nGP53O8lm6yIosFFl1hSoCiMAQkzjlwLLuFBtyxE5xZwJcaWDUf3CkMFHptD0IoKMIxx2uiShKccLBiPGFKolI1EYNLhHRSYjggoiVxgOBGuqAS5ypTFz3ABGEr7f73d63u/fsEw0zaMax8/30vvu8++zu9//u8ecff6LBu8zbfl3x77ofX9976L9f8hePZt99dbN388SjD/Tk7vnat/cd+sqLDjz7/Y/+9rcq2w695IP/8O0/vfvahzJ/O7/pikuevKKy7fu7Go/en/jS/uzOvc/v/sOrT/xWZdsbf37zvSdyt77hs7//8cufvXTb7Q2VbVd95q/uXbn7bUNfvuPDH/nLz5+Pbq1s+8Rz98z8+N7nk3e8tbRnR/nya6+sbHvTbOND1+w5sP+21+37xeefeaJtc2XbrS+Pfa3zj9beXPjUS1/6lPeWR0KijYb3/PjDsejvFd73rvG1x7YeEr/3zD1X/c+5J/cPfbLQdue56Q/23t1488SWr3559cmee68/fMPjj/QsjO8cqvzeE+euPvdvazP7Pht95MXDO768FKlsy3d8/dwv35cdOtzypuLTyVe8TOTreGjb872fO3rDI0d3PrTtgXt/GBZt/HL3tvf97/ybj8T+6ab3fnP/nULLvSd6upbmv7L3vh/OTd3w/qufFvUujL7hZTc/nrh+9syrX3moa/+hrsq2n+z5+hXjH7hv36dj2cz3Tz65KmI73tv8mmPf+Oy18/9y890/+Y/RazZVtjV/7qH4nzzyzND9Pbc+M/nn78iJfK9uj70zf/6+63Iz3326b2riWeHRZ17UeMv2HZ+//rY/fvfQ3xdLMz2VbZ4XW/C8nYnCymjC87y4503Gj70zG480t2VfUXqzZJ63khDbBBO/E678p+P5ZzBrEOw2EjfvZM2/2rros66hYh3b7GJ7m3/VItnF8omEycS/l2R7q5sOLxj1NbVlv9MyUtVSnFdaLpbLg9Fyuex5vRV2urItq/4Mir/9nCNV5iV05lVqD1jWZPLnII67pC0bMCtu/xd/UPl9ydbKo5YW8VMsirowa6vmFLkDFjXYCGA7SdxOEneQxB0kcSOOOL2vrbhGXcvOhfraD2Im+3OExCWqLFE02KjOJovuuNOEtYH2hnF7BkPtDTvay44GDLXnj+tQHRNxtTE/74rDOnuJzl7SL7X54NXPlRHCvOpczpo5GxRz1e7HheScsee0P4/q4uRa4LMQrEExq/aj3kzAUJ8pLZ4zZ9j2oSFglT//6tZi59Trs/psKFhf7L4O+hNokf2iakBzRa0vh8kaYrHlwQuet1b11huq9/0pNc4SOosYLEGYuZZH5FpwluQ8i3PK2s/inDJuDef8ZzEm1nDOcJsWh3IexvsOg6F9zhEYFzZYFrApEjdF4o6TuOMk7hiJO0biHPtig6F+qY0JY1xbY6noZpOEnSbMXF8i3si1ATP3R5G2PW8M2MEFd84Rm8W18QnqO4vru+cqLa6uvmzA6urT4uz69PZ2EobqO+uqT58rZn3bxL/XiH9rxL81XN+3tmk5rfru2T4fMFTfGq7v5g9oOVF9ak5ba2TLwwOeF60c745UjnfjYD5EFqvzYag+ZxthXS62t7IPJ3HhRff6qRhakxWz17rs6/36XDmjOOfyAS0OrZ8dOGd7m8asnG06s3JeItgOnLNFZ1bOLTqzcja16f0C5m2tP8HYrflAGFqXFEPzVjE0rhVD81YxNK6jpL4oqS9K6ouS+qKkviipL0rqi5L6Okh9HaS+DlJfB6mvg9TXQerrIPV1kPp24PqWXzeojXmgcwepbweu7/YfPRIwq74fv6uyDnqL7mNMxY4QNgXYDlz7JnGOvgP3mcGsvm4S7PwCbG+LziydzTo7DNhpnLNFZ1bOqM6snPIaxArOaTArZ6vOrJxbVXsjCbvPPHkMfR4z+VM7HvR0Zh0rFuvZcRJ3HMfdVYxrx7sgbgrHyRqOkLgjROdhGOf3Czv3zcLjEP9cTTHrPNVg6BxdMXSeWjtmB+wYYVOEHcFM6iyq2kF9ilnn7yHBZnCcwVDcJImbJHHjJG6cxKn+tK5nffrBeMDQ9TPFzPXFv1Z5DOc02EHCUM4pknOK6JzCOUd1362cz921O2Ao5xGc05hH6LriYZyz5XcGA2bllPuVmeq6ZM4xL6TG4AuxnYRZa528jinnpPh/cXydqP47EQ2J9VMxz2SeHifHYMDWBmc05rnjimZc1tPay5pM+i611+uUORVDOqdI3BSJUzktnVE9zmLy/Kimc4FoMdkmwc4SnWeJzo7FcnnUESeOpVxxtZymRz8YuKAxUEMtJ/C2xkDcWdxnRlw9CwX1kZyI7Vp09+cu0i83krgbSdwuR7+I+baL9MuNJO5GR5ye06q9QdeC+vpGHGcwK+46ca1yioyJKTyWjHmL4g7iOPn/ly/4569dymOxv6seh6Sr7FUL/jZ/TfP37zHCwlWWBjlV3PGiHuev111VdruVU/ydrzJZRxAnczI2VmXiHqCtcyPM1BLtvGqP521f9Nn5hF5fpOV3K+vSZVUWGTKYXHsuc8Q9/HrP66yyp4CWzVVWAP15qqrzAbPPLhXXGUqYtYt9zmNVdr5oaNkm2K/b1w9U2bCZM6T3p+X7jnNX+X0sWBLUdzsZSxNV9iGzPjk356rsJtO/ipa5BjEfeisst3DTbR+Nq5zRWs6YVt+wjIu8IGtf9JnvX4Nim5R/gs3IWJ+J9sR1MMVWiiYTP48tIBbuUP7FtH6pxjW0EZ3ifJ7VcHuVefNGzhbBZqtspGjUF9Lj/DXErKFQZbsW9DhvVI9LgTizvhqT7R2U3q6Xr0xUfdXWiRFtTmtsq7r/rtYsjcmcvVW2y2DR2rmaGrsaM8andrxXO49jzKFTsvNVNgLaO03YCmE1LQv1WtR6Vts3SBaJ6qxospaHd/vXyARrq9UQEjXIuK1VljDjZHsq7jCoXa11nhHnfeHd8wEzdXpmnEdYsZ55i+4+Uzo/tFDP/JwXy7cs1NdXaw/0tWKTlhbxR7HDVk4Zuxis5faYV75brE1f5832/HX+bJXtM+uLiDVEsZtMJq+ls3Gt9gFmX1f6ZUBjhkeRlheaK0U8rkN6HOrrLJ7vkh2B893fd0wuIN/9uPuqrBf4fqzKwmC8PIbjQnqcNc5Cen8eNOsL6TkTdWzgV69dEGvLcGgmEXuVWOcn4962yr740rasYt73yo8aTPSKtyzZbZtWEmKbYOJ3RO0HvNCiYIc0NiBZdvBzF78q49LlowsJPefmtmy6/DHJejqL8ypu96vkOj/gZFtEfdO+TrmvFiyh7R8UGwcsjPtM/lxOxovaP6B1fqd2PKiNCfl8gWrPWlvlvkPN6SOgPTXH0Lztqm4rxv36/D/+GFTMs5jY1i/ZxfI8YDESl8Hsva+ZqR6X1TM5V1KYydrTjvbEj2pvJuFm44QNm+y14jhSsV6TNehxVn/esTjorF22FyM6Y0RnDOs8L/olhnXKv2NEp8s/8ZMkOpNY56P7FgM2TOLqdGoMjU/HePH08WLrFNtSpD9TRGeK6Exhndu3f8U5duV9rjTpzzTRmcY673zs6oAhnWnSnxuZRytGzogRZ7M2rV9QXJKwGGH9WOel8j5XUbC1cnmwvobIwgux+vVM/Pg5GavLKe/jsfZUDf0L9SxGWJKwFGYh3SMUlyEsUmUxwpKgPcVSJC5NWAawLqKli2jpcmgR27qIli6ipZ9o6cdaDIb6pZ9o6SdaYkRLjGiJES0xoiVGtCSJliTRkiRakkRLEmuR1zhTREuKaEkRLSmiJYW1yOOCNNGSxlqMOEvLa182EjCkJe3QIuIyWItx/GJp+bO3XggY6pcM0ZLBWo6Oa/NvvFgfp9hMsV6nYisk7jxhETLfu8j8Qzr7sU6DIZ39RGc/0dlPdMaIzhjRGSM6Y0RnjOiMEZ1JojNJdCaJziTRmSQ6k0RniuhMEZ0pojNFdKaIzhTRmSY600RnmuhME51pojNNdGaIzgzRmSE6M0RnhujMEJ218yqQM0lYirA0YRnCaufh825WJKyX5ETtxUh77NwwQ9rLEJ0Z0h47Z+4n7cU2wJAWdk6ZJDqTJKfj/M9kJA7lZOdqaZIzvYHaUZ+lCEsT1o/Hmbye5fCvUY+zdMrrPf24vhAZLwevuOAcu43Ed9ke88/hw1vEcxeO81Sp0z9vxOuSOgeymHFeZa1Zsj9Vzi4Q57MwHBN+TsbEPUyDfeGTe4I1JAdq6CcsRlgSswZ9DKK4tIOJbRnM5Ptqqr4x0F4XZkZ9FpPXdGKYSY+SmD38i0RQn8WMa5xISwazu4Yu+PftBUPXURSbIcy89hRp0Nkwieu1mNimWNGYDxHpg2LmXPHbO0NqOENqOINrkD6cwTUY7Vk1SB/O4BqM9qwaPil8WHXVkA3YDGhvFdcg21vFNXxKb8/2QY9DNaziGiQrER9KuIYGnaEaSmQslUgNJVJDidSwTmpYJ2NpndSwTmpYJzWskxrWSQ3smGiM1JcjbIKwPGEFwqYJmyVsjrAlwpYJO7kBhvrzJPTIZHXX2QcChu4jnIRjyX/X+SQcg2GjPqRzmehcxjrl88nLROcy1mkwS6c8LlgiOpeIziWs87ntgwFDOpewzgad2f3ZuTcYZ0jnHNE55/BdbJsjOueIzjni+yzROUt0zrrGp8aQzlni+yzROe3QKbZNE53TROc01rl590zAkM5porNA+rNAdBaIzgLpz4JDp9hWcOic3Besu0hnnujME515ojNP+jNP+nMC62zQmaXz4dxVwb4K1ZcjzNGeoZN5azF5f9oxdh8QcY75txwtutcQsY2tg461XD6P4twfZYM+s3y4QRzTjmH/pA9jDt/Fs5pjZLyMkXG2Ef/QeMmRcZYj4zNHdOaIzo2MJTaukc4JonNiA/2JtGSIlgzRkiFaMkRLhvTZRo4xkU7HGDQY0vmbGIPsWJg9z1A7F513syJh5vWsyE8+HNfOmU0WvkZj5jXxyNj189o5etHd3gph5wkzry9Fnhq9OmDmNSQzrp+wmMWyWn3mPcXIgw0/CliK5DTvKUYe0Jl5TzEi1+QzDv/EtjPEvzPYvy06s/xr0Jnl3w36dQbk3xni3xnsn9Ge5d8nvlkOmOXfDxsGA4b8O+PwT2eWf9fr9Vn+GTrTJGcGxK06/NMZ8m8V+yff+VnF/hlxln9y37hK/Fsl/q1i/wwWAf2yiv0zGPJvlfi3iv0zGJp/q8S/VeyfZCXiX4n4V8L+GQz5V3L4pzPkX4n4VyL+lYh/JeJfifhXIv6ViH8l4l+J+Fci/q0T/9aJf+vEv3Xi3zrxT42zHNCp2ITJNussbzL5Tq9iBZJz2mQRvc/GrJzifbwS0VnCOqM6q9O5O2BIZwnr3KL3Z53O3QFDOtexzojOLJ333bcnYEjnOtYp31cbg1rMY3aLbdbjrPsd0occZjJn02J1bg7V61QsYrO9ARPvU9pxzSRnM8nZTHK2kpytJGcrydlOcraTnO0kZyfJ2UlydpKc3SRntyunxlDOHpKzh+TsceWsjLM+krOP5Oxz5MwOBOPMOieRn+eomHVvIqQz696EfH9TMevexDad9RJWjBusXWeeyeS7wM24BvlsdjOuoU1nVg1bdWbV0KqzXsKsGi7RmVWD/FyjVlxDi86sGpp1Nk6YVcMWnVk1RHRm1bBZZx5g7biGJp1ZNWzSmVVDWGdWDY06s2rIifcR2nENIT3OqsETP524BoOhe3WduAaDoXt1nbgGgxWJTlRDN6mhm9TQTWroJjV0kxq6SQ3dpIYeUkMPqaGH1NBDaughNfSQGnpIDX2khj5SQx+poY/U0Edq6CM19JEaQqSGEKkhRGoIkRpCpIYQqSG0gbFknT/Iz6ao+V50x9nnD2JbbZwV3Tmt878GPSc6/6vt+0lO6/xPvnNQO9YwmXyWQ7F+wtD5n2LW+d+4eM5DMfv8T+8XdP6nGDr/q43BeTez/Hvuu49qYx70Z5/DP52h878+7J/c1kf868P+GXH2+bvOLP8a9Jzo/L2P+NeH/ZPjpc/hnx6XBuOlj/gXwv7JzwwPYf/kthDxL0T8CxH/Qg7/dIb8CxH/Qg7/9DjkX4j4FyL+hYh/IeJfiPgX2oB/Y4Sh83fFJsC4VixP4gqkz6ZBXBPR2YR1yj5rcujU4/Kgz5qwTiPO0nmq+H/accF8fVw38aEb+2cwtO524/FiMDTOuh3jU4+zryvqDM2HbjKPuh3zT2do3taOTUkc2k/Xjk1JTrQudTv8E9s6iX+dDv/0OORfp8M/PSe6z9VJ/Ot0+KfnRPujTuJfp8M/PSfyr9Phn3jmpJP414n9O779tHZ+RDxC86+d+NdO5l+7wz+dWf7tE2tPO5l/7cS/duJfO5l/7Q7/dIb8ayf+tTv80xnaT7eT+dfu8E9nln+vEKyV+NdK/Gsl/rVi/xp1hvxrdfinM3Rc0Ir9C+kM+deK/TPiZggbJ2yYsF7CLP8M5gHWjP0zWJow5F8z9s+IixHWD3xvxv4ZLEKY5Z/BVgibIWycsGHCegmz/DMYWj+bsH8GQ/41Yf8MhvxrIv41Yf8MhvxrIv41Yf+M+iz/LjWul1tx+vVry78GPc5+zsO4Xm6ykHG93PLPuF5uMnlNVd1vHAN9pp6RmCasAPpMsTxhE4TlCBsD7BTWaTCk8xTReYroPEV0nsI65Xg5iXUaDJ1bnMQ6QzqbICxHGPJ9Ges0GNK5jHXKbctYp/yMnmWsU86VZUd/CraEdTbozNIp71ctYZ2Nepztu84snWGdWTrlPY2NPHNZxwa0ZxKLBpP37WvPJM7X56y1Z7MBpxZ53549p+qsQXvXxNJpPEuMdJ4kOh3PIG/Wxxl633fZ1Z72ronV3hY9DtW+5GpvQHufBORcctXnkWezB7T3O+z2tHdGUH/O4fbk90mxd01mSX/O4vZkzllSH3tnZBq3t7z8eu09DZBzmrTneH5++cBu7b0JUF+BtFdw9Ofybv4OR560lyfjJU/qc71XILZNOPpTPIs6gduTz7BO4Pbk+wiOdxzkPiBH6suR/sy5+nNgY2sPas+xDi4f2EPWQY+vyY7a5fj8Nd7vkMz1bpL4YXOFzVvHGiLHJ1vP2PuGjv3R8oGBjX1OBvt8DTTfa+8pAm+XMZP1LWEmn3meIzlnCZsmrEBYnrAJB/vHvdq7JiBubAP9gj43RjH0uQ6K2Z9TI7bV3l0l7aHPxam9ownYEtG5RHQuYZ1vfcde7f1bUMMS0bmEdf77lfPBeLF1ZjVm6VyOJgKGPvdnDuss68zS+bZb49o7miZ7z+Ujwdi1dI6KnLOkP2eJzlni+yzWWb6jqL2jCeKmie/TLp3ZgCGd0y6de7V3LU0m322ZxjrD18wHc7pOZzZgls6jM/GAnQftFbBOg6HxWcA6lw/Eg/WlbnxqDPmeJ/2ZJ77nic488X2C+D5BdE4QnRMOnV9q0N6dI3G2ThGXIzpzDp16nKVTPpORI/2ZIzpzpD/HiM4xrDOhv4eJ+nOM6BwjOseITrUPMK8Bho3rBdbnMjbqLEVYEtSumHkN0HzfPgNyLhEtS1iLvO+7hLUY7Vla9j/102AtR1rmsBZPZynQ3hzWcr3eXgzknMVa5Lo0i7V87Nn5gKVIHPJolmiZxloMhvplGmuRa/I01mKwGGAFrMVgtpasxlJAZwFrkccaBdIvedIvedIveaIlTzzKEy0TWMt/XXg6YEjLhEOL+k4el5YJhxYRlyP9kiNaclhLo86QlhzplzGiZQxradCZpcV4b97SUtbjLC3y8/XVOmje7/DX3SXMvOJlwTphsbmd2py247zjwTyqY9lgXNcxbZxZbFT3HcXlCBsj7CT2qFFnaB9wEntk5EySuBhhTCfavyuGPoNPMWv/brAVwmYIGwdsHfanf79jHfanfz9gHfanyax7fB1tGrPvsYtr6euwP/17Z+uwP01m32PXc9r3aHVm3eML68y6xyev+Qvtp+PBs8vqe8jEMy6KrRjM/1y4TJXNGCxc62PAap8RieLETxKzB8VnRPo1B98RoMf5feVmpzWPfOZ/h0wXYap2dZ1IZ0rnGIhLYSbX1jSJyziY6M9SdZt6h0p5pMYnYLK9ZdLXY4TlCJsgLE9YgbBpwmYJmyNs6des3TWuxY94Put0XV8Hz/7UzxWv9l2SgMmfbsJ6XGyv/1yzK048i+oaL00y7mL5BKivaRGOwdqzqILlwNhVbMJktWdRBcuTuILJZvZeCNg0mA9qfKK5qZjaP+i1KzZssgad9YI4NY+6QA1LmMnP7J8jcbOYyff4pjGTx2AFzMoiZx4zeQw2QeJyJE7VHgE1KKb2R4itmMxcl0Cc6JeRRLDfrPog9+HThKm4GGFJwlKAiZon4/b+Njr0xR+E5DbAZH0+Czs/J9jFVE7r3sR+9fm7gMn2xHwXzHyP1pPrhGLme7Qi6p3t4vvVdia+8Zbi/PidYl5Nxifu93247qf+d9JFv/eR+Pj9nmS3V35HrHVP/Oznkr3/RSsJPU7s+0/87DuYVfrsxM8+XcfG7/drnzx3i5MVnve/y+7KLUcWlBbxO+IdzWfDZxfeHulK/E24N3H6U6PxlWuLg4OleVnDs+EVyf6asOSp8qMGC7d5KmcdaxLHZ+J7H8X3oN4oj6lq358qf8T3PgI2pL5jpS1hr63hh94R948L2hKh2nGrvT8CcbXPOt5Zz2RcCrNXdl7w15BEomwdLwXf49dbz5bFO1TTVS1qDNnzti1xsfxgol7LXDXOtQ8XOocJGwcsT9orVONcxxouNkvaE3EHEz+vfbdVdnC90kd6e+vlFxMtxTjO2eZghQ0w7zfP5HMJYpwNJ1rbxXeWClaMj98yWt03+uzMf8YNFnnurt3+2I0kVkLqmKE37r3dXz/9OMAalA+RRLxFHdv0xtf+QO8zFysQtlT1QR1PTPrrtXx3PAnnWFBfPfPHvBrX5ngx2TBgsyROjYkZwAqE5eF4MeN6He3Vj8/gHCihx8nf8Z8FV2zFZDKuv8pq++l4kDNSZbEFd1ztmMFn8vN3VXu1Yz6QM2e2VzuuS+hzU9vf5mCcJ5OK43LB1D5V16m+G77LYGH5uTFNi/73EJ8A7TUtBt/HrrVnsNSCO27a1CnrO7UQfFe7prOlTWNmzugl+nfRm3HhrToz4zx5zSMHffCM/jT9C57FqR8TXm0M1o+J8Da9vRjoFxWXMXOOvHwkYBGzX2TcEmTB9UiQ02ApwGZxX0t2dsGfQ9lKv5we8v9dHPp/2Kr9q9yfAAA=```

**Additional context**
Note that after pasting, some copied objects are not present.  I've observed missing objects when pasting several times.  Exiting to the main menu and re-loading again still showed the map in the same incomplete state as it was before pasting in the copied object string, indicating that the sync still wasn't functioning, even though the console did not indicate any errors.

At the moment, there appears no reliable mechanism to save a board.  Autosave does not appear to work, and has no indication to the user whether it is functioning or encountering errors.  There is no manual save.  Copying the content of a board and saving as a string outside of TaleSpire results in incomplete boards when pasted back into the system.

Possible related issues: #115, #219, #209 (and likely a couple of others.

**Comment by cbaggers** [comment]
@PurpleGranite excellent report. This has everything I need.

The `failure point 0: 3` tells me that the backend didnt think this you were the GM. This lines up with a bug dealt with on Tuesday where these server was losing session information.

Your second console screenshot actually showed a seperate bug. 

The BoardSessionManager was missing due to the transition to the Main menu but the upload was assuming it would be available (which was dumb as being able to continue an upload from the main menu was a design requirement). This should be fixed in the next update (going out 2020-04-17)

The paste bug where some objects go missing may have also be resolved today too. I did fix one this afternoon but I'm not sure if there are multiple (I'm working through the list now that two of the most common board destroying bugs have been resolved)

Thankyou once again for your excellent report and I'm sorry for the inconveniece.

**Comment by PurpleGranite** [comment]
I've done a couple of quick tests with the latest patch (from today), as far as I can see the main issue and all the sub-issues I was seeing seem to be resolved - will close this one out to help you guys declutter, and open a fresh report if anything else crops up.

TaleSpire rocks, and I'm sure it's going to go from strength to strength through the Beta - looking forward to seeing what comes next :)
