### ISSUE TITLE
Hid a hero model and couldn't get the menu back up tp unhide it

### ISSUE THREAD

**Issue by MicahMonarch** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#221]
**Describe the bug**
Hid the burly cleric model but upon reselecting it with right click, it wouldn't bring up the radial menu to unhide it.

**To Reproduce**
1. Produce model
2. Hide model
3. Cannot select model again

**Comment by Laufia** [comment]
This may be working as intended. You need to access the GM Overlay by clicking TAB to see the things you've hidden.

**Comment by LuPro** [comment]
This is indeed correct, pressing tab (opening gm overlay) show the hidden token and give the ability to show it again
