### ISSUE TITLE
Corner Alignment

### ISSUE THREAD

**Issue by Sephicien** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#224]
**Describe the bug**
I'm building a tavern and a corner waall section does not align with a straight wall section. 

**To Reproduce**
1. Place some 1x1 tavern floor sections
2. Place the tavern Wall Corner 2x2 section
3. Place the Tavern Wall 01 section
4. See screenshot (maybe do this first)

**Screenshots/Videos/Twitch Clips**
[Corner Alignment](https://user-images.githubusercontent.com/63523746/79057313-c5a85900-7c25-11ea-9931-06ec06592d7f.png)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Duplicate of #21
