### ISSUE TITLE
Handling placed tile crashes the game and corrupts the save file

### ISSUE THREAD

**Issue by SyfleNov** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#228]
I was trying to figure out why #87 was happening. So I tried other things as well. I tried interaction with a placed tile and it crashes the game.

1. Place tile set
2. Interact with tile set like move or delete
3. TaleSpire crashed
4. Relaunch the game
5. Access the campaign and it corrupts the save.

Video :
https://youtu.be/nsRKLtH1geY

I don't know why tile interaction is bugged? It seems to work fine on my friends computer.

**Comment by LuPro** [comment]
Is this reproducible for you? as in, is it consistently happening or just a few times if you do that?

**Comment by PolyurethaneNinja** [comment]
I'm having issue #87 as well and this one too, every time.

Windows 10, Intel Core 2 Quad Q6600 2.4 GHz, 8 gb RAM, Nvidia GeForce GTS 240, DX12

**Comment by Mr-Kromb** [comment]
I had the same issue. Any time I tried to move, delete, or teleport a placed tile, and the game would crash. I'd restart the game and play the campaign I was previously on, only for it to crash while loading. Happens every time I move, delete, or teleport a placed tile.
Oddly though, I could copy a placed tile with no issues.

**Comment by LuPro** [comment]
@Mr-Kromb out of curiosity, what CPU model do you have? It seems those kinds of bugs happen on older hardware (at least that's the current best theory, could just be coincidence)

**Comment by SyfleNov** [comment]
It is currently reproducible every time on my machine. I think that theory might have some weight.

**Comment by Mr-Kromb** [comment]
> @Mr-Kromb out of curiosity, what CPU model do you have? It seems those kinds of bugs happen on older hardware (at least that's the current best theory, could just be coincidence)

I run Windows 10 on an AMD Phenom(tm) II X4 955 Processor 3.20 GHz, 8GB RAM, & NVIDIA GeForce GTX 780.

**Comment by Chezeret** [comment]
I've had the same issue myself. Every time I try to move or delete and asset, Talespire crashes for me.

**Comment by LuPro** [comment]
> 
> 
> I've had the same issue myself. Every time I try to move or delete and asset, Talespire crashes for me. And I am certainly running on older hardware, though I don't remember the exact specs off the top of my head.

@Chezeret (Assuming you're using Windows) If you go to the search in the bottom left and enter "System Information" (should also work if you have a different language of windows installed as long as you write it out completely) it should open a window that shows a bunch of stuff like this:
![image](https://user-images.githubusercontent.com/20774976/79141996-21581b00-7dbb-11ea-841d-19196de4dad3.png)
The lowest line in my screenshot is the CPU model, could you check that for me?
I'm going to assume it's an AMD Phenom II though, as most of the reports of this kind have been with this series of CPU

**Comment by Chezeret** [comment]
> > I've had the same issue myself. Every time I try to move or delete and asset, Talespire crashes for me. And I am certainly running on older hardware, though I don't remember the exact specs off the top of my head.
> 
> @Chezeret (Assuming you're using Windows) If you go to the search in the bottom left and enter "System Information" (should also work if you have a different language of windows installed as long as you write it out completely) it should open a window that shows a bunch of stuff like this:
> ![image](https://user-images.githubusercontent.com/20774976/79141996-21581b00-7dbb-11ea-841d-19196de4dad3.png)
> The lowest line in my screenshot is the CPU model, could you check that for me?
> I'm going to assume it's an AMD Phenom II though, as most of the reports of this kind have been with this series of CPU

It is indeed an AMD Phenom II X4 965.

**Comment by kuhnsnr** [comment]
I'm seeing the same issue when I drag and drop or attempt to edit a placed item. My CPU seems to match the hypothesis:

Processor	AMD Phenom(tm) II X6 1055T Processor, 2800 Mhz, 6 Core(s), 6 Logical Processor(s)

**Comment by LuPro** [comment]
The latest update introduced a likely fix for this, can you please check if this works for you now? Especially interested in a report from @PolyurethaneNinja as they are the only one without a Phenom CPU iirc

**Comment by kuhnsnr** [comment]
Confirmed as resolved for me. Excited to start building!

**Comment by Mr-Kromb** [comment]
Confirmed as resolved for me as well! Thank you all for your help.

**Comment by SyfleNov** [comment]
Thanks for the update! This fixed it for my side. I am able to place multiple with drag click, and interact with tiles by moving or deleting. It doesn't corrupt my map, and everything seems to be working fine!

Thanks for the help!

**Comment by PolyurethaneNinja** [comment]
This update fixed my issue as well on my Pentium processor computer! So excited to try it out!

**Comment by Chezeret** [comment]
Sadly my computer is not functioning currently, I will test this out when I
get it up and running again. Sounds like it’s fixed though.

**Comment by LuPro** [comment]
Looking from the reports it seems this is fixed for everyone - I'll close this issue now, if any of you still have related problems, please do report them and we can maybe reopen the issue.
