### ISSUE TITLE
Mouse Pointer Jumps Away from miniatures

### ISSUE THREAD

**Issue by takkless** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#229]
**Describe the bug**
Left clicking and releasing a hero mini causes the mouse pointer to jump away (up and to the left) of the mini, and causes the focus light to skip further to the left and up until moving the mouse again causes it to skip back into sync with the mouse pointer.

**To Reproduce**

1. Produce an environment.
2. Import hero minis.
3. Click on or "pick up" minis and release the mouse button.

**Screenshots/Videos/Twitch Clips**
https://drive.google.com/open?id=1yakrvC7A4c2zfs3CEdMFSeeYCXF5c1Cm

**Additional context**

**Comment by jonnyree** [comment]
Thank you for the report @LuPro 
This has been addressed in the update: BUILD-ID: 4910231 17th of April 2020.
I would be very grateful if I could get a confirmation that this has been fixed.

**Comment by LuPro** [comment]
Assuming everything is fine, if the problem does persist please reply here. I'm going to close this issue.
