### ISSUE TITLE
Endless "Waiting for the adventure to begin", actors never load

### ISSUE THREAD

**Issue by JustinTuesday** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#236]
Dragon Build

Unable to load into one of two campaigns (second I have created, with only one. Stuck at the 'waiting to begin' text box. Assets never load.

> Begin
> select the erroring campaign > play
"Waiting for the adventure to begin" endlessly
'x' to quit > exit to main menu > yes
(repeatable)
#Alternatively I can open my first created campaign
> Begin
> select the first campaign I created > play
"Waiting for the adventure to begin" while assets load
assets load and it's business as usual on this campaing
'x' to quit > exit to main menu > yes
But then continue to have errors on the erroring campaign.

When failing to load the hourglass is spinning. Settings, Toolbar Help and Quit are all selectable and acting normally. F1 works to close the Toolbar Help toaster pop. I have tried closing and reopening the game. I have closed and reopened both the erroring campaign and the correct one multiple times. I have waited 10-15 minutes at the waiting to load screen with no change.

**Comment by Mufahasa** [comment]
Also having the same issue here 
Able to load one campaign with a smaller structure but my larger structure refuses to load it's associated campaign

**Comment by JustinTuesday** [comment]
Good perspective above. For reference: The map that isn't loading for me has a smaller asset count than the map that is working.

**Comment by bloodorange231** [comment]
same thing happened to me. made a small map with about 10 to 15 npc with two buildings an the entrence to a castle. I leave the come back to find that it no longer loads up. this is the 4th time this has happened. it might be something to do with the castle blocks because this only happens with after I start on the castle

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

**Comment by JustinTuesday** [comment]
My instance of this issue has resolved, I am able to load the map I was having issues with previously and all of the assets are there minus a few changes that maybe didn't get saved
