### ISSUE TITLE
“Waiting to begin” Loading endlessly

### ISSUE THREAD

**Issue by ShiroShiShiro** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#239]
I am unable to load my campaign. The error I am receiving is “Waiting to begin”. There are shadows of my buildings and I can access the TAB button. There was a second person that was helping me in the campaign. He was set to a GM status.

Open TaleSpire
Select the campaign > play
“Waiting for the adventure to begin” I can move around and can see the shadows.
I have left this for upwards of an hour to load assets.
No assets load
I can open other campaigns and they load normally.
When failing to load the hourglass is spinning. Settings, Toolbar Help and Quit are all selectable and acting normally. F1 works to close the Toolbar Help toaster pop. I have tried closing and reopening the game.

**Additional context**
Just wanted to say a massive thank you for making this! This is the most beautiful interface I've ever used and probably the best DND program I've ever seen. Im super keen to see what you'll release in the future.
Thank you

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

**Comment by LuPro** [comment]
As it has been 5 days, I'm going to assume this issue is resolved (as everyone who had this issue and who answered back had it resolved). If you still experience this, please comment so I can reopen the issue.
