### ISSUE TITLE
"Waiting For The Adventure To Begin"

### ISSUE THREAD

**Issue by JameserThe5th** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#240]
When I go to load a certain map, I get a never ending "Waiting For The Adventure To Begin" loading screen. I can click tab and see the markers I have placed. Bringing up the menu only works some of the time. I have tried to duplicate the map and get the same unending loading screen.

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

**Comment by LuPro** [comment]
As it has been 5 days, I'm going to assume this issue is resolved (as everyone who had this issue and who answered back had it resolved). If you still experience this, please comment so I can reopen the issue.
