### ISSUE TITLE
Unable to un-hide enemies enemies / NPCs.

### ISSUE THREAD

**Issue by Taglion13** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#246]
When I use the 'hide' command on an enemy to make them invisible to the players, I am unable to 'un-hide' them and make them reappear with the same stats that I have given them and instead have to just resort to dragging a new NPC in and change the stats on the fly.

**Comment by TaleSpireNoob** [comment]
Hey there, saw this issue earlier as I had the same problem, if you press tab on the keyboard you open up the GM Overlay which should show the hidden enemies. Worked for me, so hopefully it works for you!

**Comment by LuPro** [comment]
Would say the same as the comment before, hidden miniatures are completely invisible except in GM Overlay (by pressing Tab). Check out #89 for a related bug to this though. (If this is not the case though, please let us know, until then I'll close this as it's a duplicate)
