### ISSUE TITLE
Copied tiles don't all drop

### ISSUE THREAD

**Issue by viper5445** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#249]
Describe the bug Some tiles get copied but do not drop

To Reproduce Steps to reproduce the behavior:
1.	Select tiles for copy
2.	Tiles appear to be copied and float
3.	Tiles do not paste onto the work area

Screenshots/Videos/Twitch Clips These are worth their weight in gold!
![20200412204902_1](https://user-images.githubusercontent.com/63489683/79068233-653a1a00-7d00-11ea-9e11-5def007b7216.jpg)
![20200412204900_1](https://user-images.githubusercontent.com/63489683/79068234-679c7400-7d00-11ea-8e33-244c36779d6f.jpg)
![20200412204905_1](https://user-images.githubusercontent.com/63489683/79068236-68cda100-7d00-11ea-81f0-cd30a6c83823.jpg)

Additional context Unburden yourself of thoughts and musings here
When copied onto a note pad and back in, the same result happens. looks like all tiles are there but won't drop.

**Comment by LuPro** [comment]
Could be the same issue as in #172, could you check if you can reproduce/avoid with the steps given there?

**Comment by viper5445** [comment]
It does appear to be the same issue. And I am able to reproduce the issue
and avoid the issue as well.
