### ISSUE TITLE
Campaign starts but tiles don't load.

### ISSUE THREAD

**Issue by FeralSnek** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#253]
I can join other campaigns, and they'll load without issues. But when I load the one I've been working on the tiles never appear. It's just "waiting for the adventure to begin" in perpetuity. :( I had a really kick-ass dwarven mine going, too.

![20200412100837_1](https://user-images.githubusercontent.com/63480211/79070860-558de780-7ca6-11ea-82c4-bba44eea671a.jpg)

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)
