### ISSUE TITLE
Hidden enemies names still appear 

### ISSUE THREAD

**Issue by wolfbear3141** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#262]
**Describe the bug**
I hid a bunch of goblins but when I was looking for names theirs still appeared even when they're tokens were invisible

**To Reproduce**
1. Place goblins on the board
2. Hide them
3. Hold tab, seeing every name on the board, even theirs.

**Screenshots/Videos/Twitch Clips**

![image](https://user-images.githubusercontent.com/63504815/79071436-be2a9380-7ca9-11ea-805f-ba19f4c18c20.png)

**Additional context**
Thanks so much, loving the beta so far, can't wait to see how it improves

**Comment by LuPro** [comment]
Refer to #771 from now on.
