### ISSUE TITLE
Constant crash issue -- most actions in build mode cause instant CTD

### ISSUE THREAD

**Issue by MeisterKeen** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#265]
**Describe the bug**
Doing any action with tiles in the app other than placing them one by one causes instant CTD.

**To Reproduce**
1. Place multiple tiles
OR
1. Delete a tile
OR
1. Pretty much any other action using tiles.

**Screenshots/Videos/Twitch Clips**
https://youtu.be/lRhCKhEJjKo

NOTE: crash issue persists through update of April 12.

**Comment by MeisterKeen** [comment]
I've gotten a couple of comments on the YT video -- I'm not the only one! And it seems it might be an issue specific to older AMD architecture? Specifically old Phenom processors.

**Comment by LuPro** [comment]
not necessarily older amd, older intel seems to be affected as well, but yes, older hardware seems to suffer from this (see #87 and #12 for most of the discussions there). Did you also get corruptions for your savestate?

**Comment by LuPro** [comment]
The latest update introduced a little guy for this, could you check if it works for you now?

**Comment by LuPro** [comment]
I'm going to assume this works now, if the issue persists please comment so I can reopen this
