### ISSUE TITLE
Creatures refuse to be hidden via hide volumes

### ISSUE THREAD

**Issue by Icarus03** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#269]
I made a small structure and wanted corridors and their accompanying creatures to be hidden. I at first placed the hide volume in the main corridor and then added just a regular test creature (Cave Bear). I made sure the hide volume toggle was on, as I could see some shadows of the lanterns I accidentally included disappear. The bear would not disappear. Deleted hide volume and placed new one specifically on top of the bear and the bear only, toggled back and forth while closing GM overlay, Bear did not hide until I used the GM tools to hide the creature manually. 
![Screenshot (9)](https://user-images.githubusercontent.com/47799177/79076670-05288100-7cca-11ea-95bc-b3b23c774a08.png)
![Screenshot (10)](https://user-images.githubusercontent.com/47799177/79076672-06f24480-7cca-11ea-9671-df3a534d833e.png)
![Screenshot (11)](https://user-images.githubusercontent.com/47799177/79076673-09549e80-7cca-11ea-9f1e-edb2bb742ccd.png)
![Screenshot (12)](https://user-images.githubusercontent.com/47799177/79076674-0b1e6200-7cca-11ea-8cbe-c84781c2d7da.png)

Above are screenshots I've taken that showcase the bear inside the hide volume, what it looks like when the hide volume is toggled on and off (lantern shadow present and vanished, which I indicated via highlighting with the volumetric selection tool), and the player miniature still being able to see the bear. Thanks for everything!

**Comment by Mercer01** [comment]
Creatures have their own seperate Hide function if you right click on them.

**Comment by Icarus03** [comment]
Ah, I see. And there’s no way for them to be hidden via hide boxes? Would
make ambushes and the likes easier instead of having to reveal each one at
a time. I understand if there are more pressing matters :)
