### ISSUE TITLE
Copy/Paste Not Lining Up

### ISSUE THREAD

**Issue by DocLemming** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#272]
**Describe the bug**
Copy/Paste the building walls no longer lined up with grid

**To Reproduce**
*Copied outer wall of structure
*Pasted onto same board grid no longer lined up
*When I created it I was able to place the first piece on the inside 1/2 of the grid, but the paste pushes it to the outside 1/2 of the grid.
*This caused the wall to not be able to modify without having to remove the entire length then rebuild with clipping it into the other side walls.

**Screenshots/Videos/Twitch Clips**
1st ...Original (Darker) wall as you can see the grid shows the outer wall is on the inside 1/2 of the grid square.
2nd ...This is the copy/paste wall you can see this time the wall was placed on the outside 1/2 of the grid.
3rd ...I made these two manually and was able to freely place them in either 1/2 of grid square.

![CornerPaste2](https://user-images.githubusercontent.com/63548702/79077236-fe9c0880-7ccd-11ea-8127-103f6fa27246.jpg)

Here is the copy/paste corner again you can see because it placed it in the outer 1/2 of the square.If I try and make the portion shorter or longer. It now requires me to clip it into the side wall and also remove every part of the wall and rebuild it.

![CornerError](https://user-images.githubusercontent.com/63548702/79076904-57b66d00-7ccb-11ea-929f-7728f40daf39.jpg)

This last one is a copy/paste which I did after the first picture. By doing a copy/paste of the original and copied wall portion that is not lining up as the original. Then pasting the two the original does line up correctly and allows me to adjust the length. So it appears another tile/prop is needed to keep the originals alignment though it does have to be in the outer 1/2 of the square. So that the rest keeps it's alignment to the inner 1/2 square.

![CornerError2](https://user-images.githubusercontent.com/63548702/79077201-b11f9b80-7ccd-11ea-896b-ca50765cc5d4.jpg)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
This should have been fixed by today's update, can you please check if this is the case for you?

**Comment by MrMonop** [comment]
The issue seems resolved!
