### ISSUE TITLE
Placing tiles inbetween grid cells

### ISSUE THREAD

**Issue by Karpason** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#276]
**Describe the bug**
Placing walls on the sides of some tiles and then cutting/copying the whole thing allows to then place the copied slab in such a way that the tile between the walls ends up inbetween the grid cells, where it's normally impossible to place a tile.

**To Reproduce**
1. Place a tile on the ground.
2. Put walls on the opposite sides of the tile.
3. Copy or cut both the tile and the walls.
4. Place the copied slab onto some other tile (doesn't work if you try to put it onto the board itself)
5. The initial tile ends up where it shouldn't normally be: inbetween the grid cells

**Screenshots/Videos/Twitch Clips**
The whole process is here:
https://youtu.be/BLVxqLTVnHg

**Additional context**
I didn't experiment with this bug long enough to know exactly what you can use to get the effect, but roof tiles, fire, floors all can be placed inbetween the grid cells. It also works with clipping both on and off
Also, this is actually a very handy bug, so please don't immediatly fix it. At least leave it until you implement something that would allow to move tiles horizontally half a cell at a time. This bug right now is actually a cool feature

**Comment by AzaronM** [comment]
Can confirm this bug as shown below from left to right:
1. Start any 0.5 unit size tile and any tiles beside it then copy
2. When pasting, the 0.5 unit size tile will be snapped to the grid
3. Which cause all the added tiles to be offset by 0.5 units

![image](https://user-images.githubusercontent.com/63628402/79185130-37b2b500-7e55-11ea-8090-d573d0e03b27.png)

I think a better fix for this bug would be to allow wall tiles and wall like props (doors, etc.) to be placed in 0.5 unit increments in any direction. I would also help with not having to rely on inside corner pieces in most cases.

**Comment by DMTorren** [comment]
I second making this into a feature. Allowing to place props at the grid intersections and mid grid lines (aka 0.5 increments of the standard grid) would make even the current asset base immensely more powerful and usable!

**Comment by cbaggers** [comment]
Hi folks. The issues of placing all tiles on the half-grid is one of data density and plays in to the worst-case complexity of many of the operations we want to run on boards. We will iterate on what we have but for now I need to treat this as a bug and fix it.

I have a very minimal test case showing an issue with copy/paste and 1 tile.

![copySizeBug1](https://user-images.githubusercontent.com/1579326/79853272-1eb38200-83c8-11ea-9253-63377f042d5a.gif)

**Comment by cbaggers** [comment]
I played around with fattening up the bounds but it's not nice as it makes placement in populated places harder.
![copyPaste3](https://user-images.githubusercontent.com/1579326/79868548-59291900-83e0-11ea-9d54-4a214e8a4aec.gif)

I'm going to have to store the fact that the slab origin was on the half tile in the slab info and use that info when pasting

**Comment by cbaggers** [comment]
This prefab used to be an issue https://talesbazaar.com/prefab/753

https://user-images.githubusercontent.com/1579326/79890581-fe071e80-83ff-11ea-87bb-d2df0e53a2ea.png

**Comment by cbaggers** [comment]
Patch pushed!
If you have time please check this out and see if it solves some or all of the paste alignment issues

**Comment by AzaronM** [comment]
Fixed for me, I will attach a gif once it is created.

I do have some 'assets' that were made before the patch that can still be copy/pasted though:
![Untitled](https://user-images.githubusercontent.com/63628402/79961410-d5495c80-84c5-11ea-83cf-2670099e7e11.jpg)
