### ISSUE TITLE
Copy pasting adds extra empty cells and doesn't paste where is highlighted

### ISSUE THREAD

**Issue by SirDaly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#280]
**Describe the bug**
Trying to copy paste a wall together but it either pastes your copy a cell out, or adds extra empty cells which means you can't put it in the right place.

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy stretch of wall
2. Attempt to paste it against existing wall

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
[Copy pasting errors.zip](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4467115/Copy.pasting.errors.zip)

**Comment by LuPro** [comment]
This may have been fixed by the last update, could you check if this works for you now?

**Comment by SirDaly** [comment]
I've just tested and it seems to be fixed - thank you!
