### ISSUE TITLE
Board not loading.

### ISSUE THREAD

**Issue by Schmuky** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#283]
I have 2 board right now, a "Building board" and a game board. I use the building one to well...build. Just finished all the pieces to make a town and decided to build in on the game board. Spent a few hours making it and it is bigger than the other.

I swapped back to the building one to test something and when i wanted to test back, i entered a "Waiting for adventure to begin" loop. Lasted about 5 min before i tried to do something.

What i can still do:
->use the buttons on the top right (setting, exit), which allows me to exit to Main Menu and to Desktop
->use the buttons on top left (boards, atmosphere) which allows me to change back to the building board (no issues loading that one)
->move around the map while the prompt "Waiting for adventure to begin" is on the screen. I am moving on an empty board, nothing i build is there
->copy boards. I tried making a copy of the board, same issue.
->change the atmosphere (day night, effects etc)

What i tried:
->exit to menu, exit to desktop, same thing
->copy of original board, same problem

How to recreate:
->no idea, it might have something to do with the size, i started by making a big canvas of grass, maybe 400x400 tiles, so maybe i exceeded the size?

Not sure if Screenshots are helpful, but here you go
![Untitled](https://user-images.githubusercontent.com/63563915/79081264-75fc8700-7d24-11ea-927e-d5b2021d960a.png)

**Comment by Schmuky** [comment]
Update: managed to get some progress by setting the board as default. It still dosent load the building, but it shows their "footprint"
![Untitled2](https://user-images.githubusercontent.com/63563915/79081528-f2906500-7d26-11ea-8a7a-2bff3813a6b9.png)

**Comment by Schmuky** [comment]
buuuuuuut it took away my ability to open the menu on the left so i can't change boards anymore.......

**Comment by mawestover** [comment]
I'm seeing the same thing, but I simply tried to create a new board. I can navigate around the new board, but the "Waiting for the adventure to begin" message simply doesn't go away, even after at least 10 minutes.
![image](https://user-images.githubusercontent.com/63564868/79081747-67d74800-7cdd-11ea-9ca8-0f26234d1a06.png)
 I can only interact with the icons in the upper right or simply move around the board or move teh camera. No errors appear.

**Comment by Schmuky** [comment]
Left it running for awhile, no change and decided to exit.
I got this for 5 sec (surprised i managed to get a picture) as the game was exiting
![Untitled3](https://user-images.githubusercontent.com/63563915/79082143-36399d80-7d2c-11ea-82dd-ce4651b3eb5b.png)

No idea what it is, but it seems related?

**Comment by elvisp123** [comment]
Having the exact same issue any luck? I have over 10 hours on this campaign building I don'
![error](https://user-images.githubusercontent.com/63557698/79090122-9de4ee00-7d16-11ea-8738-f4b611f605d1.PNG)
t want to lose it :(

**Comment by Schmuky** [comment]
nothing yet, same problem for me

**Comment by lebernstein** [comment]
Yes. I have the same issue as well.

**Comment by Schmuky** [comment]
Yep. I also managed to corrupt any new campaign as well. If i exit to main menu, i cant re-enter it.

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

**Comment by LuPro** [comment]
As it has been 5 days, I'm going to assume this issue is resolved (as everyone who had this issue and who answered back had it resolved). If you still experience this, please comment so I can reopen the issue.
