### ISSUE TITLE
Deleting Current Board

### ISSUE THREAD

**Issue by chibibiscuit** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#285]
You are able to delete the board you are currently on. Upon deleting it, if it was the only board in the campaign, it hides the controls that you would use to create a new board, preventing any boards from being created.

**Comment by LuPro** [comment]
Have you tried pressing Space bar to reopen the menu? the top left menu should be seen again, as seen in #5 (or check #19 for an issue closer to yours). If that works for you, I'd mark this as closed as it would be a duplicate, if not, interesting stuff and we got ourselves a new bug!

**Comment by chibibiscuit** [comment]
You are absolutely right, I was able to create a new one by pressing space
to open the menu. At first, I has only thought I could change boards or add
new ones from the dropdown menu in the upper-right corner, this should be
closed!
