### ISSUE TITLE
Can't open a board "Waiting for adventure to begin"

### ISSUE THREAD

**Issue by HalTorns** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#293]
**Describe the bug**
Map not especially very big or with a lot of elements I think, a mood block, sevral hiden zone (5/6 I think), some playable token, some wall clipped between us, all over board can be opened in the campaign but not this board.

I try to restart several time, to reset by default light effect but nothing.

**To Reproduce**
I'm sorry I don't understand what I do for break the board

**Screenshots/Videos/Twitch Clips**
![2020-04-13 01_59_12-TaleSpire](https://user-images.githubusercontent.com/63566365/79083146-93355380-7d2c-11ea-8ffd-c65f9b5d55ea.png)
![2020-04-13 01_59_25-TaleSpire](https://user-images.githubusercontent.com/63566365/79083151-99c3cb00-7d2c-11ea-8e36-27195ad57e8e.png)
![2020-04-13 02_08_02-TaleSpire](https://user-images.githubusercontent.com/63566365/79083155-9d575200-7d2c-11ea-9a75-b1970b4b94e5.png)

I'm sad to lose some hours of work, but I still love you and your great work <3 

Kiss

**Comment by Schmuky** [comment]
had the same issue ( bug#283), lost some progress as well, but i recommend you make notepad documents with your builds so you have them no matter what happens to your board (just a pro tip)

**Comment by Jacknification** [comment]
It happened to me also.
![Bug1](https://user-images.githubusercontent.com/63573239/79091326-1cf51900-7d4d-11ea-9acc-8da34b85e7f5.png)
![bug2](https://user-images.githubusercontent.com/63573239/79091335-21213680-7d4d-11ea-9086-2674075b0a67.png)

**Comment by Khaladin68** [comment]
The same #293 I hope we can recover this maps after the resolving ... 4 Maps blocked because of this bug.

Good luck Bouncyrock ! I believe in you and your project !

**Comment by Velgor55** [comment]
Same problem for me. It was my latest, most ambitious design build. A small board, but a cool layout. Hopefully it's not gone, but I can rebuild it.

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this?

**Comment by Khaladin68** [comment]
You are the best it's ok !!!

**Comment by Velgor55** [comment]
I updated and tested the new build. The problem did not occur! In fact, one board that failed to load due to hard assert failure, now loads again! THANK YOU!



-Tom



---- On Thu, 16 Apr 2020 06:13:55 -0700 LuPro <notifications@github.com> wrote ----




The newest update has fixed many sources of this problem, can you check if you still get this?

**Comment by LuPro** [comment]
I'm going to assume this is also fixed for the original poster, as there haven't been any reports of this issue *not* being resolved by the game update. If this is not the case, please comment so I can reopen the issue.
