### ISSUE TITLE
1. Place a tile

### ISSUE THREAD

**Issue by martinlegolink** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#3]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. Punch an ogre '...'
2. Set a chair on fire '....'
3. Tried to open a door '....'
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Sebdevar** [comment]
Issue can be closed, just a copy of the template
