### ISSUE TITLE
Create multiple walls with dragging bug

### ISSUE THREAD

**Issue by Knives2021** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#302]
**Describe the bug**
When you click and drag walls on top of other walls, it will move you selection off of the wall by one space even though on the grid it is on top before you release the drag.

**To Reproduce**
1. Build a long line of wall
2. On top of those walls build more walls by click dragging
3.Walls will be off by one space

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Possible to be a duplicate of #17, but hard to tell without screenshots, could you confirm that please?

**Comment by Knives2021** [comment]
Yes looks like it's the same bug I'll close the ticket!
