### ISSUE TITLE
I can't find my house

### ISSUE THREAD

**Issue by Clayton-Pajot** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#311]
It seems the artboard don't remember where you were last building, and I guess I must not have started in the center of the map, because when I open the art board I was working on, all I see is the blank ground. I try looking around for it, but I can't find it, and I can't zoom out enough to see a large portion of the map. So I keep relaunching the board, and try a new direction, but I still haven't found it again. I did find it once, but I forgot which direction it was. 
It would be nice if there was a way to zoom out quite a bit more, or at least get closer to the ground so I could see more of the horizon

**Comment by LuPro** [comment]
the boards should remember your last position, but you can recenter your view to the center of the board by pressing "F2". Apart from that, that's not really a bug, but a feature request for that kind of things. I'm going to close this issue and you can raise this in the feature-request channel in the discord (the official place for requesting features). Though the devs are already planning on implementing "bookmarks" to store locations on the board to quick jump to, so something like that will come sooner or later anyways
