### ISSUE TITLE
Props can't be place where i want

### ISSUE THREAD

**Issue by KingGork** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#312]
Describe the bug 
I can't land props where i want, i want to put a cheese or a pie on a table, it just land on the border of the square that has been showned to me

To Reproduce Steps to reproduce the behavior:
1. Select any prop that you want to land on the prop "Round Table With Chair 01"
2. Add it, and it will land on the center of the square grid

**Comment by LuPro** [comment]
This is not a bug, it is a limitation of the current system of placement. The devs are already planning on making a more advanced system to place props (finer attachment grid, more rotation angles), but it's not quite finished yet. Until then you will have to live with the suboptimal placement of the props unfortunately.
