### ISSUE TITLE
World unable to load

### ISSUE THREAD

**Issue by Polansia** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#313]
After creating a reasonably sized world, it no longer wants to load and is stuck on "waiting for adventure to start". This was in a multiplayer session. We didn't do anything special to make it happen, we just closed out of the game after we were satisfied with our progress and when we tried to load back in we couldn't. 

The console shows this error message with 999+ updates so it is most likely the root of the problem
![Capture](https://user-images.githubusercontent.com/62407108/79140793-880f1180-7d86-11ea-8bdc-dadc730388ca.PNG)

I also have a screenshot of the logs here 
![image](https://user-images.githubusercontent.com/62407108/79140882-af65de80-7d86-11ea-979e-85afc624fbf8.png)

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this?

**Comment by Polansia** [comment]
The newest update fixed my issue, Thank you guys for your continued hard work!
