### ISSUE TITLE
Menu interfaces don't appear

### ISSUE THREAD

**Issue by Tuffghost89** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#316]
**Describe the bug**
50% of the time I open a game, the build menu won't open. Pressing space makes the logos in the top left appear, but nothing else. Pressing B does nothing. I have to log out and back in again and about half the time it works.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
That sounds to me a lot like you aren't loading into any board half the time for some reason - you have to bring up the menu in the top left and manually join the board again, check out #5 or #19 for some more detail on that. What is weird though is that you are not loading into any board only *sometimes*

Could you confirm if my suspicions are correct?

**Comment by Tuffghost89** [comment]
Yes it was my fault -_- I apologize
