### ISSUE TITLE
Control C Copy causes board crash and kick to second board.

### ISSUE THREAD

**Issue by LukePAlexander** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#32]
**Describe the bug**
When I use the copy functionality after using the volume tool I am kicked with an error message to another board. "Board Update Failed: Unhandled Exception. Left Board. Error ID to report to the devs: 4928491B-22F6-405A-8CB9-958C48F4FBDF

**To Reproduce**
1. Select multiple ground floor tiles using the volume tool (2 part left clicking).
2. Control C

**Screenshots/Videos/Twitch Clips**
![Screenshot (14)](https://user-images.githubusercontent.com/16996079/79022699-2e1f0980-7b44-11ea-9384-f77fa8baaeb4.png)
![Screenshot (15)](https://user-images.githubusercontent.com/16996079/79022705-324b2700-7b44-11ea-9627-b1425dde0092.png)
![Screenshot (16)](https://user-images.githubusercontent.com/16996079/79022696-2b241900-7b44-11ea-84a0-ee9a2a9519f4.png)

**Additional context**
You guys are incredible I hope Ree is getting better and doesn't work too hard!

**Comment by PhoenixSunrise** [comment]
Can confirm, though I don't have the exact error code to compare if it's identical.

**Comment by LuPro** [comment]
Duplicate to #8
