### ISSUE TITLE
Not able to interact after deleting all boards

### ISSUE THREAD

**Issue by Daymaster1** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#324]
**Describe the bug**
After creating, a secondary board, and deleting both the game goes to what looks like a new board, but with no build option. The only menu available is the tab menu, and pressing b for the build menu doesn't open the menu. Even closing the campaign and opening it again doesn't fix the problem.
![Annotation 2020-04-13 174232](https://user-images.githubusercontent.com/55112839/79171201-adb01100-7dae-11ea-97c7-67c17a397bbe.png)
![Annotation 2020-04-13 174233](https://user-images.githubusercontent.com/55112839/79171203-aee13e00-7dae-11ea-93ec-89bfe63ba453.png)
![Annotation 2020-04-13 174234](https://user-images.githubusercontent.com/55112839/79171208-b274c500-7dae-11ea-9ad7-c930f47b80fd.png)
![Annotation 2020-04-13 174235](https://user-images.githubusercontent.com/55112839/79171211-b43e8880-7dae-11ea-8cbc-fe767daaa81b.png)
![Annotation 2020-04-13 174236](https://user-images.githubusercontent.com/55112839/79171213-b56fb580-7dae-11ea-8070-2b7f0da3c7c4.png)

**To Reproduce**
1. Delete all boards on a campaign

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Check #5, #19 or #20 for more info - you should just be able to create a new board again and be back on track
