### ISSUE TITLE
saved notepad map lines don't want to load correctly into the next phase of pasting

### ISSUE THREAD

**Issue by GregoryFrazier** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#326]
<img width="960" alt="before pasting" src="https://user-images.githubusercontent.com/63620977/79173133-ae53a200-7dc4-11ea-919e-ae9b8601906f.png">
<img width="960" alt="After pasting" src="https://user-images.githubusercontent.com/63620977/79173146-b57ab000-7dc4-11ea-98d5-9d30746ba213.png">

**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
My saved notepad map lines don't want to load correctly into the next phase of pasting when I try to reload the map from the saved .txt file.
**To Reproduce**
1. Punch an ogre '...'
2. Set a chair on fire '....'
3. Tried to open a door '....'
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Just to confirm: You have a slab saved in a notepad text file, you're copying it and then trying to paste into TaleSpire and something goes wrong there? Could you elaborate on what error exactly is coming up please?
