### ISSUE TITLE
placing walls on edge of building offsets them 

### ISSUE THREAD

**Issue by Rebullet** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#33]
**Describe the bug**
placing walls as a group offsets them away from the wall edge

**To Reproduce**
choose tavern walls (only one i have used so far).
bring them to edge of wall. 
create a group along the wall edge.

**Screenshots/Videos/Twitch Clips**
https://vimeo.com/406341991

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Duplicate of #17
