### ISSUE TITLE
Deleting maps makes you unable to create a new map if you have none.

### ISSUE THREAD

**Issue by PouchMouth** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#330]
**Describe the bug**
The game produced the map i was working on and then when i ended up deleting my progress,l i attempted to create a new map but was left with no option on the screen to do so.

**To Reproduce**
1. Delete map all maps
2. failed to give option to create new one

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63628489/79184811-36e13b00-7de3-11ea-838f-c0197acd042b.png)

**Additional context**
A great program, with just something i happen to catch. keep up the great work!!!

**Comment by LuPro** [comment]
Could you check if #5 or #19 (and the fixes/explanation shown there) work for you? Alternatively it might be an error similar to #328
