### ISSUE TITLE
Corrupted Board(s)

### ISSUE THREAD

**Issue by AdventR** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#331]
When loading a board, the "Waiting for the adventure to begin" banner never goes away. There is a shadow from some of the assets, but they never fully load and none of the right-side menus or build mode become available.

There was a time when the assets did load while this was happening once zoomed in, but there were all stacked on each other, clipping, and in very wrong spots. I tried closing and reconnecting, no luck. I loaded a different board when logging in an another time then duplicating the corrupted one, but the copy has the same issue.

![image](https://user-images.githubusercontent.com/3279199/79189220-cb996800-7de6-11ea-9490-c73a0feb5580.png)

![image](https://user-images.githubusercontent.com/3279199/79189265-e835a000-7de6-11ea-87a0-2323c268886d.png)

**Comment by DasAmigo** [comment]
I have this exact problem right now. 6 hours of board work gone ;( Here is hte log from when I try to load and it craps out.
![2020-04-14 20_04_26-Window](https://user-images.githubusercontent.com/6361131/79285385-6f3c5400-7e8b-11ea-8961-eda068c05da4.png)

**Comment by DasAmigo** [comment]
Here is all I get
![2020-04-14 20_04_26-Window](https://user-images.githubusercontent.com/6361131/79285439-92670380-7e8b-11ea-93b2-1c677b629f9f.png)

**Comment by DasAmigo** [comment]
new interesting tid bit: I have 999+ of this hard assert failure bug in the log. if I clear the log I get 999+ more of the error in about 5 seconds.

**Comment by DasAmigo** [comment]
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4478385/Player.log)
Attached Player.log

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this?

**Comment by DasAmigo** [comment]
I just checked and I was able to get back into my board that I lost. Great work! Problem solved.

**Comment by AdventR** [comment]
You know, I feel awful for letting frustration get the best of me, but I had deleted my boards and recreated them. I'm glad to hear that it seems that DasAmigo could help confirm that they got their's back.

**Comment by LuPro** [comment]
That's a shame, but I guess we can't do anything about that. Glad to hear it fixed it for others though :)
