### ISSUE TITLE
Board not loading

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#336]
After switching between two of my campaigns repeatedly to transfer assets my primary campaign would no longer load. It would display the "Waiting for the adventure to begin" message. Eventually I noticed that I could make a selection box, use the flashlight, and toggle certain overlays such as help (f1) and DM (tab). When I selected an area some of the assets would load in but I could not interact with them in any way. The shadows for every asset seemed to be loaded.

After some time I exited the campaign and tried to load it again. This time it would not let me select any areas and most of the shadows were missing. I could still use the flashlight, DM overlay, etc as before. Entering another campaign seems to work normally.

![Loading World](https://user-images.githubusercontent.com/63642460/79213608-18913480-7e0f-11ea-9889-df70df0d0694.png)

**Comment by MallowOni** [comment]
Oh, I also alt-tabbed out of Talespire when the board was loading. I believe I switched to Firefox.

**Comment by LuPro** [comment]
The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

**Comment by MallowOni** [comment]
> 
> 
> The newest update has fixed many sources of this problem, can you check if you still get this? If so, please provide console output for more details (triple click in top left corner)

It took about a minute longer to load than normal but yes that did allow me to access that campaign again. Thank you!

**Comment by lebernstein** [comment]
Looks like I was able to get to all my "broken" boards now.
