### ISSUE TITLE
Stuck on main screen (after update on 14/4/20)

### ISSUE THREAD

**Issue by Dbarn101** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#338]
**Describe the bug**
Forever loading on main screen. Only started happening after latest update - was able to play pretty much bug free (more or less) up until today. 

**To Reproduce**
Simply logging in seems to do it. 

**Screenshots/Videos/Twitch Clips**
![ImSureImNotTheFirstOneToShowYouThisButJustInCase](https://user-images.githubusercontent.com/63656675/79240081-38eddd00-7e69-11ea-9348-3bf7f9d9def8.png)

**Additional context**
Isn't it weird how you never see cranes being assembled or disassembled. They just turn up and disappear overnight.

**Comment by LuPro** [comment]
Just going out on a limb and asking if you're on a different network (laptop maybe?) now or if you are using a VPN. I'm going to assume no, since it used to work for you, but wanna be sure :)

**Comment by Dbarn101** [comment]
I've been meaning to look into a VPN but alas, haven't gotten round to it yet. And nah, only got TS on my main PC. I've seen these suggestions floating around and fixing issues though, so was worth a shot :) I appreciate it.

**Comment by Dbarn101** [comment]
![Console](https://user-images.githubusercontent.com/63656675/79246171-01832e80-7e71-11ea-98b0-a3ea297dfe24.png)
Thought I might add a screenshot of the console triple click thingo in case that reveals some hidden info.

**Comment by LuPro** [comment]
Looks like a thing that has been creeping up here and there, the devs have the idea that it might be an external library they're using that fails on region switching/selecting - I guess that's nothing you can fix (though maybe actually using a VPN to get to another region *might* work) and they'll have to work on the code side

**Comment by Dbarn101** [comment]
Gave it another whirl this morning and for some reason, it's working now. Maybe it was something on my end, who knows.
