### ISSUE TITLE
Host leaving the game doesn't notify others/causes crash

### ISSUE THREAD

**Issue by Inshal240** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#34]
I hosted a campaign for another player and left after some messing around. The other player (as a GM role) could still edit things but when I reconnected, he got kicked out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Host a campaign
2. Join the campaign as a client
3. Host exits to main menu
4. Host rejoins
5. The client gets kicked out

I don't know the server architecture behind ToS. If I am hosting a server for others to join and it's not hosted on a server elsewhere, then a notification to inform players when I leave the game and have them gracefully return to the main menu would be nice. Else, there is an issue regarding the Owner leaving the game.

**Comment by LuPro** [comment]
As TaleSpire is completely server side right now it is possible (and intended) for you to be able to leave while others are still connected and working, but the person being online shouldn't be kicked when you rejoin. What kind of message (if any) was shown to the player who was kicked when you rejoined?

**Comment by Inshal240** [comment]
As I was unable to replicate this issue and it was probably a mix-up, I will close this issue for the Talespire team. Ya'll are doing great, keep it up! :D
