### ISSUE TITLE
Some initiative portraits white "unknown" after swapping boards.

### ISSUE THREAD

**Issue by dpwinger** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#347]
![Capture](https://user-images.githubusercontent.com/49322095/79275565-47cd9300-7e5b-11ea-984e-7f496f6ea76a.PNG)

I changed boards and returned to the one with initiative running. Several initiative portraits were white with unknown labels. in initiative settings the characters are all there. both unique and non-unique monsters included missing. 

*Several miniatures actually disappeared from the board when I tried to pick them up. not sure

*Previous to this issue I had lost my cursor after trying to move an enemy while it was not their initiative. The UI was  hung for a while not even allowing esc to menu to appear. It eventually returned but I am uncertain as to the details of the prior issue.

**Comment by LuPro** [comment]
Similar behavior to #83 and #152, likely to be due to the same bug.

**Comment by cbaggers** [comment]
This should have been fixed in the patch from last Friday. If you have time please try it out again :)

**Comment by LuPro** [comment]
I'm going to assume this issue has been fixed for you, as it has been quite a few days now. If it still persists, please comment so the issue can be reopened.
