### ISSUE TITLE
Can't move selected volumes

### ISSUE THREAD

**Issue by kirchner-trevor** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#353]
**Describe the bug**
I created a volume selecting multiple things, and then I expected to be able to click on the volume and interact with it like I would interact with any tile. Move it, rotate it, etc. Those controls are not available though so I have to copy / delete / paste it instead.

**To Reproduce**
1. Create multiple tiles
2. Create a volume encompassing them
3. Hold shift and click on the volume to try and "pick it up" like you would for a tile

**Comment by LuPro** [comment]
Not really a bug, this is how the game behaves right now - there is definitely something to be said for adapting that, though that would fit more as a feature request. The official place to raise those is the [Discord](https://discord.gg/7cEMmh) in the feature-request channel :)

**Comment by kirchner-trevor** [comment]
Should #295 also be a feature request then? I didn't see that when submitting this.

**Comment by LuPro** [comment]
It kinda goes in the direction, but it's not as clear cut. IMO the other was fine to leave here
