### ISSUE TITLE
Copy/Paste does not account for the original full-tile boundaries for alignment purposes

### ISSUE THREAD

**Issue by laposheureux** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#360]
**Describe the bug**
I am currently building 3 ships from Waterdeep and they share many traits in common, so I build one level, copy and paste, make adjustments, etc. This was fine for the base level, but I ran into a problem where I was unable to align the second level with equivalently positioned base levels after copy paste without adding a half-tile-width wall to the back end of the piece I was trying to copy. Talespire does not appear to take into account that a pairing of half filled tiles on any one axis when copying/pasting causes alignment to shift.

**To Reproduce**
I've created a minimal reproduction case...
1. Create two 3x3 floors next to each other
2. Build walls around one with two half-filled squares on either end of one axis
3. Copy the walls from one floor to another
4. Try to align them.

**Screenshots/Videos/Twitch Clips**
1, 2:
![20200415013016_1](https://user-images.githubusercontent.com/13631960/79316623-6bbfc180-7eb9-11ea-9765-6e11e8deade7.jpg)
3:
![20200415013022_1](https://user-images.githubusercontent.com/13631960/79316649-7712ed00-7eb9-11ea-8ab4-7a6ede4570d3.jpg)
4:
![20200415013031_1](https://user-images.githubusercontent.com/13631960/79316680-81cd8200-7eb9-11ea-9b9f-2688d455647e.jpg)
![20200415013033_1](https://user-images.githubusercontent.com/13631960/79316683-82661880-7eb9-11ea-81da-8161f1f983aa.jpg)
![20200415013111_1](https://user-images.githubusercontent.com/13631960/79316684-82feaf00-7eb9-11ea-848e-c2e3555692d5.jpg)
![20200415013117_1](https://user-images.githubusercontent.com/13631960/79316685-82feaf00-7eb9-11ea-9e28-6f9c835ba40a.jpg)

**Additional context**
Looks pretty similar to https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/106 but I couldn't get the video there to confirm.

**Comment by LuPro** [comment]
This should have been fixed in the latest update, could you check if this still occurs for you?

**Comment by laposheureux** [comment]
I can confirm I can no longer reproduce this with either my ships or my reduced test case. If I find another scenario where it occurs, I'll reopen.
