### ISSUE TITLE
Incorrect d100 rolls

### ISSUE THREAD

**Issue by Cabbashini** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#37]
**Describe the bug**
Not sure whether or not to describe it as a bug per se, but it's possible to roll higher than 100 on a d100 roll (d10 + percentile)

I rolled 00 on the percentile and 2 on the d10, which Talespire read as 102. Obviously different systems and different dms have different ways of reading d100s but this should at the very least not be possible.

Personally, I roll percentile for the tens place and the d10 gets added to that- ie 90 percentile and 0 on the d10 equals 100, while 00 percentile and 2 d10 (as in the actual scenario) would be 2.

**To Reproduce**
Roll a percentile die and a d10 together, with the percentile rolling 00

**Additional context**
An option within the dice menu to read percentiles differently could be useful- toggling between reading 00 as either 0 or otherwise.

**Comment by Chorcon** [comment]
I noticed this too, and took the liberty of reproducing it and taking a screen shot.
The way I read the d100, this should be a total of 9 and a total of 100.

![109](https://user-images.githubusercontent.com/10231515/79208931-07621b00-7e43-11ea-89d8-a26ad4a04af1.jpg)
![110](https://user-images.githubusercontent.com/10231515/79208934-07fab180-7e43-11ea-8479-5926695a1a48.jpg)

As others have stated in separate posts, this experiment made me agree that the result of the dice should be visible a bit longer. Watching the dice roll is so enchanting, I nearly missed my window of hitting F12 for a screenshot! :)

**Comment by cbaggers** [comment]
Thanks for the report. I tried to fix this before release but must have messed something up. I think I have it this time. 
The probable fix will be in tomorrow's patch release

**Comment by cbaggers** [comment]
![d100 again](https://user-images.githubusercontent.com/1579326/79517798-8b88ee00-804f-11ea-9dd6-1c87886e6f88.gif)
