### ISSUE TITLE
Game stuck at "Waiting for the adventure to begin"

### ISSUE THREAD

**Issue by mediaflare** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#375]
I can't figure out how to describe how I 'triggered' this problem, since it's only happened once and is now locking me out of the game

I changed the elevation of a few tiles in a board, and my friend told me she couldn't get into the room. So I quit to the main menu, and now I can't load back in. I'm forever stuck with "Waiting for the adventure to begin"

**Comment by LuPro** [comment]
Can you please open the dev console (triple click in top left corner) and check the errors there. Does it say "HardAssertError" somewhere there? If so, it might be that a fix that's scheduled to be released tomorrow could fix that.

**Comment by LuPro** [comment]
This fix is released now, can you please check if the error persists? If it does, console output would be very appreciated.

**Comment by mediaflare** [comment]
I confirm that the issue was fixed with the patch. Thank you!
