### ISSUE TITLE
Loading/Saving Bugs

### ISSUE THREAD

**Issue by Mikel-kun** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#383]
**The game fails to load in or save correctly.** 
![720620_screenshots_20200415225136_1](https://user-images.githubusercontent.com/34955611/79409369-a4f84000-7f52-11ea-94c9-11804d69548f.jpg)

My friend and I were tag-team building a village and mountainside.
When i dragged my cursor and pressed Delete on my keyboard, it deleted nearly half of our build while i was only selecting a small segment of two rows.
When i hit Ctrl + Z to undo it, it worked on my end but not hers.
So, i hit the small arrow next to the board name in the upper right corner to upload our progress and leaved. When I came back in, I was greeted with an endless loading screen.
On a map before this, I did the same thing: clicked the arrow, exited, and came back into it this morning; but except this time, it loaded in but all of my progress was gone.

**Comment by LuPro** [comment]
could you check in the developer console (triple click top left corner) what kind of errors it shows? also, the part with deleting too much sounds similar to #51

**Comment by LuPro** [comment]
Many sources of the "waiting for adventure" bug should be fixed in the newest update btw, can you check if that is the case for you as well? If you still get this, the console error logs would be even more valuable

**Comment by Mikel-kun** [comment]
Did they patch it because it's loading now that I'm looking back at it
