### ISSUE TITLE
Selecting player mode makes all miniatures vanish.

### ISSUE THREAD

**Issue by SqueeziestBee** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#393]
**Describe the bug**
Selecting player mode makes all miniatures vanish.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spend too much time building
2. Place hero and NPCs
3. Assign hero to myself 
4. Switch to player mode and watch everyone disappear

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

![20200416184934_1](https://user-images.githubusercontent.com/47105660/79489612-71311f00-8013-11ea-935c-087a43bf68c5.jpg)

![20200416184920_1](https://user-images.githubusercontent.com/47105660/79489607-6ffff200-8013-11ea-9320-7daa76bee45b.jpg)
![20200416184922_1](https://user-images.githubusercontent.com/47105660/79489608-71311f00-8013-11ea-9028-70b3949dc4d0.jpg)

**Additional context**
Only manage to reproduce this when I'm not trying to. But have done this at least twice now.

**Comment by cbaggers** [comment]
I've got a board where this is consistent. Digging into it now

**Comment by cbaggers** [comment]
Ah, found it. So what happened was that during loading creatures requested line of sight checks, but then an event fired that cleared the list of line of sight requests.

The reason it did that was we had a bug where, when switching board, we got lots of line of sight errors as it kept trying to do it's job even though the board had been unloaded.

I think we can just clear this list on leaving a board and we should get the right behaviour
