### ISSUE TITLE
Error on copy

### ISSUE THREAD

**Issue by cbaggers** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#395]
> reported for community member

**Describe the bug**
When copying some selected tiles an error occurred which ejected me from the board

**To Reproduce**
1. Select tiles
2. Copy

**Screenshots/Videos/Twitch Clips**
https://youtu.be/O0Vfguqxzpg

**Additional context**
No ideas currently

**Comment by LuPro** [comment]
smh, baggers just making dupes ( #8 )

**Comment by cbaggers** [comment]
hehe good catch. yeah I should probably merge them
