### ISSUE TITLE
Mass Select and delete functionality

### ISSUE THREAD

**Issue by Vormancer** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#398]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
added in a large section of blocks and later discovered they're not needed, now trying to highlight and hold shift and right click to delete but it seems to just unselect it not sure if this is by design or if an error
**To Reproduce**
See above

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
if you highlight with the volume tool you need to press the "delete" key to delete (or press ctrl + x to cut, that also allows you to paste the tiles back in in another position again.) If you're unsure on the controls I recommend you check out [this tutorial](https://www.youtube.com/playlist?list=PLzhSvLOshFOhCC-7uI8uR8fL3ZsNitY8Y), it should cover pretty much everything :)
