### ISSUE TITLE
Crash to Desktop on placing tiles

### ISSUE THREAD

**Issue by martinlegolink** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#4]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. Place a tile
2. select new tile
3. click and drag new tile and place on top of first tile
4. crash to desktop

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Sebdevar** [comment]
@martinlegolink Please use the template to describe the issue rather than the issue title :).

As for the crash, I personally am unable to reproduce it on my end using the steps mentioned

**Comment by LuPro** [comment]
Couldn't replicate - which specific tiles did you use? Might not work with every tile

**Comment by LuPro** [comment]
Just realized that this might be related to #12 (and related issues)

**Comment by LuPro** [comment]
If it is related to the issue mentioned above, then there should be a fix for this in the latest update, coould you check if it works for you now?

**Comment by LuPro** [comment]
I'm going to assume that this is fixed now, I will close this now, if the issue still persists please comment here and I will reopen it
