### ISSUE TITLE
Infinite Hourglass

### ISSUE THREAD

**Issue by LupinKira** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#401]
**Describe the bug**
Still getting the infinite hourglass loading once I click begin and the campaign list pulls up. Unable to make a campaign or see any to join. Tried computer reboot, router reboot, uninstalling and reinstalling Talespire, and changing my DNS manually to 1.1.1.1 and 8.8.8.8 with no luck. 

**To Reproduce**
1. Open the game
2. Click "Begin"

**Screenshots/Videos/Twitch Clips**

![20200416192138_1](https://user-images.githubusercontent.com/63829367/79525534-eef72980-8017-11ea-84ab-9ca4e8239bac.jpg)

![20200416191331_1](https://user-images.githubusercontent.com/63829367/79525548-f74f6480-8017-11ea-9c39-9e0520e6f38e.jpg)

![Screenshot (132)](https://user-images.githubusercontent.com/63829367/79525592-1948e700-8018-11ea-9d18-2099802ab4d9.png)

**Comment by LuPro** [comment]
Can you please check this dev log out: https://bouncyrock.com/news/articles/talespire-dev-log-208 - the devs have just investigated in some of the connection issues and this seems to be a promising source of the error. they plan on releasing a fix for this soon, but until then you can try to disable the proxy in windows settings to see if this is indeed the problem you are facing (if not, that would be super interesting)

**Comment by LuPro** [comment]
As there hasn't been a follow up in all this time, I presume this has been fixed. if not, please comment and I'll reopen
