### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by Veska75** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#413]
**Describe the bug**
Graphical glitch more intense near sides of screen

**To Reproduce**
1. Happens everytime I fire up the Talespire

**Screenshots/Videos/Twitch Clips**
![Lighting glitch](https://user-images.githubusercontent.com/63480403/79600967-0d136700-80b6-11ea-9ac8-1321686b2e99.jpg)

**Additional context**
GAHHHHHHHHHHHH! IT SUPER BOTHERSOME TO ME! Please let me know if this is planned on being addressed at some point. Thanks for all the hard work so far. Keep it up!

**Comment by LuPro** [comment]
Check #93 for an explanation - tldr: not a bug, but intended feature, though in future there will be an option in the settings to turn it off/change intensity

**Comment by Veska75** [comment]
Thanks for the reply. I apologize not looking at the comments prior.
 Thank you for your patience.
