### ISSUE TITLE
Tavern Wall Corners Do Not Align

### ISSUE THREAD

**Issue by abonnell** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#416]
**Describe the bug**
Tavern Wall corners do not align

**To Reproduce**
Place corners

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

![image](https://user-images.githubusercontent.com/62351448/79613955-5fec1f00-80b4-11ea-9168-005569ec3473.png)

**Comment by LuPro** [comment]
Duplicate of #21
