### ISSUE TITLE
Wood Fences after 4/17 patch

### ISSUE THREAD

**Issue by qu181** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#417]
**Describe the bug**
After the 4/17 patch the fences got a huge improvement but they still don't quite line up if rotated in a different orientations.

**To Reproduce**
1. Place fence or fence corner
2. rotate fence twice or corner three times.
3. Place tile where you would align it

**Screenshots/Videos/Twitch Clips**
![Talespire fence](https://user-images.githubusercontent.com/63611455/79626048-268ad200-80fb-11ea-8b2d-535fc2f6f17d.JPG)

**Additional context**
I want to say thank you for all the hard work. The improvements thus far have been amazing and this is really a nitpick and should be lower priority as builders can easily work with the fence in their current state. This is mostly an Issue when making a "Z" with the fence corners (see image) but if they get changed the straight fences would need to be fixed also. I just wanted to make sure someone pointed it out. Thank you.

**Comment by LuPro** [comment]
This should not be an issue anymore with the new prop system that released with the chimera update :)
