### ISSUE TITLE
click and drag bug for tile placement

### ISSUE THREAD

**Issue by shambalba** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#420]
Placing multiple tile (click and drag) crashes the game

**To Reproduce**
1. launch tailspire
2. Set a chair on fire or create a new board.
3. enter build menu and select any tile.
4. click and drag to set multiple of them.
5. talespire crashes.

**Screenshots/Videos/Twitch Clips**
no clip but here is the error report.

TaleSpire.exe 
   2019.3.0.40491 
   5debc82c 
   lib_burst_generated.dll 
   0.0.0.0 
   5e99e4e7 
   c000001d 
   00000000000016d6 
   2e58 
   01d61542eecae552 
   F:\Program Files (x86)\Steam\steamapps\common\TaleSpire\TaleSpire.exe 
   F:\Program Files (x86)\Steam\steamapps\common\TaleSpire\TaleSpire_Data\Plugins\lib_burst_generated.dll 
   50674c04-f2d4-440d-9282-8bf746b7e6f0

**Additional context**
friend i got the program for is having this problem

**Comment by shambalba** [comment]
other simillar bug, sorry found after posting
Placing multiple objects with mouse drag crashes the game and corrupts the campaign file #87
 Open
**crash** TaleSpire - Unity 2019.3.0f3_6c9e2bfd6f81 #114
 Open
Constant crash issue -- most actions in build mode cause instant CTD #265

**Comment by LuPro** [comment]
Based on the error I presume you have an old AMD Phenom processor?

**Comment by shambalba** [comment]
ill have to ask my buddy what kind of processor he has... aparently posting on here is too hard for him.

**Comment by LuPro** [comment]
The latest update has a likely fix for this bug (if it really is the same as the issues mentioned above). Could you please check if it works now?

**Comment by shambalba** [comment]
it seems to have fixed it yes. thank you!
