### ISSUE TITLE
ZQSD controls and tile placement

### ISSUE THREAD

**Issue by ponchoa** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#426]
Unfortunately, the game detects that I have an AZERTY keyboard, and remaps the camera controls accordingly to the ZQSD instead of the WASD keys, but it still uses Z and C for quickly switching tiles to place.

**To Reproduce** 
Plug in an AZERTY keyboard and select a tile to place. Press Z to switch between tabs, and the camera will pan up.

**Comment by LuPro** [comment]
There's key rebinding now in the game, so this should fix the issues where keybindings aren't correctly detected for other keyboard layouts
