### ISSUE TITLE
Clipping Texture

### ISSUE THREAD

**Issue by Mikel-kun** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#433]
**Describe the bug**
There's a clipping texture in a wall segment.

**To Reproduce**
1. Open the Tavern Tab under Building Assets
2. Place a Tavern No Floor ( 1x1 A ) corner on the board
![720620_screenshots_20200419015957_1](https://user-images.githubusercontent.com/34955611/79680931-06761400-81ca-11ea-86a2-81d8cc278de6.jpg)

**Comment by PropForge** [comment]
I believe this is the same issue as reported in https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/242

**Comment by Mikel-kun** [comment]
That it was, sorry about that!
