### ISSUE TITLE
Each time I create a new board, it becomes my default board

### ISSUE THREAD

**Issue by laposheureux** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#442]
**Describe the bug**
For a while I had no default board, and after about 10 different ones I set one as the default. Now each time I've created another board in that campaign, the default board switches to the new one.

**To Reproduce**
1. Set default board
2. Create new board
3. Default board switches to new board
4. ???

**Screenshots/Videos/Twitch Clips**
Note that Unknown Realm 1 became the default.
![20200419124843_1](https://user-images.githubusercontent.com/13631960/79698218-5d1c3600-823c-11ea-8592-fc51b1daa428.jpg)

**Additional context**
🥇

**Comment by cbaggers** [comment]
I'm seeing this too (which is a relief of a sort). I'll look into this now

**Comment by cbaggers** [comment]
Turned out to be a very stupid mistake on my part. Luckily that means it an easy fix.

This will be in the next patch

**Comment by laposheureux** [comment]
Hooray thanks :)

**Comment by LuPro** [comment]
Patch should be out now, could you check if it is fixed for you?

**Comment by laposheureux** [comment]
Can confirm this does not happen to me anymore when creating new boards.
