### ISSUE TITLE
Initiative order seems to randomize on mini removal

### ISSUE THREAD

**Issue by TheWhiteNinja91** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#445]
We recently ran a game across multiple boards, with one GM two players for talespire yet controlling multiple minis for others playing via screen share.
When a PC who was "on their turn" killed an enemy the tracker moved to whatever was after the mini which was removed, the GM then manually moved it back, this happened throughout that encounter, it was reproduced across different encounters and boards with the same result.
The two player accounts both had control over 6 minis, though this seemed to have no impact.
Unfortunately no clips but the whole session was streamed to twitch, the first combat can be seen at the 35 minute mark : http://www.twitch.tv/evenstargaming/v/595712256?sr=a&t=9s

**Comment by USMCM1A1** [comment]
I have the same issue on removing a "killed" mini.

**Comment by PanoramicPanda** [comment]
Thought this was resolved with Chimera. still an issue as of 4/12/2021

**Comment by LuPro** [comment]
Should be fixed by now, if not please comment so I can reopen
