### ISSUE TITLE
Killing a monster results in <unknown> monster in the turn order

### ISSUE THREAD

**Issue by tinman4243** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#453]
**Describe the bug**
Killing a monster that is in turn order results in a White square in the turn list at the top of the screen with the name listed as <unknown>

**To Reproduce**
1. Enter turn order.
2. Add a bunch of Monsters
3. kill a few

**Screenshots/Videos/Twitch Clips**
none

**Additional context**
If someone wears black everyday, no one cares.  If someone wears yellow every day, that's weird.

**Comment by LuPro** [comment]
Is this still the case for you? The devs have released a fix a few days ago (Friday if I recall correctly) which should have fixed this (or at least most occurrences).

**Comment by SqueeziestBee** [comment]
I didn't manage to make the -unknown- appear, but the turn list vanished entirely

https://drive.google.com/open?id=1vsvVQGWHgl1wBgJE-FRlOMJqvlV0E5w5

**Comment by tinman4243** [comment]
Reported the issue before playing the game on Monday.  Found that the <unknown> issue was fixed, but there’s still an issue with the turn order going wonky when a monster is killed. 

Paul Lewellyn

**Comment by LuPro** [comment]
Going to close this, as the issue with the weird order on monster kill is already reported in issue #445
