### ISSUE TITLE
Texture overlap spazzing out

### ISSUE THREAD

**Issue by Resendez1** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#468]
**Describe the bug**
For the tavern no floor (1x1 A) corner piece the textures on top of the tiles have a weird visual conflict where when you rotate or move the screen they fight over which is supposed to be visible.

**Comment by SqueeziestBee** [comment]
https://drive.google.com/open?id=1gOlQ5_VBD3w1POMflC5cDRkQvJCyDZ0H

**Comment by PropForge** [comment]
Same as https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/242

**Comment by LuPro** [comment]
As PropForge mentioned, same as #242, so going to close this :)
