### ISSUE TITLE
Tavern No Floor 1x1A Graphical Glitch

### ISSUE THREAD

**Issue by rich18144** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#478]
**Describe the bug**
Looks like there is a graphical glitch with the top of the Tavern No Floor 1x1A block. Not sure if the block is glitching or if it's a bigger issue. I have not seen this with any other block.

**To Reproduce**
1. Place listed block
2. Move Camera around either using middle button click or with the right click.

**Screenshots/Videos/Twitch Clips**
Attached
[TaleSpire 2020-04-23 09-05-22.zip](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4521094/TaleSpire.2020-04-23.09-05-22.zip)

**Additional context**
Block at top of stack of Grass Block & Castle Floor 3.

**Comment by SqueeziestBee** [comment]
Issue had been listed #242
