### ISSUE TITLE
"Wooden Fence Corner" does not always line up

### ISSUE THREAD

**Issue by DrewBanyai** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#48]
**Describe the bug**
The "Wooden Fence Corner" does not line up in most configurations with either other instances of itself or with the basic Wooden Fence object. There needs to be a simple way to either shift the objects around manually, or they need to be redesigned to "snap" together correctly so as not to look ridiculous.

**To Reproduce**
1. Place a few pieces of Wooden Fence in different directions
2. Place a Wooden Fence Corner instance at the ends, in different configurations
4. Observe that they do not line up.

**Screenshots/Videos/Twitch Clips**
- https://imgur.com/a/xwrTPAf

**Additional context**
There was no crash, so I assume this is low priority, but there's a good chance this issue pertains to quite a few resources, so a way to make things "snap" together or be manually configurable would be great.

**Comment by USMCM1A1** [comment]
Same behavior.

**Comment by LuPro** [comment]
This also used to be the case in the alpha, many times this could be "fixed" by rotating the fences in a certain way (they're not properly centered) - though not every time and it still is annoying.

**Comment by LuPro** [comment]
This issue was (mostly) fixed since the last (17.04.) update. See #417 for the remaining issues with wooden fences
