### ISSUE TITLE
Placing props on tables has odd results along with other objects

### ISSUE THREAD

**Issue by EHCM81** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#487]
**Describe the bug**

I am not sure if this is a bug, but when I place props, such as plates, food, books, and paper on different tables, unless its the "Castle Table" will it place the prop objects half on, or completely off the table.

I also noticed that when placing lighting sources such as the "candleabra single," will it not always go flush with the wall and instead is one tile off making for clunky pathing for players at times.

**To Reproduce**
I would say, open a map and experiment with tables and props as well as walls with floors and other objects and props.

**Screenshots/Videos/Twitch Clips**

![Prop Bug 01](https://user-images.githubusercontent.com/64118405/80173419-a2c26100-85a4-11ea-8c62-9a62ccdbe7b4.jpg)
![Prop Bug 02](https://user-images.githubusercontent.com/64118405/80173421-a3f38e00-85a4-11ea-9847-4b4e2c525f2b.jpg)
![Prop Bug 03](https://user-images.githubusercontent.com/64118405/80173422-a3f38e00-85a4-11ea-981a-48106c88d2fd.jpg)
![Prop Bug 04](https://user-images.githubusercontent.com/64118405/80173424-a48c2480-85a4-11ea-825d-d50fefb7c3cc.jpg)
![Candleabra Bug 01](https://user-images.githubusercontent.com/64118405/80173715-8bd03e80-85a5-11ea-98a3-36f4a34124ec.jpg)
![Candleabra Bug 02](https://user-images.githubusercontent.com/64118405/80173722-8f63c580-85a5-11ea-950d-ebd675ed981b.jpg)

**Additional context**
Nothing at this time.

**Comment by SqueeziestBee** [comment]
Somewhat related to #372

**Comment by LuPro** [comment]
That is more a consequence of the current prop placement system, it will be revised to allow for more freedom in placement.

**Comment by LuPro** [comment]
I'll close this now as the new prop system has just been released three days ago with the chimera update - there's now free placement for props 🎉
