### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by LowkeyLatch** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#489]
**Describe the bug**
Game Crashing in multiple scenarios:
-joining own server
-when deleting a tile (on own server)
-when trying to join a friends server

**To Reproduce**
when deleting a tile:
1. join server i have created
2. place a couple tiles (each time around 6)
3. trying to delete a tile
4. game crashes

when joining a server:
1. start game
2. select either my own or friends server
3. load screen finishes
4. waiting for adventurers pops up
5. keyboard shortcuts/legend pops up
6. game crashes 

**Screenshots/Videos/Twitch Clips**
![talespire task manager](https://user-images.githubusercontent.com/64260379/80209457-79253a80-8675-11ea-8f7f-5915eb1b312c.jpg)

![crash screen](https://user-images.githubusercontent.com/64260379/80209669-ce614c00-8675-11ea-8b99-69cd5f14dd85.jpg)

**Additional context**
I apologize if this is actually something to do with my computer, its *new* (for me anyway) but here are my computer stats (i know its not high end stats or anything but i've been able to run a few other games like 7 days to die and deceit on medium settings without an issue):
CPU: AMD Phenom II x6 1090T
Memory: 8gb DDR3
GPU: NVIDIA GeForce GTX 960
In case its needed too, my operating system is run off a 120gb SSD whilst the game is saved to a secondary 2tb hdd

I tried to recreate the crash a few times whilst observing task manager to see if i could spot any issues there. The cpu % of the game seemed to spike before it suspended itself and crashed which i tried to get a screenshot of (as seen above).

I also verified the files on steam as I was told by a friend that could maybe solve the issue. Hope this helps, loving what I've seen of the beta so far and excited to get into it!

**Comment by LuPro** [comment]
Looking at the CPU it's most likely the same bug as #87

**Comment by LowkeyLatch** [comment]
Yeah after giving that bug a read it sounds the exact same, luckily nothing corrupted for me as of yet but I wont tempt that fate. I had a quick look at the beta issues before writing this up looking to see if it was known but obviously I didn't look hard enough :( sorry for wasting any time!

**Comment by cbaggers** [comment]
I've upgraded Unity's Burst package to a preview version that seems to give us SSE2 fallback support. This will be in the next patch, so hopefully we'll see some progress on this issue then.

**Comment by LuPro** [comment]
I'm going to assume the fix for this works, if it still persists please comment so I can reopen the issue
