### ISSUE TITLE
Session History

### ISSUE THREAD

**Issue by Perkuns** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#49]
**Describe the bug**
Session history is completely empty

**To Reproduce**
1. create something.
2. check session history.
3. find it empty.

**Screenshots/Videos/Twitch Clips**
https://imgur.com/UMgMmFI screenshot

**Comment by Lagicrus** [comment]
Session history doesn't track the creation of assets. It is more for dice tracking

**Comment by LuPro** [comment]
Indeed, session history is for movements, GM requests (attacks/open doors) and dice results. Creation of buildings is not (and should not) be handled there.
