### ISSUE TITLE
Camera level view Line and controls do not work.

### ISSUE THREAD

**Issue by s7092910** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#506]
**Describe the bug**
Move the camera level view line on the sidebar doesn't change what level the camera focal point is on (the white circle). Using the keyboard bindings to move the level view also does not change the level view, but still moves the sidebar line.

**To Reproduce**
1. Move the Camera Focus Level Line on the sidebar to a higher or lower level.
2. Press Page Up or Page Down to move to a higher or lower

**Screenshots/Videos/Twitch Clips**
![Screenshot 2020-05-01 00 27 51](https://user-images.githubusercontent.com/9308628/80790177-015a8280-8b43-11ea-9c57-cb44458e1cce.png)

**Additional context**
I believe the build this affects is BUILD-ID: 4969118

**Comment by EHCM81** [comment]
I can confirm this bug as well. I was just about to post this too. The double click elevation still works, but the slider does not.

At least, the double click works for me.

**Comment by s7092910** [comment]
Closing this because it seems fixed in latest build (BUILD-ID: 470014)
