### ISSUE TITLE
Floating above dungeon corner.

### ISSUE THREAD

**Issue by Resendez1** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#517]
Issue where pieces placed above dungeon corner + no floor float as if a single floor piece is in the way. Tested with other corners and only seems to be affecting the dungeon tile.
![Dungeon corner float](https://user-images.githubusercontent.com/63680450/80898448-1bbe6880-8cc9-11ea-8036-ecdfe817e8e3.PNG)

**Comment by LuPro** [comment]
Duplicate of #123
