### ISSUE TITLE
Grass texture broken

### ISSUE THREAD

**Issue by Immortalstar01** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#521]
The texture of the grass tiles seems to break when you leave the game and come back to it. 

The Link shows how the the tile texture behaves when you move the camera:

https://i.gyazo.com/d6d45d5c89a7e841406523ab5c656fb2.mp4

**Comment by LuPro** [comment]
This is another issue where previously deleted blocks sometimes come back after rejoining the game. This results in the textures of the grass "fighting" for which one is on top. This issue is also logged in a few others, so I'll close this
