### ISSUE TITLE
Height slider lock not working

### ISSUE THREAD

**Issue by TheHuckleberry** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#524]
**Describe the bug**
When I lock the height slider it still moves automatically when you move a mini

**To Reproduce**
Fairly self-explanatory
Lock height
Move mini with WASD or Mouse
Slider still moves

**Screenshots/Videos/Twitch Clips**
I'll add these in a sec but I'm sure you get what's happening

**Comment by jonnyree** [comment]
@CorrosivePenguin  This should have been addressed in today's update 5124991.  Would love to have you confirm this if possible
