### ISSUE TITLE
Reloading maps 3/4 of all tiles missing 

### ISSUE THREAD

**Issue by Seiziuss** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#53]
**Describe the bug**
reloading a map by exiting to the main menu and then reloading the level causes tiles to disappear.

**To Reproduce**
1. Exit to the main menu 
2. reload into same board 
3. missing tiles 

**Screenshots/Videos/Twitch Clips**
https://www.twitch.tv/videos/588470753 video of it creation 
https://imgur.com/a/K2VMAGJ - here is the reloaded map with missing tiles 

**Additional context**
bit sad really, its gonna take another 2hrs to rebuild :'(

**Comment by LuPro** [comment]
Board sync/saving seems to be broken by quite a few, definitely a bug

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed already, I'll close this.
