### ISSUE TITLE
Clipping without being enabled

### ISSUE THREAD

**Issue by tvgazza911** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#537]
**Describe the bug**
Tiles clip can be clipped into each without pressing any keys, or having clipping enabled.

**To Reproduce**

1. Select a tile to place
2. Move the screen to begin on an empty space with the tile to be placed at the same height as other nearby tiles
3. Drag the view plane up so that the newly placed tiles will intersect the existing ones

In some cases (like in the screenshot) this leads to rendering issues.

**Screenshots/Videos/Twitch Clips**
![Clipping](https://i.imgur.com/xFAdCY0.png)

For reference, here's a slab with the issue.

```H4sIAAAAAAAAC33SPw4BQRzF8beSTbYntp04gYjaTMSfuIFyElfQ21Y0bqAQjUKh0ohJ9CvUruACCqxlRJh53W/2m5dPs+k1PQYooDc/l8fVbnvd33aGxWUzQgXR6VAb7OutTTxZzFaXuJR9A7QKkTRu99Eue8jnHSCRCPFpgDL/TZCdIDsj/btXc+9AdiC7qULekO/e908zpAnjb9rRNPE08TTxNPEE8QTxBPEE8Yz0e7a5PNtcnm0uD8QD8UA8EM/+uzBft3oA5wxvFFgDAAA=```

I'm unsure if it's related, but there's a warning in the console saying
"This InGameGUI needs to be layer 16, switching to that now"

**Comment by LuPro** [comment]
Not really an issue anymore as clipping is now the default (and only mode) - still interesting to see this happen, however I think the new building tools make this behaviour more consistent and it should happen accidentally anymore
