### ISSUE TITLE
Resolution Help

### ISSUE THREAD

**Issue by xRinzler** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#553]
This isn't so much a bug, but a problem I need assistance with.

My Talespire game didn't boot in the proper resolution, and when I went to change it, I selected the wrong resolution and completely messed up my aspect ratio. Here's what I have tried already:

Completely deleting and uninstalling Talespire.
Using windows 10 to manually change the ratio.

Is there a way to change the ratio outside of the game so that I may select the proper ratio? Perhaps a .ini file that allows me to change it? I would provide a screenshot but it would seem windows and steam won't allow me to take one while in-game.

**Comment by LuPro** [comment]
Check #55 for info on how to change resolution manually. As this bug is already logged in #318 I will close this
