### ISSUE TITLE
Issue with click and drag placement for walls

### ISSUE THREAD

**Issue by ian4150** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#559]
**Describe the bug**
I was trying to drag click a length of 2x1 dungeon wall to set up a room and instead it automatically makes the dimensions of the click drag to width 2 and then only copies the walls into the section it made instead of the original area

**To Reproduce**
1. Select a wall
2. Try to click drag placement along the x1 length

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/44068405/82954476-736f8d00-9f72-11ea-9e0a-100e9c668a22.png)

![image](https://user-images.githubusercontent.com/44068405/82954508-85e9c680-9f72-11ea-8274-50a3e90ce05d.png)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Based on the description I'm not entirely sure, but could it be that's the bug described in #17?

**Comment by ian4150** [comment]
It sounds similar although with a different wall. Also one thing I didn't see was the mention of the click drag in a certain way. For example I was still on the same axis as the wall but the placement box was extended to one of the neighboring axis spots. (If I placed it on x-axis 1 then the box would select x-axis 2 or x-axis 0). Also if I let go of the click drag it would only place a row of walls in the wrong x axis. (2 or 0 in earlier example)

**Comment by jonnyree** [comment]
@ian4150 This should have been addressed in the latest update 5124991.  Would love to have you confirm this if possible
