### ISSUE TITLE
Deleting board with creatures in initiative mode -creates blank <unknown> 

### ISSUE THREAD

**Issue by Twotricks** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#56]
Deleting board with creatures in initiative mode - creates blank <unknown> fields in the initiative area, that can not be removed or deleted in any way

**Comment by Maxnwil** [comment]
I've also found this issue. I've attached a screenshot

![20200410195404_1](https://user-images.githubusercontent.com/63475362/79030186-d1cce180-7b65-11ea-9295-edfef9ea80d8.jpg)

**Comment by cbaggers** [comment]
I believe this was fixed by the fixes I made for #83 the patch with those fixes will be coming out tomorrow

**Comment by LuPro** [comment]
Considering I haven't seen this issue be reported again and no further comments on this, I think this is fixed. If this error is still reachable please comment so the issue can be reopened
