### ISSUE TITLE
Fern 02 2x2 Tile is not the correct size

### ISSUE THREAD

**Issue by jrwillette** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#563]
**Describe the bug**
The Fern 02 2x2 tile is smaller than a 2x2 tile and cannot be placed properly.

**To Reproduce**
Select the Fern 02 asset
Hold shift down when placing to view the grid.
Notice how it is basically a 1.5x1.5 tile.

**Screenshots/Videos/Twitch Clips**
https://youtu.be/6phEtbtfFWs

**Comment by LuPro** [comment]
Going to mark this as an asset issue though I'm not quite sure if it actually is an error/something fixable. I presume once the new prop placement hits, this is going to be a non-issue anyways, but maybe something can be done for better placement of these before that.

**Comment by jrwillette** [comment]
Since the new prop system this is not really an issue.
