### ISSUE TITLE
Weird black square on the map

### ISSUE THREAD

**Issue by Vabres** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#564]
**Describe the bug**
Hi, there's a weird black square (10x10) on the map always centered in the middle of the screen. It hides walls and tiles but doesn't affect doors, foam or tokens (here's some screenshots : https://imgur.com/a/DWbmfvi). Reloading the campaign seems to do the trick to make it disapear, but there's the 'syncing' logo that kept looping. Finally, I don't know if it's related or not, but Steam keeps showing Talespire as running even though I closed it and it doesn't show up in the task manager (https://imgur.com/68V1VA3).

**To Reproduce**
1. Talepspire running with a vpn connection on
2. Lost connection for a few seconds while in building mode
3. When the connection came back, Talespire pulled the last commit
4. Black square on the map

**Screenshots/Videos/Twitch Clips**
![Capturebug1-1](https://user-images.githubusercontent.com/33997637/83558954-18124180-a514-11ea-8c2c-34aeb9dccdca.PNG)
![Capturebug1-2](https://user-images.githubusercontent.com/33997637/83558956-19436e80-a514-11ea-8fa6-7f35c4f23cb1.PNG)
![Capturebug1-3](https://user-images.githubusercontent.com/33997637/83560377-6d4f5280-a516-11ea-876b-d453521fd70f.PNG)

**Additional context**
I don't know what else to add, so i'll just say that i've been having blast making maps and i'm loving Talespire so far !

**Comment by LuPro** [comment]
Press "N" :) That's the "cutbox" meant to help you look inside buildings when you want to move a character in there for example (also the "-" button next to the height sliders). It currently isn't perfect (eg: it doesn't cut some things it should cut and there are some bugs when trying to interact with tiles in the cutbox), but this is still very much intendeed behavior
