### ISSUE TITLE
No way to save?

### ISSUE THREAD

**Issue by Tyranboi** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#57]
**Describe the bug**
It's not a bug as much as it's just a missing feature;

So I spent about an hour and a half (Ish) making a little tavern, just as a test for when I start using it to make campaigns. So I was done with it, nice, tested it all out, everything was ok. I thought I'll quit and try something else. I looked around and couldn't see a save button and eventually thought it must just save on quit,  so I quit to the main menu and realised I'd forgotten to put something in so I loaded back in - Bam, literally all there was, was the base framework of the tavern. Literally just the walls and the floor.

It hadn't saved for over 40 minutes at least. I searched everywhere, and have since searched everywhere again for a save button and I have yet to locate one. I even tried hitting ctrl + S just to be safe but nope.

Yes, luckily this was just a test so I'm not overly annoyed but what I am annoyed at, is for anyone that dives straight in making campaigns for their friends and has to quit for whatever reason and loses loads of progress.

**To Reproduce**
1. Load Game
2. Build Something
3. Quit
4. Doesn't Save

**Comment by LuPro** [comment]
Going to close this particular issue, as the devs have (temporarily, while the sync bugs are in place) introduced a manual "save" (sync) button. The actual error with the sync is probably not quite fixed (or at least not all occurrences of this bug, some sources of this have already been addressed), but these errors are reported in other issues already.
