### ISSUE TITLE
Remote controllable door

### ISSUE THREAD

**Issue by MyMolly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#570]
Copied a premade slab ( https://talestavern.com/slab/modcity-sewers-encounters/  the "throne room" w/ adjoining small rooms), quit session and started up a different day. And there are now four adjoining hatches that seemingly send their inputted commands to other objects *see linked gif* those other objects do not control the hatches.

*linked gif: https://gyazo.com/6addc2f2f9bb89f6b2941508b0b32bab

//Copying the slab does not replicate the bug to the copied building. **Proven false**
Switching boards, exiting to main menu, or exiting game completely. None of these actions change or remove the remotecontrol

**Comment by MyMolly** [comment]
on second investigation the copied slab also have remote control hatches but in different locations

https://gyazo.com/5909c13dc137ae88286d45441b6c3127

**Comment by MyMolly** [comment]
Third round of testing, it was completely reproducible. Copied it fresh from tales tavern in a new campaign and there is remote control hatches, they're paired up in adjacent tiles. in the bottom right you can see it controlling a nearby portcullis within like two foamblocks if it matters

https://gyazo.com/7c37b464aa48b0f98d020e3b7e9e2c7e

**Comment by Felivath** [comment]
I have a similar issue. I used the dungeon generator (https://talespire.creadth.com/slab/import-dungeon) to get a empty dungeon slab. Added it to my game and filled it with spooky stuff like coffins. Came back the next day and while trying to open this door it was opening a coffin nearby instead. 

https://gyazo.com/2e196c6fc4dd66396ea2638db5c72231

**Comment by cbaggers** [comment]
Excellent report, thank you. I can confirm from the paste linked that two tiles are being assigned the same script id. I'm guessing I have a bug in paste, I'll dig into this.

I'm super happy to have a lead on this one. I had not been able to replicate the issues consistently before now

**Comment by cbaggers** [comment]
This should be fixed in the next update for newly built/pasted tiles. The update wont fix currently broken tiles however
