### ISSUE TITLE
"Flying" Player Token

### ISSUE THREAD

**Issue by lunalonewolf** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#575]
**Describe the bug**
I was just trying to move my token while using the fly move, so I was holding my token in the air, and I was near an invisible spot; the DM rolled a 92, and told me to stop, I stopped and my token didn't drop.

**To Reproduce**
1. Pick up token
2. Try to maneuver near tree line
3. Stop near blank spot at pine tree height
4. Get flying token

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

![image](https://user-images.githubusercontent.com/67572941/85974631-d8ac0900-b98a-11ea-8354-9d711d36e791.png)

**Additional context**
Unburden yourself of thoughts and musings here

Personally, if you guys can make it so the tokens can fly/hover without needing to rest on something, that would be amazing!

**Comment by LuPro** [comment]
While cleaning up old issues I noticed I didn't come around to answering on this one. To me it seems the character was sitting on the tree crown asset (it has a bit generous collision mesh size), so not really a bug.
Also, flying for minis got added now (quite a while ago actually) in case you didn't know that :)
