### ISSUE TITLE
Screen too zoomed in

### ISSUE THREAD

**Issue by Nickneedshelp** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#584]
The screen ratios are off and I am unable to change the display seetings.

I was casting talespire to a different device off my laptop, and while casting, changed the display settings from window to full screen, and it immediately looked like the picture below. I uninstalled and reinatalled the app twice, and restarted my computer.
![InkedTalespire bad_LI](https://user-images.githubusercontent.com/68879765/88603507-c29d7100-d03a-11ea-8b1d-3dca29adc4bb.jpg)

**Comment by LuPro** [comment]
Check #55 for a fix for this, apart from that it is similar to #318, just from a slightly different source - interesting to see where it triggers, but ultimately the same problem
