### ISSUE TITLE
Changing player role increases UI size

### ISSUE THREAD

**Issue by vagabond666** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#585]
**Describe the bug**
Changing a player role causes the player list text to get bigger. You can repeat it until the text is so big the buttons to change roles are inaccessible.  

**To Reproduce**
1. Bring up the players "tab" on the left side of the screen
2. Change a player role from player to GM
3. Change back to Player
4. Repeat 2 and 3 until the buttons go off the right side of the screen

**Screenshots/Videos/Twitch Clips**
https://cdn.discordapp.com/attachments/530921919458050089/732195237598068816/TS_big_names.png
https://cdn.discordapp.com/attachments/530921919458050089/737459268319707136/TS_BigText.png

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by jonnyree** [comment]
This was fixed in BUILD: 5632745
Thank you for the report!
