### ISSUE TITLE
Hover text for the ruler says "toggle cutbox"

### ISSUE THREAD

**Issue by vagabond666** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#587]
**Describe the bug**
I assume hovering over the ruler icon is supposed to say "ruler" or similar.

**To Reproduce**
1. Move the mouse pointer over the ruler box.

**Screenshots/Videos/Twitch Clips**
https://cdn.discordapp.com/attachments/530921919458050089/738321985368621066/TS_ruler_hover.png

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by jonnyree** [comment]
Thanks! Fix is in next patch.
