### ISSUE TITLE
Changing object height after CTRL-C or CTRL-X

### ISSUE THREAD

**Issue by DragoonTM** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#588]
When you drag a new object into a scene, you can SHIFT + Mouse Wheel will increase or decrease the object's height. I you copy or cut a model this ceases to function until you place the model and pick it back up again.

Pull out a new tile.
SHIFT + scroll to see it change height.
Place tile.
Capture tile in a copy / cut box.
CTRL + C or CTRL + X to copy or cut the tile.
Try to shift + scroll wheel to change tiles height prior to placing it.
You should see the zoom function operating instead.
Place the tile
Pick it back up
Test again
It should work as expected this time.

Frustrating when trying to copy or cut tiles and alter their height.

Amazing work you all are doing. Keep it up!!

Regards,
Tim

**Comment by LuPro** [comment]
This feature has now been added - Ctrl is the modifier key for changing height and it works on minis, slabs, tiles and props alike :)
