### ISSUE TITLE
X no longer closes help window

### ISSUE THREAD

**Issue by vagabond666** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#589]
**Describe the bug**
Clicking the x on the help/reminder box no longer closes it. 

**To Reproduce**
1. Click the x. 

**Screenshots/Videos/Twitch Clips**
https://cdn.discordapp.com/attachments/706933655653580901/740174258730434600/unknown.png

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
The help window is no more. Long live the help bar \o/ 
(Not an issue anymore, help window is gone now)
