### ISSUE TITLE
Mini spawned in stuck

### ISSUE THREAD

**Issue by mawestover** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#593]
**Describe the bug**
I was placing a mini into the world and it got 'stuck'. This has happened before, but it was only stuck on one board before. This time, the mini is so stuck that I can create a new world and the miniature is still sitting there awkwardly in limbo and cannot be selected. Other minis added before and after work without issue.

**To Reproduce**
Unfortunately, I was just placing minis into a map, so I can't replicate the issue. I was placing the model near some rock and trees in the map, so maybe that had something to do with it. Sorry that I can't be more helpful.

Note: if you restart TaleSpire, the glitched figure disappears.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![image](https://user-images.githubusercontent.com/63564868/91764770-17319000-eb95-11ea-9014-81345e121bc1.png)

**Additional context**

**Comment by ZachHunt359** [comment]
I ran into this issue today. Glad to see it's already been reported.

**Comment by LuPro** [comment]
Should be fixed by now, see #592
