### ISSUE TITLE
Often tiles fail to draw when you zoom out (when the green altitude cut off marker shoots up)

### ISSUE THREAD

**Issue by Roxfall** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#597]
**Describe the bug**
When you work with a green altitude marker to cut off roofs on a big scene, and then zoom out back to see everything, some tiles along edges and corners of the previously hidden area fail to unhide themselves, leaving gaps and holes in the scene. The tiles are still there, but to see them, you need to zoom back in and out with them in the center, but this often breaks other tiles, repeating ad naseam. This is a long-standing issue.

**To Reproduce**
1. Create or load a big scene.
2. Zoom in by double clicking on the ground so that roofs come off, or drag the green thing down, then using the scroll wheel.
3. Place some new tiles.
4. Zoom out with mouse wheel until all the roofs come back. Look around. You'll notice some missing tiles around the edges of the area where you did work, on neighboring buildings and the like.

**Comment by LuPro** [comment]
On second thought, could you check issue #577 and by extension #471 if that could be the same issue as the one you're having? They seem similar, but I'm not entirely sure without knowing exactly what you experienced

**Comment by Roxfall** [comment]
Yeah, that's the exact same issue.

**Comment by Roxfall** [comment]
I was a dummy and posted another bug on the same issue here: https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/604

Now with a couple pictures.
