### ISSUE TITLE
Main Menu does not load

### ISSUE THREAD

**Issue by Cortegos** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#6]
**Describe the bug**
I clicked "Play" in Steam after downloading the beta app, and the main screen loads, but I get a spinning hourglass, and nothing else happens.

**To Reproduce**
1. I load Talespire.

**Screenshots/Videos/Twitch Clips**
https://imgur.com/a/bPQpE1E
https://imgur.com/a/wvdcVey

**Additional context**
Please fix!  I'm excited! :)
Attempted to close and reload multiple times, uninstalled and reinstalled, ran executable as administrator - all same result.  I also am not using a VPN of any sort - currently residing in the United States.

Update: Stupidly - turning my PC off and back on again has resolved my issue.  Hopefully others don't have it.

**Comment by Sebdevar** [comment]
Issue can be closed as it seems to be resolved.

**Comment by cbaggers** [comment]
Other people have been having this too. It's odd. I'll look into the region searching code as something seems to be silently failing there. Maybe we can just write our own

**Comment by Televisation** [comment]
Having the same issue myself, although restarting the game client / Steam / my machine has not resolved the problem.
I'm using a Surface book, no VPN, connecting from the UK.

**Comment by Televisation** [comment]
Ok, after a number of reinstalls and restarts, I discovered a solution of sorts:
After installing (or re-installing), do not attempt to Play! Restart the PC **first**, _then_ Play.

Any attempt to play after re-installing (without a restart first) prevented the game from ever loading, even after subsequent restarts.

**Comment by LuPro** [comment]
As this hasn't been encountered for a good while now, I'll close the issue. If it pops up again, please create a new issue.
