### ISSUE TITLE
Performance issues on immense maps

### ISSUE THREAD

**Issue by Sergueil819** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#601]
Hi!

I'm currently building a city map with over 60 houses/castle/church/bridges/river/forest/etc, fully furnished. Performance really take a dive when I'm trying to zoom out and get a global view of the map. The worst issues regards the screen violently shaking until it reaches a zone with no construction, where it stops and performance increases. So my guess is simple.. too much stuff need to be loaded at the same time and the game cannot handle it yet. Every house on my map is fully furnished, but it is not required for the items inside the houses to be displayed at all times. Could there be a distance at which items other than walls/trees/cliffs/grass are not loaded until our view distance is smaller? Or a sliding bar which would allow us to choose the distance at which stuff is displayed?

The lag is minimal when the view is set close to the board (playable distance).

This issue has been reported at least once in post #594.

Thank you!! Keep up the good work! I can't wait to get my friends in here when it's available!!

**Comment by LuPro** [comment]
I think the screen shaking hasn't been fixed entirely yet, but Chimera has brought a *ton* of performance improvements to the table and I think the screen shaking happens less frequently/at lower fps. I'll close this for now, if the screen shake is a bigger issue for you, feel free to create a new issue targeted around that one :)
