### ISSUE TITLE
Rural roof casts odd shadows. Normal maps borked? 

### ISSUE THREAD

**Issue by Roxfall** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#603]
**Describe the bug**
At certain angles, the rural (hay) roof casts strange shadows on itself. Doesn't look good.

**To Reproduce**
1. Make a 8x8 pyramid out of the hay roof tiles.
2. Play around with the sun on the board.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![image](https://user-images.githubusercontent.com/30673911/93150340-dd997280-f6c6-11ea-89c5-3596699345bd.png)

**Additional context**
Might be worth looking at what's happening with normal maps. Are they flipped on these assets?

**Comment by jonnyree** [comment]
@Roxfall This should be fixed in the latest build on steam. Which was released approximately around the time this was reported. Let me know if that is not the case. Thanks for reporting!

**Comment by Roxfall** [comment]
Confirming, it's fixed.
