### ISSUE TITLE
Some tiles fail to render after hiding the ceiling, modifying terrain, and then zooming back out.

### ISSUE THREAD

**Issue by Roxfall** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#604]
Description:
This happens 100% of the time on large enough boards with lots of overlapping details, like roofs. You zoom in (double clicking on the floor of an interior space), so the roofs and floors above go away, modify some stuff, and then zoom back out. Some tiles on the edges of your previous view point fail to "fall back down" and render, although they still cast shadows.

1. Zoom in or move the green pin to remove roofs.
2. Place some new tiles.
3. Zoom out.

Picture: 
![image](https://user-images.githubusercontent.com/30673911/93151069-d4a9a080-f6c8-11ea-8c1b-587254f0a282.png)
In this case I was modifying something under the ground. This line of tiles was near the edge of the screen. It still casts shadows!

Workaround is to zoom back in and out again so the tiles pop back into place. It can be disconcerting during play though and confuse the hell out of players.

**Comment by Roxfall** [comment]
Same spot after zooming in and out again.
![image](https://user-images.githubusercontent.com/30673911/93151194-3b2ebe80-f6c9-11ea-89b1-d85e0e61e66d.png)

**Comment by Roxfall** [comment]
My best guess is that Talespire counts how many tiles it hid from view, and then when you place new tiles, this counter is off by 1 for each tile placed, so when it's time to put the tiles back in, it fails to drop all of the tiles. They are always on the edges of the previous screen view, and are always in straight lines like this.

The bug has been present since day 1, but until now I couldn't exactly replicate it.

**Comment by Weird-devi** [comment]
I have this happen even if I dont place any new tiles. Some tiles just stays hidden even when they shouldnt be, but zooming in then out again makes them re-appear. When I showed one map to a friend, this happened to a floor tile, and they saw and walked right through it even though it was supposed to be there. Anoyed me a bit as it made them see the secret cave beneath the floor, so messed up my suprise.

**Comment by LuPro** [comment]
As said in #597, refer to #577 and/or #471 for further information on this issue, thanks for the extra data.

**Comment by Roxfall** [comment]
This is still happening in the latest build btw.
