### ISSUE TITLE
Corner + No Floor tile placement issues.

### ISSUE THREAD

**Issue by Ruladian** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#606]
The **Corner + No Floor** tile in the **Dungeon** tab do not allow any other tile to be placed directly on top of them.
![Wall + Corner Bug](https://user-images.githubusercontent.com/6038597/93691475-8dd9f300-fa9a-11ea-9008-1a8960849770.png)

**Comment by LuPro** [comment]
duplicate of #123
