### ISSUE TITLE
Hero Model Title

### ISSUE THREAD

**Issue by CosmiVox** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#607]
**Describe the bug**
When you open the side menu to select the Half Demon Warlock(Necromancer) the name Half Demon Warlock is repeated twice in the menu bar.

**To Reproduce**
1. Open the hero tab where the creatures are located.
2. Find the Half Demon Warlock and you see the repeat
![PictureWarlockIssue](https://user-images.githubusercontent.com/59884418/94350908-d81e1f80-0018-11eb-9c21-dc7f46972a21.PNG)

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Old asset library doesn't exist anymore, got replaced with new UI - this issue doesn't exist anymore
