### ISSUE TITLE
Summon Players to Board

### ISSUE THREAD

**Issue by NinjaOperative** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#622]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

Players are supposed to be pulled from one board to another.

**To Reproduce**
1. Punch an ogre '...' **Spawn on one board.**
2. Set a chair on fire '....' **DM loads new board.**
3. Tried to open a door '....' **Players get stuck on "waiting on DM"** (players can go to the board menu and just pick it and that works.
4. TaleSpire crashed - lite

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
Sorry, no gold here my liege. Just disappointing tidings from The Forgotten Kingdom.

**Additional context**
Unburden yourself of thoughts and musings here
We found a work around. From my perspective, it seemed like the buttons' embedded link to the players wasn't connected on the players end. I'd assume from a mismatched directory path of some sort or my players somehow weren't connected to my board per se.

**Comment by roguelock** [comment]
I have also been having this issue for the past two weeks.

**Comment by LuPro** [comment]
Should be fixed now

**Comment by NinjaOperative** [comment]
Thanks!
