### ISSUE TITLE
Pasting a slab - Tiles missing but not in preview

### ISSUE THREAD

**Issue by cptn-cosmo** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#63]
So I was trying to paste this slab: https://talesbazaar.com/prefab/62

In the "preview" (after Ctrl+V, when you can move around the slab) it looked correct, but after placing it (left click) some floor tiles were randomly missing

**Comment by LuPro** [comment]
check #172 for possible reproduction steps
