### ISSUE TITLE
Merged assets in the Building assets tab

### ISSUE THREAD

**Issue by Charminbear** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#632]
**Describe the bug**
I have been building a city for about a week now. I've used many or most of the building assets at some point. Just now while building a church I was using the Moorgoth assets, then when I scrolled down to use the Moorgoth Large Wall 02, the icon shows the Large wall, but behind it I can also see the Leather Chest icon. When I click on Large Wall 02 to use it, the Leather Chest populates.

**To Reproduce**
Not sure to be honest. Maybe
1. Use the leather chest asset
2. Use several moorgoth assets
3. Bug occurs?
![Moorgoth Large Wall Leather Chest Bug 001](https://user-images.githubusercontent.com/75871512/101972380-d836c000-3c02-11eb-9168-9caac65122a8.jpg)
![Moorgoth Large Wall Leather Chest Bug 002](https://user-images.githubusercontent.com/75871512/101972387-d8cf5680-3c02-11eb-9980-825ba3c37a13.jpg)

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Charminbear** [comment]
Oh, forgot to mention. Reloading the board did not fix the issue, but exiting to the main menu, then returning to the board solved the problem. 

Since it was an easy fix if I shouldn't have reported this bug I apologize. Just wanted to help out in any way I can, can't wait for more assets Talespire will soon become my favorite part of D&D I love it!

**Comment by LuPro** [comment]
no matter if easy fix or not, it's good to report - in the end it's a bug that needs fixing from the devs :) definitely an odd one though

**Comment by LuPro** [comment]
Rejoice, this bug should be no more!
Mostly because the building menu has been replaced with the new asset library and I doubt this (vastly different) design has that same issue. If it does and you find it, definitely comment so I can reopen this issue!
