### ISSUE TITLE
Dragon mini rotated 25° or so forward

### ISSUE THREAD

**Issue by vivas555** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#636]
**Describe the bug**
I was moving around my map and saw the 4x4 flying dragon mini had rotated 25° or so forward. I barely had time to realize what was happening that it went back to normal and that was it. No idea why it happened or how to reproduce it. It was above castle ruins large floor.

**Comment by LuPro** [comment]
I'm not entirely sure based on the description - could it be similar to/the same as issue #43 and/or #198 ?

**Comment by vivas555** [comment]
Visually similar to #198  I would say, but I don't recall the dragon being moved and there was no bear rug or animation other than the floating still animation.

**Comment by LuPro** [comment]
Closing this in favor of issue #791
