### ISSUE TITLE
Upgrading boards crashes the game

### ISSUE THREAD

**Issue by LuPro** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#640]
**Describe the bug**
Upgrading boards from Beta to Chimera crashes TaleSpire.

**To Reproduce**
1. Open TS
2. Click on old campaign
3. Press upgrade
4. Wait
5. Crash! 🎉 

Edit: This is wide spread, but not universal - if you think you have an idea about what's up, drop it in the comments. The more data the better :)

This is my log file for the crash: https://pastebin.com/VaJaqp9y
If you want to attach yours, it can be found in `C:\Users\<$User>\AppData\LocalLow\BouncyRock Entertainment\TaleSpire`. 
If you are sensitive about your private information, remember to search and replace your Windows Username before uploading (as it is seen in the file paths in the log)

**Comment by PurpleGranite** [comment]
From the boards I have, some that have no objects clipping others have updated fine, but the ones that failed I know for sure have (lots of) clipped objects.

**Comment by Ja07sj** [comment]
I've just updated a simple old board with no clipping, and it upgraded just fine. However all of my more advanced boards with clipping are currently crashing.

**Comment by jrwillette** [comment]
I tried it on all of my campaigns. The only one that completed was a fresh campaign with one board that I did no building on.
One other campaign, the first board seemed to transfer, that only had minis in it, no tiles and it failed on the next board.
Another campaign failed that I'm pretty sure had tiles but no clipping.  I think it did have hide volumes, but previous ones that have failed did not have hide volumes.

**Comment by UnsoughtAngel** [comment]
It's happening on both my campaigns as well. One of which is 40+ boards for a primary campaign and the other only has 2 boards, both failed on board one and both have clipping.

**Comment by MirianRoth** [comment]
Same here, it's happening with almost every single campaign I have.

**Comment by JakeEkiss** [comment]
I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.

**Comment by PurpleGranite** [comment]
> I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.

@JakeEkiss Sounds like a different issue - the one being discussed here is in TaleSpire after you've upgraded via Steam, when updating your TS boards to the new format - you seem to be having an issue with the actual Steam Client updating the game itself, which is probably best raised with Steam Support directly.

**Comment by JakeEkiss** [comment]
> > I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.
> 
> @JakeEkiss Sounds like a different issue - the one being discussed here is in TaleSpire after you've upgraded via Steam, when updating your TS boards to the new format - you seem to be having an issue with the actual Steam Client updating the game itself, which is probably best raised with Steam Support directly.

That's how this bug started. Everything above happened, but when I tried to boot again after the crash this is the thing that happened. In addition, after restarting my comp entirely, I tried to restart TS and my virus detector went off and said it was infected with something (sadly I didn't catch what).

**Comment by JakeEkiss** [comment]
> > I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.
> 
> @JakeEkiss Sounds like a different issue - the one being discussed here is in TaleSpire after you've upgraded via Steam, when updating your TS boards to the new format - you seem to be having an issue with the actual Steam Client updating the game itself, which is probably best raised with Steam Support directly.

Like, the update had finished, but now it says it isn't, and I'm having issue opening the game at all. But the update was complete and the game opened, but when I tired to update a board the crash happened and all these other issues immediately followed.

**Comment by JakeEkiss** [comment]
> > > > I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.
> > > 
> > > 
> > > @JakeEkiss Sounds like a different issue - the one being discussed here is in TaleSpire after you've upgraded via Steam, when updating your TS boards to the new format - you seem to be having an issue with the actual Steam Client updating the game itself, which is probably best raised with Steam Support directly.
> > 
> > 
> > Like, the update had finished, but now it says it isn't, and I'm having issue opening the game at all. But the update was complete and the game opened, but when I tired to update a board the crash happened and all these other issues immediately followed.
> 
> Ahh - that sounds like something in the local game files became corrupted during the unexpected shutdown of the game - If it will let you, try doing "Verify integrity of game files" in the Local Files tab in the Properties.

So, what I ended up doing was a complete uninstall and reinstall, and I'm still having the issue. Not sure if I'd still need to verify local files in that case.

**Comment by JakeEkiss** [comment]
> > > > I'm getting this bug, but instead of just a crash, Talespire now cannot be opened at all in Steam. The update had completed, but now in my Steam library it shows a "update paused" message. If I click "resume" it immediately pauses again and nothing happens. The Steam icon in my taskbar also now has a yellow tint to it which I've never seen before.
> > > 
> > > 
> > > @JakeEkiss Sounds like a different issue - the one being discussed here is in TaleSpire after you've upgraded via Steam, when updating your TS boards to the new format - you seem to be having an issue with the actual Steam Client updating the game itself, which is probably best raised with Steam Support directly.
> > 
> > 
> > Like, the update had finished, but now it says it isn't, and I'm having issue opening the game at all. But the update was complete and the game opened, but when I tired to update a board the crash happened and all these other issues immediately followed.
> 
> Ahh - that sounds like something in the local game files became corrupted during the unexpected shutdown of the game - If it will let you, try doing "Verify integrity of game files" in the Local Files tab in the Properties.

Also, looked into my anti-virus and it said that talespire.exe was infected with IDP.generic

**Comment by PurpleGranite** [comment]
> So, what I ended up doing was a complete uninstall and reinstall, and I'm still having the issue. Not sure if I'd still need to verify local files in that case.

No harm trying it, but it's unlikely to work if you've completely reinstalled.

I think your virus detection is a false-positive, I dropped the main executable into VirusTotal which reports zero hits from 67 different AV engines.

**Comment by JakeEkiss** [comment]
> > So, what I ended up doing was a complete uninstall and reinstall, and I'm still having the issue. Not sure if I'd still need to verify local files in that case.
> 
> No harm trying it, but it's unlikely to work if you've completely reinstalled.
> 
> I think your virus detection is a false-positive, I dropped the main executable into VirusTotal which reports zero hits from 67 different AV engines.
Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.

**Comment by LuPro** [comment]
> Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.

Can you go to the local files and try if TaleSpire starts when running the .exe? Feels like steam is just confused on that one

**Comment by JakeEkiss** [comment]
> > Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.
> 
> Can you go to the local files and try if TaleSpire starts when running the .exe? Feels like steam is just confused on that one

I'm not sure how to do that exactly.

**Comment by JakeEkiss** [comment]
> > Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.
> 
> Can you go to the local files and try if TaleSpire starts when running the .exe? Feels like steam is just confused on that one

I verified the local files using steam but no luck so far. Not sure what else I need to do.

**Comment by LuPro** [comment]
> 
> 
> > > Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.
> > 
> > 
> > Can you go to the local files and try if TaleSpire starts when running the .exe? Feels like steam is just confused on that one
> 
> I'm not sure how to do that exactly.

if you go to the settings menu (where you also checked for file integrity) there should be a button saying "browse..." clicking on there should open the folder where talespire installed and in there should be an .exe

**Comment by JakeEkiss** [comment]
> > > > Yeah, it had quarantined talespire.exe and I deleted that, then did a fresh install, still the same issues. No idea. Can't get into TS at all. Just stuck on "download paused" (even though the download completed) and when I hit resume it just recycles the paused message.
> > > 
> > > 
> > > Can you go to the local files and try if TaleSpire starts when running the .exe? Feels like steam is just confused on that one
> > 
> > 
> > I'm not sure how to do that exactly.
> 
> if you go to the settings menu (where you also checked for file integrity) there should be a button saying "browse..." clicking on there should open the folder where talespire installed and in there should be an .exe

Yeah, not showing the .exe anymore. I'm guessing my anti-virus nuked it, but I reinstalled after, unless it's just stopping it from being downloaded now. I have no idea.

**Comment by LuPro** [comment]
An update just went out to steam that should fix this, please do let me know if the upgrading works for you now :)

**Comment by JakeEkiss** [comment]
> An update just went out to steam that should fix this, please do let me know if the upgrading works for you now :)

Still crashing when I try to upgrade old boards.

**Comment by LuPro** [comment]
that's odd, anyone else still getting a crash on upgrading? there are some other (luckily less common issues) with the upgrader, but crashes should have been fixed

**Comment by PurpleGranite** [comment]
All of my boards have upgraded successfully ... having other issues with those boards (which I'll try and add to appropriate issues here with logs), but the upgrade has gone OK.

**Comment by JakeEkiss** [comment]
> that's odd, anyone else still getting a crash on upgrading? there are some other (luckily less common issues) with the upgrader, but crashes should have been fixed

Looks like it's working this morning. Not sure what was up before, but no crashes this time on upgrading.

**Comment by LuPro** [comment]
That sounds good then, I'll close the issue for now and for the other campaign upgrading bugs I'd refer to the other issues already openend. If someone still continues to have this problem (with actual crashes on upgrading) please do tell so I can reopen this.
