### ISSUE TITLE
Cannot Build Outside Certain Area - Hit Invisible Wall

### ISSUE THREAD

**Issue by PanoramicPanda** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#644]
**Describe the bug**
After 300 tiles, you hit an invisible wall you can no longer build past

**To Reproduce**
1. Create Map
2. Build out/go out 300 tiles
3. Cannot move tiles in hand outside of range

**Screenshots/Videos/Twitch Clips**
[GIF](https://i.imgur.com/ubJww6G.mp4)

**Comment by CamoMilly** [comment]
To add onto this one: same thing happens with minis, not only tiles; if you try to set a mini outside of the mentioned range, it "rubberbands" the mini back to within the tile range. In my case, I couldn't set/drag tiles over 250-ish tiles away from the board center, and while I could drag minis over the 250 tiles, they would immediately be teleported back to the 250-tiles-away edge upon dropping them. You also can't double-click focus the area outside of the 250-300 tiles. (Measuring seen below).

Additionally, in one of my tests, the rubberbanding seemed to have bugged the mini's position. (Seen below)

![image](https://user-images.githubusercontent.com/74841089/113425891-00604f80-93a9-11eb-8d45-445c2aed6900.png)

![image](https://user-images.githubusercontent.com/74841089/113425926-11a95c00-93a9-11eb-9b31-1e3c97ce64ed.png)

![image](https://user-images.githubusercontent.com/74841089/113425955-1a9a2d80-93a9-11eb-846d-ae3ab92cde57.png)

**Comment by LuPro** [comment]
This should be fixed by now, can you check if this is the case? Would be especially interesting if @CamoMilly still has this issue with the minis or if it also got fixed by this.

**Comment by CamoMilly** [comment]
> This should be fixed by now, can you check if this is the case? Would be especially interesting if @CamoMilly still has this issue with the minis or if it also got fixed by this.

Can confirm that minis are able to be dragged and dropped beyond 256 tiles away from the center of the board now! Seems fixed to me. 
![image](https://user-images.githubusercontent.com/74841089/113484401-7da9c400-947e-11eb-8fb4-9477c7b30ed3.png)
