### ISSUE TITLE
Flipped Assets aren't Flipped

### ISSUE THREAD

**Issue by PanoramicPanda** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#646]
**Describe the bug**
Most of the Flipped assets come out as their normal counterparts.

**To Reproduce**
1. Open asset library
2. Search 'Flipped'
3. Place some of the assets

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/1569246/113208094-68932200-923f-11eb-98c9-5d5a3f94ced9.png)

**Comment by LuPro** [comment]
Flipped assets are now flipped! 🎉
