### ISSUE TITLE
Resolved: Campaign Upgrade Failed; Not Crashed

### ISSUE THREAD

**Issue by flogenos** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#656]
**Describe the bug**
I haven't had any crashes, but this has happened every time I try to upgrade my campaign.

**To Reproduce**
1. Be me
2. Try to upgrade campaign
3. Campaign Upgrade Failed

**Screenshots/Videos/Twitch**
 [unknown-3](https://user-images.githubusercontent.com/68303604/113236908-7199e880-926b-11eb-9af9-c7540654a0c6.png)

**Additional context**
This was on both the 7:00 pm update and the more recent one from about 30 minutes ago.

I'm flogenos on steam

**Comment by Kkares213** [comment]
Am having the same issue. Have tried periodically with each update released- most recent update attempted was Build 6485997.

Log file if that helps any: 
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6253057/Player.log)

**Comment by cbaggers** [comment]
Hi folks. I believe that this bug is now fixed. 
It was fixed on the backend so you should be able to go and upgrade your campaigns immediately.

**Comment by flogenos** [comment]
Yep! Fixed!
