### ISSUE TITLE
All hide volumes have disappeared

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#657]
**Describe the bug**
After the update to Chimera every hide volume in every board in every campaign is gone.

**To Reproduce**
1. Update to Chimera
2. Cry a little

**Comment by PanoramicPanda** [comment]
Popping in to confirm this :(

**Comment by LuPro** [comment]
Forgot to add this after the update: should be fixed now, already upgraded campaigns need to be downgraded and then upgraded again, then the hide volumes should be back again.
If something isn't working still, comment so I can reopen this issue
