### ISSUE TITLE
New board crashing on loadup.

### ISSUE THREAD

**Issue by gregoryfl** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#668]
I made a new board yesterday from scratch, and when trying to load today, it consistently crashes as it starts to load.

![image](https://user-images.githubusercontent.com/53844413/113310514-531d0700-92d6-11eb-9ab0-9a033c2c8875.png)

[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6244340/Player.log)

**Comment by LuPro** [comment]
related to #666

**Comment by cbaggers** [comment]
Thanks for the report @gregoryfl, alas the log doesnt give us much to go on in this case. Are you on the discord? If you have time some day I could join your campaign from our dev build and see if I get a 'better' crash

**Comment by cbaggers** [comment]
Did that board contain hide volumes by any chance?

**Comment by gregoryfl** [comment]
It did. After the patch I was able to have it load all the way, but the
hide volumes were gone, then after about 30 seconds of being in the game it
crashed. Now it is back to crashing while loading, like it did before. I am
on discord yes, sorry I did not check this email earlier, but I can be
available tomorrow (Friday) if you want to check it out and see if it helps
you figure out what is wrong.

**Comment by cbaggers** [comment]
Another crash fix patch just landed. Looking forward to seeing if it helps :)

**Comment by gregoryfl** [comment]
Good day Baggers!

I just tried it this morning and so far it is loading up just fine. I shut
down the game and came back and works as well. I know the hide volumes not
working right are already being worked on, but other than that, all seems
great so far. Thanks again friend!
