### ISSUE TITLE
Build Mode Is Missing Asset Library

### ISSUE THREAD

**Issue by SteelSovereign** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#678]
**Describe the bug**
At first, the build mode did have the tabs at the bottom of the screen for the asset library (and something else that was bound to "c"; neither of the shortcuts worked either...), but when I clicked on them, nothing would happen. Now, those tabs aren't showing up at all. Right now I can only move around and delete tiles I've already placed beforehand, but I can't put anything new onto the board.

**To Reproduce**
Open up build mode...

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![20210402080951_1](https://user-images.githubusercontent.com/81819745/113428266-5aeab300-938b-11eb-9eb6-1b09db55de7e.jpg)

**Comment by PanoramicPanda** [comment]
Have you tried hitting space-bar to get the interface?

**Comment by marcoheisig** [comment]
I have the same problem.  Sometimes the 'Open library' and 'Pick up an asset' tabs on the bottom of the screen are not visible at all, and even when they are visible, nothing happens when I click them or when I press the shortcut.

**Comment by SteelSovereign** [comment]
> Have you tried hitting space-bar to get the interface?

I just did. Ya, that 'fixed' it. I facepalmed so hard I hurt myself.
