### ISSUE TITLE
Selected assets cannot hover over empty board-- only over other assets.

### ISSUE THREAD

**Issue by BrotherPanan** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#681]
Selected assets cannot hover past the edge of a group of other tiles

**Steps to reproduce the behavior:**
1. lay a block of tiles
2. Select an asset (tile or prop)
3. drag the cursor over board floor with asset selected
4. Unable to bring cursor over empty board-- it can only travel over *non-empty* board, in other words, I can hover cursor over any already placed assets, like tiles and props, but cannot leave their perimeter (based on the camera's visual perspective)

**Demo #1**
https://user-images.githubusercontent.com/63543627/113451086-3c0e1000-93cf-11eb-969b-d0491509c272.mp4

**Demo #2**
https://user-images.githubusercontent.com/63543627/113451400-e71ec980-93cf-11eb-8cc4-71663cca1b63.mp4

**Additional context**
Toward the end of the second demo video, you'll see that it appears to be specific to one particular block of tiles or area of the board.  Very strange!

**Comment by LuPro** [comment]
I believe this is the same as #644 - if I recall correctly Ree has said on the discord that he has found the issue and will include the fix in the next patch. (Can't watch the video right now because on phone and it somehow doesn't want to play the video, could you check if it is indeed the same? if so I'd close this one)

**Comment by LuPro** [comment]
Had time to look at the video, it does look exactly like #644 which a few people have reported as being fixed, so I'll close this. If you still get this issue please do tell so I can reopen this.

**Comment by BrotherPanan** [comment]
Hey there, sorry for the delay.  Okay, that sounds great, thank you as
usual for the amazing support!!
