### ISSUE TITLE
Problems right-clicking (opening radial menu) on shrunk miniatures

### ISSUE THREAD

**Issue by CamoMilly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#683]
**Describe the bug**
Right-clicking shrunk (scaled to 0.5x) miniatures's bodies to open the radial menu is irresponsive/failing in some minis. I tested a bit and some miniatures seem to respond better than others. Right-clicking on the affected minis' bases *generally* works fine (not all of them), but if you click on their bodies (or at least most parts on their body), the radial menu just doesn't pop up, as if it doesn't recognize their bodies as valid interactable objects.

**To Reproduce**
1. Spawn a miniature (I recommend the tiefling thief for this one)
2. Set its size to 0.5x0.5
3. (Optional) Toggle flying on
4. Try right-clicking the miniature's body to open the radial menu. 
5. It should be irresponsive.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/74841089/113458927-63bea180-93ea-11eb-9c41-c372009ea1ad.png)

**Additional context**

For clarification: I know that since Chimera launched you need to click on the body of the creature instead of the base to open the radial menu when they're flying, but some of the minis seem to not be responding properly to that either. I tested them both with flying toggled on and off, but testing them with flying on is good since you can test the different miniatures' responsivities without the base, which continues to be properly responsive even when shrunk.

To exemplify what I mean: I did some tests on three different minis; the tiefling thief, the dark-skinned monk wielding dual blades, and the helmeted general (all pictured above). If I shrink them these three minis and fly them:
1. It's near impossible to right-click the tiefling thief mini; oddly enough the only part of her body that responds to being right-clicked is... the back of her foot?
2. The human monk has several parts that are just not responding either, albeit not as drastic as the first one
3. The helmeted general's body mostly responds properly, although some parts don't.

**Comment by LuPro** [comment]
The latest update should hahe a fix for this, can you check if this is working on your end? If so I'll close this issue :)

**Comment by CamoMilly** [comment]
It's working fine on my end now! Issue seems fixed.
