### ISSUE TITLE
Maps were deleted after downgrading and reupgrading

### ISSUE THREAD

**Issue by rosenauk** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#684]
We waited to change anything on our Guild Campaign after the release of the Chimera build. We recently downgraded and reupgraded but some things seemed to be missing so we tried to downgrade and reupgrade again and now the boards are all empty except for some creatures.

**Comment by rosenauk** [comment]
It looks like it's the first 11 boards that were deleted. The others seem to be fine.
![Capture](https://user-images.githubusercontent.com/56204294/113470119-e0ac4400-9407-11eb-9e82-02ac25ae7687.PNG)

**Comment by shortyhero** [comment]
I have the same issue, the problem is that all of the boards that were not created after the Chimera are gone.

**Comment by cbaggers** [comment]
Hi folks. First, just to reassure, non of the data will have been deleted, so this will be recoverable.

Are we sure that @rosenauk and @shortyhero  are having the same issue?

@shortyhero when you say they are gone, does that mean they are empty like the screenshot above? or that they are missing from the board panel all together?

@rosenauk  when you first downgraded and said things were missing, were they missing from the board like there are now or are the boards AWOL from the board panel too?

**Comment by rosenauk** [comment]
@cbaggers I guess I worded that wrong. I meant that there was some functionality that was missing. I was not able to copy pieces of some boards because when I tried there would be an exclamation mark at the top left of the screen. Another thing was that some boards would say something like could not be copied when I clicked to copy the whole board.

**Comment by shortyhero** [comment]
@cbaggers my problem is that the boards are empty like the picture above, they load but have no maps

**Comment by cbaggers** [comment]
@rosenauk @shortyhero thanks to both of you. I'm working on this right now. I can confirm what you are seeing from the backend and am working on creating a test-case which will let me replicate the issue

**Comment by cbaggers** [comment]
Thanks to your data I've been able to find the bug. When the fix goes out you'll be able to downgrade (again) and upgrade to bring back your boards.

**Comment by LuPro** [comment]
The last patch should have fixed this, can you confirm? (Read Baggers comment above this one for details on how to fix previously broken boards)

**Comment by shortyhero** [comment]
Going home right and going to check

**Comment by shortyhero** [comment]
Got home and checked the updated, it is fixed! Thank you!

**Comment by rosenauk** [comment]
It looks to be fixed on my end as well. Thanks so much!
