### ISSUE TITLE
Audio changes to being underwater are not working

### ISSUE THREAD

**Issue by CamoMilly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#687]
**Describe the bug**
Going underwater in TaleSpire is supposed to temporarily "muffle" any music playing in the game's atmosphere settings. It currently doesn't seem to be working.

**To Reproduce**
1. Open a board
2. Go to the Atmosphere Settings and pick a song from the Music dropdown menu
3. Raise the water plane enough to go underwater
4. Lower your camera to go underwater
5. The song that is playing will remain unmuffled. 

**Additional context**
I tested it with multiple songs, so I don't think it's a song-specific bug.

**Comment by LuPro** [comment]
This should be fixed now
