### ISSUE TITLE
Board issues

### ISSUE THREAD

**Issue by Dakotism** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#69]
When I change Boards my build doesn't always save and sometimes duplicates things (walls, fences).

I created a tavern in a testing board. 
I then selected the tavern in its entirety and copied it. (Placed the removed a copy to make sure it was working)
I created a new board to start building the town.
Pasted the copied (Everything was working at this point)
Renamed the new board then went back to the test one.
The Tavern was then missing some props and had extra walls. 
The new board was now missing. And the clipboard was empty.
![NoExtraWalls](https://user-images.githubusercontent.com/63479810/79028653-c8cc1800-7b45-11ea-86bd-0dbca1be251b.JPG)
![ExtraWalls](https://user-images.githubusercontent.com/63479810/79028658-cec1f900-7b45-11ea-9318-fdea921cd171.JPG)

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
