### ISSUE TITLE
Hide volumes unhide after leaving board

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#693]
**Describe the bug**
Any time I leave a board, whether I go to another board within the same campaign or to another campaign entirely, when I return to the original board with the hide volume they are no longer hidden. The hide volume is still present however. Manually pushing a sync does not help.
[Player-prev.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6254496/Player-prev.log)
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6254497/Player.log)

**Comment by PanoramicPanda** [comment]
Adding to this. It appears the sync is per-player as well. As I went to board to re-hide things before bringing the players in, and when they got to the board, things were still revealed to them until I unhide and re-hide them *again*.

https://clips.twitch.tv/AnimatedFitPuddingWTRuck-geoUguQyRNyPOvpQ

**Comment by PanoramicPanda** [comment]
Hide volumes now fixed, minis are not.

**Comment by LuPro** [comment]
Should all be fixed now
