### ISSUE TITLE
Ruler line is 1 sided 

### ISSUE THREAD

**Issue by McCabe554** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#700]
**Describe the bug**
The line to display rulers is one sided 

**To Reproduce**
Shown in video 

https://user-images.githubusercontent.com/19496178/113609035-302a8400-9643-11eb-99aa-64c3feef1d42.mp4

**Comment by cbaggers** [comment]
Thanks for the report! The next release has an improvement for this. Not perfect, but not one sided :)

**Comment by McCabe554** [comment]
Confirmed as fixed, nice job!

https://user-images.githubusercontent.com/19496178/116475482-d435d280-a871-11eb-9c02-73a57629a93f.mp4
