### ISSUE TITLE
Cannot close the game or enter main menu

### ISSUE THREAD

**Issue by BrotherPanan** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#710]
Alt+F4 does nothing.  Selecting Quit to Desktop closes the relevant menu, but does nothing more.  Same happens if I select Main Menu.  I end up having to use Ctrl+Shift+Del to bring up the Task Manager and end the TaleSpire app.

**Comment by LuPro** [comment]
Check #800 for possible reproduction steps

**Comment by McCabe554** [comment]
https://user-images.githubusercontent.com/19496178/115126611-31a36700-9fc8-11eb-9191-d5886340ae62.mp4

Reproduced in video with steps from #800

**Comment by BenteLee** [comment]
after using the photo mode and hiding the photo menu. I exited the photo mode via esc. Then when I tried to use the exit menu, the exit to main menu button does nothing but give the clickt feedback, and the exit to desktop closes the exit menu window but does not seem to do enything else.

**Comment by cbaggers** [comment]
Fantastic work everyone (especially @Clickeddaisy) I was able to replicate the issue trivially.
I'll get it fixed now

**Comment by cbaggers** [comment]
Got it! This will be fixed in the next patch

**Comment by LuPro** [comment]
Should be fixed in the newest patch, can you confirm?

**Comment by Clickeddaisy** [comment]
> 
> 
> Should be fixed in the newest patch, can you confirm?

Confirmation. Issue has been fixed
