### ISSUE TITLE
Rulers are not recognizing props

### ISSUE THREAD

**Issue by CamoMilly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#711]
**Describe the bug**
Rulers are not recognizing props as points of contact. So for example, if your players are traversing a mountain or something where the floor they're standing is cliff face assets, it won't recognize the cliff face floor where they are standing as a point to start measuring, instead ignoring all props on the way until it reaches a tile or the base of the board.

**To Reproduce**
1. Set down a prop (in this case, I used the icy cliff face asset in the first GIF and the regular cliff face on the second)
2. Set down any of the rulers over it or going across it
3. The prop won't be recognized as a point of contact for the ruler.

**Screenshots/Videos/Twitch Clips**
![Prop ruler problem 1](https://user-images.githubusercontent.com/74841089/114209589-2d76aa00-9935-11eb-94f5-045b4e5b430f.gif)

![Prop ruler problem 2](https://user-images.githubusercontent.com/74841089/114209610-336c8b00-9935-11eb-9e25-ffcd327a4f9c.gif)

**Additional context**
This is happening to all three rulers. Tiles are still being recognized just fine.

**Comment by ShaunDave** [comment]
+1 Can reproduce on my side too

**Comment by LuPro** [comment]
Should be fixed now, can you confirm?

**Comment by CamoMilly** [comment]
All fixed! 

![GIF 20-04-2021 17-40-54](https://user-images.githubusercontent.com/74841089/115461354-b0ceb000-a1ff-11eb-8b2a-935374fad091.gif)
