### ISSUE TITLE
Cannot grab minis when they are in roofed buildings

### ISSUE THREAD

**Issue by PanoramicPanda** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#714]
**Describe the bug**
Had minis inside of roofed buildings, used the green slider to see into said buildings, and it took very specific camera angles to even click the mini

**To Reproduce**
1. Build room
2. Place mini inside
3. Put full roof on
4. Try to pick up or use mini

**Screenshots/Videos/Twitch Clips**
https://clips.twitch.tv/GeniusInterestingNightingaleBrokeBack-t7SbsVsUneSzMFtT

**Comment by jrwillette** [comment]
I've noticed this as well, it appears that the pixel perfect choosing of minis is seeing all objects, even if they are currently hidden from view due to the green slider being lowered.

**Comment by ElliottHowchin** [comment]
In case it helps, I have experienced the same thing. I noticed that if I zoom the camera inside the building, so I can see the mini directly, I'm able to click the mini absolutely fine.

**Comment by PanoramicPanda** [comment]
Seems to be fixed in the latest version!
