### ISSUE TITLE
Hidden flying Creature is visible after reload and UI says: "Reveal" instead of hide.

### ISSUE THREAD

**Issue by Albyricus** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#719]
Hi Guys,

i build a map and set an flying creature "Pterodactyl", saved the map and left. Today i started the game, and the Pterodactyl was visible (in normal mode, not GM Overlay or things like that) to me, in the interface it tells me, that i can "Reveal" the creature, if i click there nothing happens, after that i can hide it again!

Update: This even happens if i "only" change the map and return to that one!

Greetings

**Comment by cbaggers** [comment]
Hey @Albyricus, thanks for the report. I can confirm this too. I'll look at it now.

**Comment by cbaggers** [comment]
Woop. Seems to be fixed now. This will be in the next release

**Comment by LuPro** [comment]
This should be fixed now, can you confirm?

**Comment by Albyricus** [comment]
confirm! Bug is fixed!
