### ISSUE TITLE
Hide Volumes not working for Players

### ISSUE THREAD

**Issue by gregoryfl** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#720]
I just loaded up my GM game on one computer, and connected another computer to the game as a player. On my GM side, the hide volumes appear to be working fine (nothing visible), but when the player side connects, or when they disconnect and reconnect, the hide volumes do not work (everything is visible). I have to in each instance, while they are in the game connected, go to each hide volume and disable then re enable them to get them to work on the player side.

**Comment by cbaggers** [comment]
@gregoryfl wow, yeah that straight up doesn't work. Should be an easy fix though. Cheers!

**Comment by cbaggers** [comment]
Yup, fixed. This'll be in the next release

**Comment by LuPro** [comment]
This should be fixed now, can you confirm?

**Comment by gregoryfl** [comment]
Yes, it is working. I just logged in and hide volume both on my side and
players side is working fine.
