### ISSUE TITLE
Unique mini's cannot be placed on board after being placed and deleted first.

### ISSUE THREAD

**Issue by gregoryfl** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#721]
This may be related to Bug #715.

1. Place unique miniature(s) on board.
2. Delete them.
3. Try to place them back on board, will not work. They disappear from being attached to the mouse as soon as you left click to place them on the board.
4.  Tried logging all the way out to desktop and back in, and still have the same issue.

**Comment by LuPro** [comment]
Yeah, sounds like it's the same issue
