### ISSUE TITLE
Street lights doesn't produce lights

### ISSUE THREAD

**Issue by SmugOwl** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#728]
**Describe the bug**
Lights from three way and one way street light doesn't produce light

**To Reproduce**
1. put down either of the lights
2. make it night

**Screenshots/Videos/Twitch Clips**
![Screenshot_5](https://user-images.githubusercontent.com/57043501/114867346-fa309100-9df4-11eb-975b-7797e9d239ea.png)

**Comment by LuPro** [comment]
Duplicate of #648
