### ISSUE TITLE
Ghost assets

### ISSUE THREAD

**Issue by MatthewNock** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#729]
when i place an asset and then go to select another asset the new asset i click on creates a ghost asset that won't go away and i can't interact with it in any way

**Comment by LuPro** [comment]
Is this just for minis or also tiles and props?

**Comment by LuPro** [comment]
Gonna close this as the issue for minis has been fixed. If this occurs for tiles and/or props as well, please comment so I can reopen this issue
