### ISSUE TITLE
glitch that makes props and walls merge together

### ISSUE THREAD

**Issue by Brayo12466** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#73]
**Describe the bug**
After fooling around with trying to build a tavern, I was deleting and replacing many different props, walls, and counters when I had to leave, I exited out of the game using the "exit to desktop" and when I came back, the bed prop was inside the countertop and there were walls littered about the room where I had not placed them when I left.

**To Reproduce**
1. 'Place walls and delete them over and over'
2. 'Replace them with countertops and bed props'
3. 'exit using exit to desktop'
4. come back and they should be all mixed together

**Additional context**
How would you go about using walls and floors because I can't find a good way to make a room without it looking off, such as using a fireplace with walls touching the ground doesn't work but having them on top of a floor tile makes it so that you cant put things against a wall.

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
