### ISSUE TITLE
Placing minis creates "clones"

### ISSUE THREAD

**Issue by Kamakor01** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#730]
When I was placing minis in the world and wanted to change to another one, a unmovable unselectable clone was placed.

**To Reproduce**
1. Select a mini to place
2. Place it in the world
3. With it still selected, click on another mini
4. Current fix is to leave and reload map

**Comment by Stray-Fenris** [comment]
Can confirm and do want to thank kamakor01 for the Hotfix. Would have deleted everything otherwise

**Comment by TheSchnibble** [comment]
I wanted to report this too, but as I'm not the first, I'll just confirm this issue. :)

**Comment by LuPro** [comment]
Duplicate of #592, thanks for the idea for replicating it though :)
