### ISSUE TITLE
Player Can't Join Campaign

### ISSUE THREAD

**Issue by PseudoModel** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#734]
**Describe the bug**
When attempting to join a game, my player receives a message telling them that they're in the space between the boards, as well as all of the axis are present and none of the keys work as well. 

**To Reproduce**
1. I open the campaign
2. player attempts to join
3. Player is trapped in a gray zone with the space between boards error message

**Screenshots/Videos/Twitch Clips**
My player had to leave to a meeting before i could ask for a screenshot, sorry

**Additional context**
Attempted to give the player a GM role, as well as summon to another board, but nothing seemed to have worked for us. My campaign was from Beta, and upgraded, if that helps.

**Comment by LuPro** [comment]
Has your player tried to open the menu and switch to a board? It's odd that the default board wasn't used (did you delete it maybe?)

**Comment by PseudoModel** [comment]
The player ended up reinstalling the game, and we didn't have the issue with any other player. The issue was fixed after the reinstall. Thank you for the follow up!
