### ISSUE TITLE
Big black volumes have appeared next to buildings

### ISSUE THREAD

**Issue by hectorarce1975** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#735]
While creating my first board, I tried to use the fog of war, then disabled it. And big black blocks appeared, I can't erase them o manipulate them in any way.

**Comment by LuPro** [comment]
This seems like fog of war volumes, can you check if you accidentally bound fog of war to something like your left mouse button? I've seen some people do that on accident and then it would trigger the FoW seemingly randomly

**Comment by hectorarce1975** [comment]
No, I haven't. In any case, how do you delete them?

**Comment by LuPro** [comment]
You need to assign a mini to you (right click on the mini -> GM tools -> Player permissions) and then move the mini through the fog, you should see the fog get removed. Unfortunately there's no quick other way yet for doing this (it's very experimental

**Comment by hectorarce1975** [comment]
Thanks!

**Comment by LuPro** [comment]
Actually, could you check in the settings for the keybinding on the fog of war settings? I feel like you might have accidentally bound it to left mouse button when "disabling" it (by pressing on the X) - would be interesting to know if it's a bug that the keybindings didn't work or just bad UI getting you to accidentally set it incorrectly
