### ISSUE TITLE
Mouse Keeps Dragging to the left

### ISSUE THREAD

**Issue by jrw5** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#736]
**Describe the bug**
Just bought the game this morning, used it once  to reasonable success, although I was having an issue once I got into it that the screen kept scrolling (like I was holding down one of the WASD keys). However, hitting the offending direction's key would fix it. Now whenever I open the program, my mouse starts shooting to the left side of the screen, meaning I can't access anything. I changed a couple of visual setting on my first play, but now I can not access anything because of the mouse issue. 

**To Reproduce**
Opened the game and this occurs.

**Comment by LuPro** [comment]
Hm, can't say I've seen this issue before. Is maybe a controller connected and something is lying on top of it and pushes the stick?

**Comment by jrw5** [comment]
I bet that was what it was. Thanks, and I will let y'all know if it ever becomes an actual issue.
