### ISSUE TITLE
Black squares

### ISSUE THREAD

**Issue by Syler57** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#737]
**Describe the bug**
When i try to do a multiple selection the area i selected become a black squares and nothing is selected.
The only way to remove this block is to restart the application.

**To Reproduce**
1. Building mode
2. select "multiple selection"
3. Try to select something
4. Tadaaaam bug!

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/62910686/114899763-894ca180-9e13-11eb-83ef-f46898432b8e.png)

**Comment by LuPro** [comment]
This is the experimental fog of war, can you please check if you maybe accidentally bound the keys of this in the settings to something like the left mouse button or the like?

**Comment by Syler57** [comment]
Thx!  my bad.
