### ISSUE TITLE
multiselection delete leavse a big black box on my board

### ISSUE THREAD

**Issue by olelau** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#740]
Hi! found a bug :)
I used multiselection to delete some props that were stacked on top of each other and it left a big black box on my board where the multiselection was. The Box seems permanent and is still there after switching to different boards and restarting the game.
When it happened I was building together with a friend who I had given the GM permission in my campaign.  Just for the sake of giving you as much info as possible; the props I was stacking were the straight stone fences
![2021-04-15](https://user-images.githubusercontent.com/82604300/114908002-f3694480-9e1b-11eb-864f-7140cfd617fe.png)

**Comment by LuPro** [comment]
It looks like you accidentally bound the experimental fog of war to a key that conflicts with other things - could you check if the fog of war option in the second tab of the settings has a keybinding?
To get rid of the fog of war, you need to assign a creature to yourself with player permissions in the gm tools, then move through the fog to clear it.
