### ISSUE TITLE
Unique Miniature Issue when deleting

### ISSUE THREAD

**Issue by gregoryfl** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#741]
1. Unique miniature placed on board.
2. Kill unique miniature.
3. Unique miniature still shows on player side, DOES NOT show on GM side.
4. Unique miniature cannot be placed back on board by GM, seemingly because it is still registering as on the board from the players side.

Here are 2 screenshots, where the halfling miniature on the left was killed off by the GM and yet still shows up on the player board, but not the GM board.

![player view](https://user-images.githubusercontent.com/53844413/114911242-cc474e80-9dec-11eb-90f0-48a31974c2c0.jpg)
![gm view](https://user-images.githubusercontent.com/53844413/114911250-cea9a880-9dec-11eb-9a80-66eb6c2f64ab.png)

**Comment by LuPro** [comment]
This is probably another manifestation of the issue #592, combined with #715 - can you confirm if this was fixed after going to main menu and back again?

**Comment by gregoryfl** [comment]
I tried both that, and logging completely out and right back in, and
neither worked. However, if I logged out and waiting a period of time, then
log back in, I can once again drop that mini.

**Comment by cbaggers** [comment]
This should be fixed in the upcoming patch.

**Comment by LuPro** [comment]
Fix is in now, can you confirm if it works for you?

**Comment by gregoryfl** [comment]
Yes, it works. Thank you so much!

Ronen
