### ISSUE TITLE
I've somehow borked it 

### ISSUE THREAD

**Issue by SqueeziestBee** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#742]
**Describe the bug**
Got over excited placing farm animals, delete all but two who now can't be selected in build or normal mode.

**To Reproduce**
1. Place lots of farm animals
2. Make moo noises while moving animals about
3. Realise you are meant to be an adult and delete most of the animals.
4. Permanent Cow'n'Chicken

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![Screenshot 2021-04-15 18 15 05](https://user-images.githubusercontent.com/47105660/114911631-1c3b0b00-9e17-11eb-83aa-16a670c3f91b.png)

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by TheSchnibble** [comment]
This happens when you select another mini while still having one selected.
The one you currently have selected is put down as a permanent (until you reload) mini.
But I'm sure the mooing didn't help. :P

**Comment by LuPro** [comment]
Yeah, seems like the same issue as #592 - I'll close this in favor of the other
