### ISSUE TITLE
Hiding Minis a a GM seems to make them unaccessible

### ISSUE THREAD

**Issue by Stray-Fenris** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#743]
**Describe the bug**
I was trying to make the Minis visible for the players, by using the GM Hide-action and the character kinda dissapeared completely. Retried, made the character unique beforehand and now i can't even place the unique character. Both hidden characters are visible in the Build Menu, but you can't click them

**To Reproduce**
1. Be GM
2. Place a Mini
3. use the "Hide" Option in the Radial Menu
4. the Mini dissappears abd can't be reselected

**Screenshots/Videos/Twitch Clips**
![20210415200901_1](https://user-images.githubusercontent.com/35239511/114917824-ae96db00-9e26-11eb-8c22-e7dc79f03008.jpg)
![20210415200906_1](https://user-images.githubusercontent.com/35239511/114917851-b787ac80-9e26-11eb-90e4-09f78a25475e.jpg)

**Additional context**
Both tried with shrunk Giant. Found out, that the placing of unique Chars could be due to another problem, that was
already reported

**Comment by NocturneShade** [comment]
Hold the Tab button

**Comment by PanoramicPanda** [comment]
You need to be in the GM overlay (press Tab) and also not in Build Mode.
