### ISSUE TITLE
Can't pick a figure

### ISSUE THREAD

**Issue by alaction** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#750]
I tried making a tavern, and added figures while in builb mode. Due to a misclick on the building library (that's on me) I put a mini in a zone where there was no floor. For some reason it managed to be at half floor-high. 
I can no longer pick the figure, even if i place floor under it.

**Comment by LuPro** [comment]
This should be a duplicate of #592, but still thanks for reporting it
