### ISSUE TITLE
Pressing top number row "0" in main menu causes game to lock up momentarily

### ISSUE THREAD

**Issue by McCabe554** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#754]
**Describe the bug**
Pressing top number row "0" in main menu causes game to lock up momentarily

**To Reproduce**
Go to main menu, press top number row "0". this can be in general or in a text box

**Comment by cbaggers** [comment]
Good catch. Thanks for the report.
This is fixed in the next patch :)
