### ISSUE TITLE
Unable to edit health

### ISSUE THREAD

**Issue by GorathMtGiant** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#755]
When right clicking on the character and going to the health wheel I find that there are no longer numbers for hp or max hp

1. set a random characters health to a ridiculous amount

2. then go to another character or place down a new one and ta da invisible health
(^worth while note I am not sure if this was the exact cause but it is the only one I can see^)
![TaleSpire bug image](https://user-images.githubusercontent.com/82616023/114941295-9617c800-9e08-11eb-9986-9d39aedf71a1.PNG)

Also note that this happens to all characters not one individually even to ones originally placed
Another thing by closing and reopening the game this will be undone

Have a nice day

**Comment by cbaggers** [comment]
Thanks for this excellent report. I was able to reproduce this issue exactly with your steps.
I'll have a look at this now :)

**Comment by cbaggers** [comment]
While I'm sure the hp and stats ui will have follow-up issues, this particular issue should be solved.
The fix for this will be in the next patch.
Thanks again for the help!

**Comment by LuPro** [comment]
This should be fixed now, can you confirm?

**Comment by GorathMtGiant** [comment]
Yes it is fixed thank you Sent from Mail for Windows 10 From: LuProSent: Thursday, April 22, 2021 9:44 AMTo: Bouncyrock/TaleSpire-Beta-Public-Issue-TrackerCc: GorathMtGiant; AuthorSubject: Re: [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker] Unable to edit health (#755) This should be fixed now, can you confirm?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
