### ISSUE TITLE
Multi-select creating objects instead of selecting objects.

### ISSUE THREAD

**Issue by Travbot36** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#757]
**Describe the bug**
While using the multi-select tool, objects would be created wherever I tried to select multiple objects. The objects would not be selected and the objects that were created by the tool are impossible to remove from the map. 

**To Reproduce**
1. Start new map
2. Enter build mode
3. Activate the multi-select tool
4. Select any area
5. Box will be created and items will not be selected. 

**Screenshots/Videos/Twitch Clips**
![20210415182023_1](https://user-images.githubusercontent.com/82619992/114950151-172a8b80-9e18-11eb-96c5-9c770241b686.jpg)
![20210415182030_1](https://user-images.githubusercontent.com/82619992/114950154-185bb880-9e18-11eb-8564-6a0e3416f942.jpg)
![20210415182031_1](https://user-images.githubusercontent.com/82619992/114950155-185bb880-9e18-11eb-8a26-a28c9ea11ea4.jpg)

**Additional context**

**Comment by LuPro** [comment]
Did you accidentally assign a key to the fog of war option in the 2nd tab in the settings? These boxes are the experimental fog of war volumes - you can get rid of them by placing down a mini, assigning yourself to them in the right click menu and moving it around. It would be very interesting to know if there's a bug that assigns the keybinds or if you accidentally pressed on it :)

**Comment by Travbot36** [comment]
> Did you accidentally assign a key to the fog of war option in the 2nd tab in the settings? These boxes are the experimental fog of war volumes - you can get rid of them by placing down a mini, assigning yourself to them in the right click menu and moving it around. It would be very interesting to know if there's a bug that assigns the keybinds or if you accidentally pressed on it :)

This was the exact issue! Thank you very much. Not sure how I managed to bind that key...
