### ISSUE TITLE
Able to grab tiles hidden by cut-off plane

### ISSUE THREAD

**Issue by Fesmaster** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#758]
When some tiles (above others) are hidden due to zoom and the green height hider slider, they can sometimes still be grabbed in build mode. 

From the behavior, it looks as if the test for if a tile should be grabbed relies on direct distance from camera, while the visibility check relies on the vertical level. Though this might not be the case, as I have some areas that I cannot ever select the lower level of tiles when there is an upper level above it.

https://user-images.githubusercontent.com/21015354/114952595-945bfd80-9e24-11eb-9087-197881a5c289.mp4

**Comment by LuPro** [comment]
I've seen this report come up a few times already, but I am unable to reproduce it - could you publish the board and send the link here, maybe it has something to do with what was placed?

**Comment by Fesmaster** [comment]
I believe this is correctly published
talespire://published-board/VGF2ZXJhbg==/0b827df24db7eb940cc205a03b88e20c

**Comment by LuPro** [comment]
This should be fixed now, can you please check and confirm? You may need to move the tiles around a bit (that was how the bug was triggered before)

**Comment by Fesmaster** [comment]
It seems to be fixed! I was unable to reproduce it, on the same board and on a new one. Thanks for the fast fix! I am very impressed with you and TaleSpire!
