### ISSUE TITLE
NullReferenceException occurs when viewing Attacking video Tutorial

### ISSUE THREAD

**Issue by eghager** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#760]
When opening and viewing the "Attacking" tutorial under the "Playing" section, a NullRef error occurs. 

This error doesn't seem to cause any visual issues as the video still plays but the error happens regardless. 

**Error:**
`NullReferenceException: Object reference not set to an instance of an object
UITutorialDisplay+VideoLoader.BundleRequestOncompleted (UnityEngine.AsyncOperation obj) (at <14b4979c5fbb44ffa18d85caa9bbf81a>:0)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at eaed1887017646508aa3fd7a8edf50d6>:0)`

`Failed to read data for the AssetBundle 'E:\Steam\steamapps\common\TaleSpire\Taleweaver\Tutorials\tutorial_playing_attacking'.`

**Repro Steps:**

1. Create and open a new board
2. Within the board open the Tutorials menu
3. Navigate to "Playing" 
4. Open the "Attacking" tutorial
5. Observe NullRef error occurs 

Expected Result:
NullRef error does not occur when viewing Attacking tutorial. 

![NullRefAttackBug](https://user-images.githubusercontent.com/59941582/114955742-57dfd000-9e2b-11eb-91b6-e430aa2e7f8d.png)

Please let me know if more info is required :). 
Note: I'm a software tester as well so hopefully I can help find more bugs!

**Comment by eghager** [comment]
This also occurs with Hide/Reveal Minis tutorial as well.

**Comment by LuPro** [comment]
This should be fixed with the latest update, can you confirm?

**Comment by eghager** [comment]
Just checked, the issue no longer repros, verified fixed! Checked all of the tutorials as well and no errors occurred.
