### ISSUE TITLE
Unable to move/manipulate multiselection

### ISSUE THREAD

**Issue by ktcoup** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#761]
I can make a multiselection in build mode, but can't do anything with said multiselection. At first, I thought it was user error, but after going through the demos and tutorials, I realized it wasn't. The only thing I am able to do with a multiselect is deselect.

**Comment by LuPro** [comment]
You can press "delete" to... delete, or ctrl + x to remove and copy, ctrl + c and ctrl + c to copy.
The tutorials unfortunately don't cover everything yet.
