### ISSUE TITLE
"Ghost" Minis

### ISSUE THREAD

**Issue by xcasino** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#762]
**Description**
When placing minis on the board, if you place a mini and then (Without hitting "ESC") select another mini from the library, this will then place a "ghost" mini that can't be interacted with. Only way I can fix this is "Exit to Main Menu" and reload the campaign, even reloading the board doesn't seem to help although I haven't tested loading into another board first then swapping back (I would assume this would work as well.)

**Reproduce**
1. Select Mini from Library and place mini on board
2. Without hitting "ESC" select a new mini from the library.
3. This will place a "ghost" mini that can be interacted with.

**Screenshots**
As you can see there are quite a few minis in the wall and such those are the "ghost" minis as well as some on the ground level too:
![image](https://user-images.githubusercontent.com/5254073/114956918-e5242400-9e2d-11eb-91b5-73b86e0fbefd.png)

**Additional context**
Screenshots don't really show this very well unfortunately but this hasn't been a big issue only a minor annoyance with the minis as this behavior doesn't seem to exist with props or walls from what I have been able to experience and a "Exit to Main Menu" and reloading the campaign is a workaround for now.

**Comment by LuPro** [comment]
This has been logged as #592 already, but thanks for the report :)
