### ISSUE TITLE
You can "clone" a creature, and then it can't be manipulated

### ISSUE THREAD

**Issue by UhDaTank** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#765]
**Description**

It's possible to "clone" a creature. This "clone" cannot be manipulated in anyway as far as I can tell, including being unable to delete it.

**To Reproduce**

*1.* Grab any creature from the library.
*2.* While holding the selected creature, move your mouse down into the library tray.
*3.* Left click on any creature in the library tree.
*4.* There will now be a "cloned" creature on the board that you cannot move or otherwise interact with.

**Here's your weight in gold**

![InstantGif_2021 04 15-22 27](https://user-images.githubusercontent.com/82625836/114963081-f1ae7980-9e39-11eb-8b1c-c4d445e43477.gif)

![Bug](https://user-images.githubusercontent.com/82625836/114963300-70a3b200-9e3a-11eb-890c-c7face1d948c.png)

**Additional context**

I love this tool so much. It's really great for us GM's that don't have a lot of free time, but still want to do right by our players! Keep up the good work.

**Comment by cbaggers** [comment]
Wow, what a great report. Thank you. I'll go try this out now

**Comment by cbaggers** [comment]
Excellent. I havent managed to click the ui while holding the creature (how did you do that?) but I replicated it by click the UI while using the keyboard controls.

The think i've found should be an easy fix. Hopefully it's the same bug you are seeing

**Comment by cbaggers** [comment]
Fixed it. Thanks again for the report. This will be out in the next patch

**Comment by LuPro** [comment]
Should the same as #592, so that would probably also be fixed

**Comment by LuPro** [comment]
Should be fixed in the latest update, can you confirm?
