### ISSUE TITLE
Help Text Incorrect - Teleport Mini

### ISSUE THREAD

**Issue by PhilosophasterDC** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#767]
**Describe the bug**
I found that the controls listed in the helper bar while hovering over a mini shows "X + Left-Click" to teleport, but it is supposed to be "Shift + Left-Click".

**To Reproduce**
1. Place a Mini
2. Hover over it
3. Look at the help bar at the bottom of the screen

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/17963816/114963746-646c2480-9e3b-11eb-8d16-f55bc267ecd1.png)

![image](https://user-images.githubusercontent.com/17963816/114963659-3ab2fd80-9e3b-11eb-94ba-7c59ea04f0c0.png)

**Additional context**
Appears to happen on all mini's of all sizes.

**Comment by cbaggers** [comment]
Good catch! I can confirm this on my end too.

**Comment by cbaggers** [comment]
The fix for this will be in the next patch

**Comment by LuPro** [comment]
Should be correct now, can you confirm?
