### ISSUE TITLE
Infinite loading on title.

### ISSUE THREAD

**Issue by Farathil** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#769]
**Describe the bug**
First time trying to start up Talespire had infinite load time (Settings works, music is working, just the hourglass spinning). Tried restarting it several times after checking online. Got the same results, except one time I got some errors (link 1). I verified the program on steam, and reinstalled.

**To Reproduce**
1. Start game

**Screenshots/Videos/Twitch Clips**
[Only time I got errors](https://i.imgur.com/M61B1Qn.png)
[Every other time.](https://i.imgur.com/7sh1HXF.png)

**Additional context**
It seems like it might figure itself out from what some of the other bug submitters said, but figured the error report was important.

**Comment by LuPro** [comment]
Are you connecting with a VPN or on a corporate/university network? Those are known to sometimes cause troubles

**Comment by Farathil** [comment]
Not a VPN, but university network. However it seems pretty lax with p2p working but things like SMB (network file share) not working. 
Never had any issues with anything regarding server communication, or games though.

**Comment by LuPro** [comment]
Very interesting. TaleSpire could definitely handle some weird network setups better, but it's unfortunately rather hard to find the issue without being able to recreate it 😅 
Could you try going through a VPN (to circumvent the university network) and see if that works, it did for some people in the past. If it does, it'd be great if you could let me know - it's definitely a bug worth investigating and I'd be interested if this is really the cause

**Comment by Farathil** [comment]
It seems todays patch might have fixed it just now, was about to test it with proton, would have liked to have known that as well.
