### ISSUE TITLE
Indefinitely Loading Screens and many red console "things"?

### ISSUE THREAD

**Issue by Katangorn** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#779]
**Describe the bug**
When i do try to create a board or to leave one, it just keeps loading indefinetely, also, when i'm trying to leave the board and try to exit the game, it doens't answer my commands

**To Reproduce**
Listed above, nothing much specific

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/82655019/115019975-47157580-9e90-11eb-9a03-5361d745d138.png)
![image](https://user-images.githubusercontent.com/82655019/115020248-b2f7de00-9e90-11eb-8013-3537027a8dd2.png)
![image](https://user-images.githubusercontent.com/82655019/115020343-dae74180-9e90-11eb-91e7-1388b15b41e3.png)
![image](https://user-images.githubusercontent.com/82655019/115020365-e20e4f80-9e90-11eb-9e21-9bf3b1361022.png)
![image](https://user-images.githubusercontent.com/82655019/115020397-eb97b780-9e90-11eb-88e0-ad81c780786b.png)
![image](https://user-images.githubusercontent.com/82655019/115020419-f18d9880-9e90-11eb-8fdb-2d66ec998e6b.png)

**Additional context**
I have a pc meeting the minimum requirements only (i guess)
Here is my Talespire player and player-prev files
 
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6324730/Player.log)
[Player-prev.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6324731/Player-prev.log)

**Comment by LuPro** [comment]
could you try verifying the game files on steam and see if that's fixes it? also if it's an old pc it'd be interesting to know the exact hardware for better diagnosis

**Comment by Gideon-Lord** [comment]
I have the same issue with my laptop (im getting a new gaming pc soon but using a low end laptop for time being) the specs meet the minimum system requirments but i get the same errors. My specs are -
OS - Windows 10
Processor - Intel Core i3-2310M
Graphics - Intel HD 3000
Memory - 4GB RAM

I know its probably due to being minimum pass whereas 8GB RAM would make it the recommended

**Comment by Gideon-Lord** [comment]
if it helps im running it on all the lowest settings too

**Comment by Gideon-Lord** [comment]
i verified the files on steam like you suggested and re-loaded talespire with the same issue

**Comment by jpentropia** [comment]
i have the same problem, my pc has almost the same configuration, the only thing different is the 8gb of RAM.
![Capture001](https://user-images.githubusercontent.com/82675627/115069038-6c72a580-9ec9-11eb-89ec-8b9c578fa502.png)

**Comment by Gideon-Lord** [comment]
i think it may be my GPU, i looked at the player.log and it said something about the GPU wasnt good enough for shdaers etc, even though it should be good enough for minimum requirements.
[Player-prev - Copy.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6328054/Player-prev.-.Copy.log)

**Comment by LuPro** [comment]
Could you check for me what DirectX version your integrated GPU supports?

To find this out, press the windows key + r, a window should open like this:
![image](https://user-images.githubusercontent.com/20774976/115096065-f8192000-9f23-11eb-9691-91679c575a21.png)

enter "dxdiag" in this window, then press enter. Windows may ask you about needing to connect to the internet, accept that. After this you should have a window like this:
![image](https://user-images.githubusercontent.com/20774976/115096113-2a2a8200-9f24-11eb-8f3f-7e41cc00bb9d.png)
In the bottom most row of the central "info panel" there is the line "DirectX Version", In my case it says DirectX 12, the game needs at least the version 11.0

PS: Looking at the log it seems your chips only support DirectX 10.1 which is unfortunately below the minimum specs for the game - make sure by still checking the dxdiag, but I think it's just a bit too old at this point :(

**Comment by Gideon-Lord** [comment]
![image](https://user-images.githubusercontent.com/82661004/115097150-678d1080-9f20-11eb-91ac-d41d92282ce6.png)

**Comment by Gideon-Lord** [comment]
nope says i have DirectX 12....from what i read it says my GPU doesnt support shaders etc (not that i know what that means lol) but i assume m intergrated graphics just isnt enough

**Comment by LuPro** [comment]
That is odd, it says Dx12, but that is not possible, the CPU came out before DirectX 12 😅 
I'll take a look at what the issue here may be, give me a few minutes :)

**Comment by Gideon-Lord** [comment]
![image](https://user-images.githubusercontent.com/82661004/115097222-cb173e00-9f20-11eb-8d36-0d6da7db2267.png)

**Comment by LuPro** [comment]
Ah! Just wanted to ask for the "display" section
There on the right it says "Direct3D DDI: 11.1" and "Feature Levels: ..."
The GPU needs up to feature level 11_1, but only supports 10_1 and below unfortunately

**Comment by Gideon-Lord** [comment]
so basially intergrated graphics is just under whats required, just my luck, thanks for looking into this for me, ill have it on pc soon enough so dont worry you havent lost me :D

**Comment by LuPro** [comment]
That's great to hear, would be sad if something stupid like this would be a permanent block - though at this point the CPU/integrated GPU is practically ancient, I'm surprised it survived this long 😅 
Thanks for the quick answers and hope your PC treats you better than this laptop chip :P

**Comment by Katangorn** [comment]
> That's great to hear, would be sad if something stupid like this would be a permanent block - though at this point the CPU/integrated GPU is practically ancient, I'm surprised it survived this long 😅
> Thanks for the quick answers and hope your PC treats you better than this laptop chip :P

Hum, so do i fit on the same problem too?
![image](https://user-images.githubusercontent.com/82655019/115119882-ff224b80-9f80-11eb-9055-d160947c3318.png)

![image](https://user-images.githubusercontent.com/82655019/115119893-0a757700-9f81-11eb-8d74-22556ecdc941.png)

If that's the case, what should i change on my pc? (minimum requirement?)

**Comment by LuPro** [comment]
You'd probably need to add a new graphics card, it's the same underlying issue - your integrated graphics in the CPU only supports directx feature level up to 10_1, but needs up to 11_0.
I am not entirely sure the CPU has enough performance to play TaleSpire *well*, but I *think* it should be fine, at least for smaller maps, and while you don't have a ton of RAM it should suffice as well. The biggest issue for you is definitely the graphics card, however those are hard to get in recent times :/
