### ISSUE TITLE
Spelling error in Grid interface

### ISSUE THREAD

**Issue by spetsdod** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#784]
**Describe the bug**
There is a spelling error in the grid interface.

**To Reproduce**
1. Enter Build mode
2. Press 'G' to open grid options
3. Mouse hover over sample grid options
4. See "Sample Height for Gird" <-- should be Grid, I assume?

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/13544170/115045436-f8adaa00-9e82-11eb-962e-ffe88c9ab173.png)

**Comment by cbaggers** [comment]
Good catch! Thanks for the report. 
This will be fixed in the next patch
