### ISSUE TITLE
The single standing lantern

### ISSUE THREAD

**Issue by persgorilla** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#789]
**Describe the bug**
I can't get the single standing lantern to work.

**To Reproduce**
1. Put single standing lantern on board.

![image](https://user-images.githubusercontent.com/82684728/115093941-1c034400-9ed9-11eb-91b2-e66a710b98e2.png)

**Comment by LuPro** [comment]
Duplicate of #648
