### ISSUE TITLE
Tile Size (Ruler Scale) do not accept float/decimal values

### ISSUE THREAD

**Issue by jawwadbr** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#792]
**Describe the bug**
When you change de tile size in Campaign & Board Settings in World Units to some value like 1,5 or 2,5 it does not work. I play DnD 5E in Brazil so we use Meters, for every 5 Feet is 1.5 meters. I want to change the tile size for 1,5 so we can use Rulers and calculate distance but when we change to 1,5 it just say 1. I tested more and put 2,5 and the tile size instead of saying 2,5 say 1. And I cannot put 1.5 but only 1,5 and does not work.

**To Reproduce**
1. Change Tile size to a value with decimal (Like 1.5 or 2.5)
2. Use ruler to see distance and it will say 1 and not the value you putted 

**Screenshots/Videos/Twitch Clips**
https://prnt.sc/11jtr58
![TalespireRulers](https://user-images.githubusercontent.com/37093842/115098309-c42f0200-9f05-11eb-9bef-e787e5d2eec4.jpg)

**Additional context**
Because all of this I think Tile Size don't work with decimal numbers

**Comment by jawwadbr** [comment]
Apparently some people can use decimals
![dVe04jH](https://user-images.githubusercontent.com/37093842/115099055-ef1b5500-9f09-11eb-84d7-eff2d259bcd5.png)

Me and my friend are having issues with this but a random user from Steam send me this picture showing him with no problem. So it won't be everybody with this problem. Hoping that somehow this gets fixed.

**Comment by McCabe554** [comment]
Another user has just had this same issue, their system language seems to be Spanish, I'm wondering if this has to do with decimals being handled differently in different languages, such as using 1,5 instead of 1.5. Note this issue does seem to stop the user inputting either of those options.

**Comment by jawwadbr** [comment]
> Another user has just had this same issue, their system language seems to be Spanish, I'm wondering if this has to do with decimals being handled differently in different languages, such as using 1,5 instead of 1.5. Note this issue does seem to stop the user inputting either of those options.

Uhmm, thats a good point, I use Brazilian Portuguese, I'll try to put it in English and see what happens

**Comment by jawwadbr** [comment]
> Another user has just had this same issue, their system language seems to be Spanish, I'm wondering if this has to do with decimals being handled differently in different languages, such as using 1,5 instead of 1.5. Note this issue does seem to stop the user inputting either of those options.

You are absolutely correct, I changed my system language to English and now I can input 1.5 in the tile size, and not 1,5. But its working.

![Capture](https://user-images.githubusercontent.com/37093842/115128271-f34f7d00-9fb2-11eb-9109-6bb110b9d7f5.JPG)

**Comment by cbaggers** [comment]
I have probably made some other mistakes but I've had a first go at supporting the current culture setting with rulers.
I was able to set Windows to french, edit the tile size using the comma as the decimal point and get the expected result in the measurement.

This change will be in the next patch

![image](https://user-images.githubusercontent.com/1579326/115643010-43647180-a31c-11eb-86dd-a2fe6416223a.png)

**Comment by LuPro** [comment]
Should be in now, can someone who's affected confirm?

**Comment by jawwadbr** [comment]
> Should be in now, can someone who's affected confirm?

For me It's working as intended now in Windows with Brazilian Portuguese.
