### ISSUE TITLE
Beds disappear when placed.

### ISSUE THREAD

**Issue by riceballdono** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#796]
When beds are placed down they disappear and leave their shadows only. Rotating doesn't help any and it seems to stay this way even after relaoding Talespire

https://user-images.githubusercontent.com/82698488/115105099-5d6c1180-9f22-11eb-965a-aee550e2b91f.mp4

**Comment by cbaggers** [comment]
That is bizarre! Thanks for the report.

**Comment by cbaggers** [comment]
Now I look at it, I can see that the build plane is above the hide plane. So my guess is that the game is actually place the beds a little higher, which leaves the mystery: why is it showing the preview against the tiles?

**Comment by cbaggers** [comment]
I've been able to replicate this. There is definitely positions you can put the hide-plane which shows the floor and walls but not the objects in the room. This is not strictly a bug, although it's a little tricky to see what was happening.

The solution in this case is to drag the green hide-plane indicator up until the beds become visible. 

![image](https://user-images.githubusercontent.com/1579326/115715907-e64ad900-a378-11eb-88ba-2889644a6f2b.png)

I hope this helps!
