### ISSUE TITLE
Shift+WASD gets lost with camera

### ISSUE THREAD

**Issue by LegendaryParadox** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#80]
**Describe the bug**
I expect the camera to stay centered on the mini I am moving with Shift+WASD. 

**To Reproduce**
1. Select mini
2. If I use Shift+D (for example)
3. the camera moves the direction of the mini, but further than the mini moved

**Screenshots/Videos/Twitch Clips**
not needed, simple reproduction

**Comment by Chorcon** [comment]
Additionally, if your mini is bouncing into a wall (so it's not changing positions), the camera still moves.

**Comment by LuPro** [comment]
This has been fixed. Though there are still issues regarding minis walking into walls, none of them are camera related at least.
