### ISSUE TITLE
Killing the mini whose turn it is also temporarily empties initiative list

### ISSUE THREAD

**Issue by PanoramicPanda** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#802]
**Describe the bug**
Had a few minis in combat, killed the one who was taking their turn (Attack of Opportunity death)

**To Reproduce**
1. Put a few minis down
2. Put them in the initiative tracker
3. Kill the mini whose turn it is

**Screenshots/Videos/Twitch Clips**
https://imgur.com/a/CEjdAHm

**Comment by cbaggers** [comment]
I've been able to replicate this. Looking into it now

**Comment by cbaggers** [comment]
Found the issue :) The fix will be in the next patch

**Comment by PanoramicPanda** [comment]
Fixed. New issue though XD (opening shortly)
