### ISSUE TITLE
GM Marker blocks not persistent

### ISSUE THREAD

**Issue by MoacirCudePato** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#807]
EVERY TIME I CREATE A "PLACE MARKER BLOCK" IT IS DELETED WHENEVER I LOGOUT / LOGIN ON THE BOARD. AND I NEED ADD ALL AGAIN.

**Comment by LuPro** [comment]
This is the first time I'm seeing a report like this, could you maybe make some screenshots/video of this happening? Like showing the GM view with the marker blocks, the normal view without and then the same after reloading?

**Comment by MoacirCudePato** [comment]
This first screenshot i create a PLACE MARKER BLOCK

![image](https://user-images.githubusercontent.com/82739166/115132398-2eaf7300-9fd6-11eb-9e42-000d3c6c177b.png)

And this second screenshot i just exit to main menu, and login back to de board, and it is just gone

![image](https://user-images.githubusercontent.com/82739166/115132455-9d8ccc00-9fd6-11eb-91c5-fa7d800f2d96.png)

**Comment by martin-jw** [comment]
I am getting this as well, it's really annoying, essentially making GM markers useless since they don't even stay between switching boards.

**Comment by LuPro** [comment]
This should be fixed in the latest patch, can you confirm?

**Comment by MoacirCudePato** [comment]
Yes man, it's fixed. Thnks for attention. And congratulations for TaleSpire, it's just amazing!!!!
