### ISSUE TITLE
Black Boxes

### ISSUE THREAD

**Issue by MoonMan24** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#812]
**Describe the bug**
Black Box replaces the multiselect clear dotted box. I do see the dotted line box beforehand, and it fits the exact size. Also can reappear on different boards when loading in. It also reflects the build light off the box and others can see it. When using the miultiselect the blocks do jump up when highlighted. It also does not appear in picture mode. I can create these boxes in other people's campaigns and they cannot be interacted with and remain after I leave. Other players can still use multiselect as usual even though mine doesn't work. If you have more question I can respond, new to github though so I don't know if that's a thing.

![Bug Report Picture](https://user-images.githubusercontent.com/82750244/115138053-a386ab00-9fde-11eb-9531-37050afe3543.PNG)

**To Reproduce**
1. Use multiselect
2. left clicking will create the box instantly
3. Right clicking will create nothing but if you click the multiselect button again it will make the black box.

**Screenshots/Videos/Twitch Clips**

The picture I have attached is an example of this with the build light on. It still is there even without the build light. This is in my own personal test campaign. Sorry for double posting the picture I do not know how to delete. New to Github

**Additional context**

Plz help, want to build a lot but no copy paste because multiselect is now black box simulator.

**Comment by LuPro** [comment]
It seems you accidentally set the experimental fog of war feature. Can you check the settings for that in the second settings tab?

**Comment by MoonMan24** [comment]
Yup... you're right.... it was set to left mouse button. Thank you! I really appreciate it!
