### ISSUE TITLE
Connecting to region server

### ISSUE THREAD

**Issue by TorishimaEve** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#814]
Was supposed to connect to a server to start my own campaign and it doesn't connect.

**To Reproduce**
1. Create name for campaign
2. Game searches for server to connect.
3. fails to connect & brought back to create campaign screen.

![talespire connection](https://user-images.githubusercontent.com/82767409/115151489-145bb080-a03b-11eb-9b32-6b2b7a8f85df.jpg)

I can connect to a friends campaign that lives in the same region of the US as I do (south east, different state) just fine but I can't start my own.... if it was an internet connection issue, I dont think i would of been able to connect to his game to edit as gm.

**Comment by TorishimaEve** [comment]
just fyi.. i've already checked my antivirus/vpn and windows settings.

**Comment by LuPro** [comment]
Are you on a corporate/university network? They sometimes cause issues (sometimes going through a VPN can help with connection problems).

**Comment by TorishimaEve** [comment]
no its a private network.

**Comment by TorishimaEve** [comment]
its now working. thanks to the creators for the bug fixes.. :D much love to ya!!
