### ISSUE TITLE
The GM can't seem remove all the dice from the board anymore

### ISSUE THREAD

**Issue by PrezWaste** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#815]
**Describe the bug**
Whenever the GM attempts to remove the dice on the board by right-clicking and using the GM function to remove all the dice at the same time. It's function doesnt work anymore it seems like. It used to work, but doesn't anymore

**To Reproduce**
1. Throw out a lot of dice on the board
2. Right-click on one of them as a GM
3. Attempt to remove them by using the GM function to remove them all
4. Nothing happens

**Screenshots/Videos/Twitch Clips**
None

**Additional context**
It happens in both the game I DM and the games I'm a player in, so seems to be a re-occuring issue!

**Comment by LuPro** [comment]
Should be fixed now, can you confirm?

**Comment by PrezWaste** [comment]
> Should be fixed now, can you confirm?

I can confirm that the issue seems to be fixed! It works! 
Thanks a bunch to the team!

**Comment by dudu631** [comment]
Also confirmed that it's fixed. Thanks!
