### ISSUE TITLE
Roof tiles bug?

### ISSUE THREAD

**Issue by tincho-sudo** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#817]
**Describe the bug**
Roof tiles have a strange infinitely long brown plank ?

![image](https://user-images.githubusercontent.com/62819585/115157928-26047e80-a062-11eb-9c91-e5773b938f67.png)

![image](https://user-images.githubusercontent.com/62819585/115158010-7976cc80-a062-11eb-9984-329c03ad8f23.png)

![image](https://user-images.githubusercontent.com/62819585/115158043-a925d480-a062-11eb-9409-a16d860ebb82.png)

**Additional context**
Sorry about the steps, couldnt figure it out how to reproduce it.  (tried to make some mini roofs, but it didnt happen there)
Gpu is 3060 12gb if its worth something
Please ignore windows activation message lol

**Comment by LuPro** [comment]
Unable to reproduce - could you verify your game files on steam please, maybe the asset file got corrupted.

**Comment by tincho-sudo** [comment]
> Unable to reproduce - could you verify your game files on steam please, maybe the asset file got corrupted.

It didnt download anything and got the "all files verified correctly" message. Seems fixed by now, but will notify if it happens again. Thanks !
