### ISSUE TITLE
Not saving my progress!

### ISSUE THREAD

**Issue by Lantel12** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#82]
**Describe the bug**
I finished up some work on a test map, a tavern with some greenery and an apple field. I had logged off and on twice before this, and felt accomplished with my work. I decided to restart the game and show it off to a friend through streaming, but when I had returned the game had only saved my progress up to the point where I had logged previously, effectively erasing 3 hours of my work on the map.

**To Reproduce**
All I did was quit to desktop after I finished all my work instead of going to the main menu. I can only guess that might be where the issue was.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
Second Time I logged on: 
![image](https://user-images.githubusercontent.com/63480686/79029760-cd9fc480-7b63-11ea-8a50-14b010a705be.png)
![image](https://user-images.githubusercontent.com/63480686/79029766-d395a580-7b63-11ea-91ff-fcabe52ed6f3.png)
![image](https://user-images.githubusercontent.com/63480686/79029769-d7292c80-7b63-11ea-9c18-cd7f38c35317.png)
![image](https://user-images.githubusercontent.com/63480686/79029773-db554a00-7b63-11ea-8691-64d07e11a169.png)
Third time I logged on:
https://gyazo.com/38af78138eece9e280b339d6a444bc56
![image](https://user-images.githubusercontent.com/63480686/79029792-f0ca7400-7b63-11ea-9916-967e1b9afbcc.png)
https://gyazo.com/18393fdd3f45c8cf5e5009ddb1d87d30
**Additional context**
I am not bothered, it's a beta after all! That being said, I was proud of what I had built. It had, at the very least, informed me for future building. Thank you for your time, and I hope this helps!

**Comment by WarBrute88** [comment]
I am having a similar issue.
![image](https://user-images.githubusercontent.com/63480914/79030037-53b40f00-7b54-11ea-907a-dadf7cfbc5bd.png)

**Comment by musiconator** [comment]
Same here. I did just finished a dungeon level, went out to the main menu and when returned almost 1h of work was gone.

How often does it autosave, does it after every action? And does it save it online or on the PC?

**Comment by LuPro** [comment]
It *should* autosave 5 seconds after every board change, but as of right now there are bugs with that

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
