### ISSUE TITLE
Blue Glowing Treasure Chest collision box remains after being deleted.

### ISSUE THREAD

**Issue by zorum24** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#823]
When you delete the ornate blue glowing chest it does not delete the collision box. Seems that the chest bugs out if deleted while it's open or possibly if it's oriented a certain way. I was able to preproduce the bug but not consistently.

1. Place chest
2. Open Chest
2. Delete chest
3. Collision remains

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/44488349/115189724-2cb3e580-a0a4-11eb-91ec-8c79d9b321d0.png)
![image](https://user-images.githubusercontent.com/44488349/115189732-31789980-a0a4-11eb-863f-ef4f6701c570.png)

**Comment by cbaggers** [comment]
Fantastic find! This has been annoying me for ages as I only ever saw it randomly. 
I'll dig into this now

**Comment by LuPro** [comment]
Should be fixed now, could you confirm?
