### ISSUE TITLE
copy and paste tool bug

### ISSUE THREAD

**Issue by HorusF10** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#826]
When I select the copy and paste tool, an opaque black box appears that does not allow me to do any more action with what was in place, it is not possible to delete or return the action to cancel the box.

![image](https://user-images.githubusercontent.com/82850560/115317667-73601900-a152-11eb-886c-0f2549fa2ff6.png)

![image](https://user-images.githubusercontent.com/82850560/115317697-85da5280-a152-11eb-8445-6c4eb999ccd4.png)

**Comment by HorusF10** [comment]
I found out that in the settings an option was checked, when deselecting it returned to normal

**Comment by LuPro** [comment]
Yeah, it seems you accidentally set a button to the experimental fog of war - it can be removed with the remove keybind or by assigning a creature to yourself (or another player) and moving through it
