### ISSUE TITLE
2x2 hatch ignores mini collision

### ISSUE THREAD

**Issue by pyrestriker** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#827]
**Describe the bug**
The 2x2 hatch ignores minis, so they fall straight through unless the mini is on the rope handles.

**To Reproduce**
1. Place a 2x2 hatch
2. Place a mini
3. Move the mini onto the hatch
4. The mini falls through.

**Screenshots/Videos/Twitch Clips**
https://youtu.be/mt9_9FSpfvg

**Comment by cbaggers** [comment]
Oh my, this definitely shows the worst case of the collider math issues yet :D

Thanks for the report. I adore how few pieces I needed to show this issue!

**Comment by cbaggers** [comment]
This one is fascinating actually. It seems that it is using the wrong colliders for the doors. This one is going to be exciting

**Comment by cbaggers** [comment]
I was :facepalm:. This is fixed in the next patch

**Comment by LuPro** [comment]
Should be fixed now, could you confirm?

**Comment by pyrestriker** [comment]
We good!
