### ISSUE TITLE
Cannot rotate selected object with middle button/scrollwheel

### ISSUE THREAD

**Issue by DickyB2013** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#828]
Cannot rotate objects with middle button/scroll wheel. Map is rotated, not object

Expected object to rotate, instead map rotated and object kept same orientation with the map

**To Reproduce**
Select a wall tile
Try to rotate from default orientation by press and hold scroll wheel
Map rotates, not object

**Comment by LuPro** [comment]
You don't have to press and hold to rotate an object, but *click* alternatively you can also hold the Alt key and move the mouse to rotate. Please tell me if that works for you :)

**Comment by DickyB2013** [comment]
Thanks - when you say 'click' do you mean single click of the middle button?
If so, then no, it doesn't work
But ALT does, so I have a solution😉

Thanks for the quick response

________________________________

**Comment by LuPro** [comment]
Yes, a single click should work for rotating - but I think only while you have the tile "in the hand".
