### ISSUE TITLE
Rebinding "Rotate 90 degree" to a custom key only works for single tiles, not group selections

### ISSUE THREAD

**Issue by Ja07sj** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#829]
**Describe the bug**
If you change "rotate 90 degrees" off of middle mouse button to a different key,  you can use your custom key to rotate single tiles, but if you want to rotate a group selection it will default back to middle mouse button.

**To Reproduce**
Just rebind "rotate 90 degrees" to a different button, then try to select a group of tiles.  Your custom button won't worked, but middle mouse will.

**Comment by cbaggers** [comment]
Thanks for the report. I've confirmed this issue and hopefully fixed it. I'm going to get it double checked as I didnt write this part of the game. 
If all goes well then this will be in the next patch

**Comment by LuPro** [comment]
Should be fixed now, could you confirm?
