### ISSUE TITLE
Hide plane slider deletes a line of constructed area

### ISSUE THREAD

**Issue by dutoito** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#833]
**Describe the bug**
While I was building the second floor and roof of a build I noticed that by adjusting the hide plane slider eventually a staight line of objects would disappear, sometimes it would just pop back up. But most of the times I'd have to rebuild it again.

**To Reproduce**
1. Build a multi level house or something similar
2. Continue to build and rotate the camera inside and out while adjusting the hide plane slider
3. It will probbably delete something in a straight line.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/82909834/115464503-90a0f000-a203-11eb-86cb-9add4d384ff7.png)

**Additional context**
I initially thought it was something with the way I positioned my camera, but then I realized the objects really did disappear, so I had to build it again. 

Finally, I would like to say I really enjoy playing this game, it sure has a great future, so keep up the awesome work!

**Comment by LuPro** [comment]
Could this be the same as #577 or more like #809?

**Comment by cjfoye** [comment]
I was able to capture this bug in a video, but it is too large to post here (only 40 seconds long, but 48 MB).  It seems to get fixed if you adjust the hide plane slider while focusing the camera on the missing piece.

**Comment by LuPro** [comment]
Okay, to me that sounds like #577, so I'd refer to that issue for this.
