### ISSUE TITLE
Invisible furniture objects are still interactable

### ISSUE THREAD

**Issue by mrotondo** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#837]
While in build mode, moving the hide plane to hide furniture objects does not prevent them from being grabbed and moved. For example, I build a multi-story tavern with bedrooms on the second floor and a bar on the first floor, and when I moved the hide plane down to show only the first floor to try to move some tables around, I kept grabbing objects (beds, desks) from the (hidden) second floor instead.

```H4sIAAAAAAAAC02We1xUxxXHZ/feu7siBk18lESbrYmaIL629iPGZl2WBZULKKIuEoyrXiNB1Eulsmq3ueKjkGiyKBAQUVipaDBhEzESiLJWk/ixPtZY+dBgolUra0ISbLU++Bg7Z+aY+Nfv8z0zZ+6ZM2fO3DP3z5zTkwmEkL6+Y7qekl2OzVMqrF9Zc4dXUpulqUlyXqtLKbww7L5DeGOiSG2h8cMNQ6pXxPrinyno3G0YoaO2a0tiwsduzrRvjWscOsDT8gBsX69fFt6gC9gPiyVFv2msbBeorfHQ9/2yWhbFF66dE9blPRgF8zp7Jj217Gbr9PKYusycv8ulYHu9c+GA5JY34j7qzntz8I0f6sH27eiFY35K22gvvPJB4MT879+AWIT/HB2jnzA89i/580sMa8KrnqA2bX1aTOffOlMKZtrX+cKu3gbfV0cPean5Uo3cGOaccu5PM2/rqe1JMWxSzuiJsXX/vp2bnznqdZg3OSP15cPhlfaqhTWGQ0V1vftR27SH9Y6Bq59MabZNWxy+yZIG81o/PjlLPivGl34zrlg4lb0IbPl97bP/MGfUtLJeRUd67n1XZaS2lHfCsuTsktgjX8UuvXp8/xQDtU24l5Bd6/gwrly5c+7ogP4nwffs+kva6UOpyc1JVeNzt3z0NdiiQ7aCxZ/Pm767+Fh326AVIbD9c7K/oOfpyQm7744Za05evABy+mNz/ps3FsxNLC1WL/g/v9kGe7vT0bv40mBdwtbtO4o++3bvEfDd9NyarW3KdvsBd0GrFNXnfF9qi3TlV9a6w6bXH+4otve5bxxAbQduHav2WYYk1Ytp37k3fHgT1ovMW1W34IMOe4nyxZwHu+52gs1S+cd9we3O2OZ3PH9eWdMdDrF0R0yqv7L8Qlz5jaquEv/IbRHUdmL27Pr2T89PbT4YYa0IrR0AsfQs2NHkG/hycu1Le+aOiLL8HmwTYxqa48J99uJZpXeUA5E1EMv1QQdbAxWnk5qV91/dlR8RD98dXFEYKEv/Mq645omhWdN610JOk4c1nawOa7Q1JJrKPnMJCRK1/Wr3uFPRkb1tNauvi3t7tjfBN1oWuc4uzzTGHrixIzzjC2cW+NZd/l3w3rxfy96TC//hP73GBPMG6rvOXys95fCvyvtvqThwOdiGPbui/YW1K5MPx+vfrd+Ucxxsn/Tpas/7a2PytuvWrr0lZB3U5AvRBR0DrzfZK46GpnpXfLoD6uDQ5rc7rC9eiN+3M+rqj+2DTTBvw5Lkb1IOPufY++LMnZMT36pkdyb3f5eGd2dP3+ZP3pjbJ+IU5HTfQ8/V5/OJ3TfqJ0drqHQ2+CYsib5+9kxrwlvmu4Nibn5pjoR6earqh0RpZXJ1/uld9Unr58O8tgdRN3Nrnk880LEtU+p87x7Y8u8X3o7ZX+nwOsQr4vGhAfjuqIYHd1+Z1D7l7SHG1SVpznKwpdwRe9Y8iLNvbR57ur5mYx7EErRGPXg2LTauYtzST4pvjRkJeR6RsfRhbHWN/P5vde3R+S3jWQ7CThBtmKYDJZGaztWLMyhwuYkzKHDQyBkU2IRsQrYZOIMCuyXOoMB+kXILIaCkAbWM9iqB20HBzpTazWg3oz1dzxn0Z/Yh0/leHR8HhXHGPmQ6foLwcVAYZ+xDpuMExwmOExwn5Jd4YB8sLrqvEHIIme3n0T4pMz8LrmPFdWRkJ7KCrKIWYTwWjM+KLCM7kRVkFbUI92nBfVuRZWQnsoKsohbhviyYbyuyjOxEVpBVZA+ekwXPz4osIzuRFWQVGf3guyxfFq7gz1hGdiIryCqyB5n6szq1YN1asW5lZCeygqxinVu4wnzGMrITWUFWsW5pfKyOrVwhPsZOZAXVg3YaF6t/C1fwYywjO5EVZBXZg0z92X2ycAV/xjKyE1lBVpE9yNQ/iP5B9A+ifxD9g+gfRP8g+gfRn913C1fwZywjO5EVZBXZg1yEeVAxL2WoDWhvwf2WoTbgvltwH2WoDbifFoyvDLUB42zB75ahNuD3WR9xSxDneBNTodbglgKrNN1FibJVE/dImfqxuZowTnQYtFRNN4MqWUmETVTN8ZouyuQwzKD8rjjYqGXY6P1O19O6EHOM6XpbNhEaRU3QEom4xLBBMM8n5Li0QfDOoW+UVCiYcyFu/h2/yDUkeHX8Pnh1vL4ps3GqKvQPt8TPg6lgM3A/N8SrQj/l84JGto7AmI6bjFy3GDL1msMmLRNtdD+E3JLS9YEkyKurFz0/geXFh3nzYV59mHcfnosP75UP76cP73mZJrI+5cG+48E+4sG+K2si68NOrpAnxioyvW+MrbAPLRziqRfzDN4MQl4z0bxS/yQad2AesM0A3F/inGPkajNQO72X74HdoYnjTZBHrrZU8Idz1nSgdL4AeYQ8gQbmaaKefsf2CqzTHQbfD+L5mNj6EBeNjNYrrM/9/KItFdQs0PMSIO9wLq5e0KNhPlczPLbs3XhMH9kJ9H+CffUxVXCaAv2LYP8irO+wdVnfeGy8DO10/ZFSkMWVQDU4U9MlSLdEbxatV6lLNC8hQn8pJAayNHEktdM6Jf2lRpgnthmCIknTxCgpILpmEXKDMujT4n6TN5Hmlerl1UToJ5WbAi5C+kmaaQbNY7ux2kTWECHbmGUyLyBkhTHH5KL2f0npJhf1e80UEl30vPsaQyL4n0KNNToMwVVEmCVxHWFwGNRlmriR5lldDveQnSu9l1wh7/QcdbVYr3BOAQeMc+0vVUfAubhRL6LaDFxrUU1GrjAf6saNehEV5oPWosJ80I9ppXoTeZ0Bh+Ck6XkzlbnCun4R4oP3naoK91cLh3pnKsN7wcdNRq5BI/MnoLzvsnUJm0f92f1UoQ650qpk68E9ATUZuTK7zO8PKLNTjaJ5DazUxHU0bjOtgwRaz91qQJpA8z5DtZF62geqkwL6DNCpAV0a7RPmhIAYa0jXX5YDAvQzyD8ozyP0N1ifK9ghD+wee+C+uSW4b6D8PeP9qZYpnA+9bw7IN6im2yIU6vwuG42f96lGQ6Fgy+H5hXNmSvcdfCxf/D3i67E+bsV+zvrko34J68E8YH4/Yf3DdH+BTI2Motp3oUYEqsFZGlFpv++eq5E9NLP+TCKw/xifJjItwv5UxM8R+ggo9IWdRs6gwLA/fs7Qp+E8OLM8OJEVyB+3s3fAiaxwP74+H/eLj7HC9wUK78Ij5eOs3+kgjz+rwt8F/n0+jzH7Prez98GJrHA/vh6ve1Do2znsHsB58/vD4nr0Lsn4nqnoT/UZmtex0wICW59yG9RNKvSbX5T2I9q/o3Vwf+F8uJoF3lfZO8gUGL4D8UBdQb+24XvtxveakP8DiOdK2gARAAA=```

**Comment by LuPro** [comment]
Related to #758

**Comment by cbaggers** [comment]
I've managed to confirm at least one version of this bug. I'll fix what I'm seeing and we can then test if it fixes your issue

**Comment by cbaggers** [comment]
This looks like it's fixed in the next patch :)
Thanks for the help!

**Comment by mrotondo** [comment]
Yep, seems to be fixed!
