### ISSUE TITLE
Game doesnt work offline

### ISSUE THREAD

**Issue by RiftWalker6812** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#841]
**Describe the bug**
the game is supposed to load normally but if offline the game just sits in the loading screen.

**To Reproduce**
turn off network connection and launch game, it will then stay on loading screen trying to probably retrieve something, forever on loading animation.

**Screenshots/Videos/Twitch Clips**

![image](https://user-images.githubusercontent.com/45465917/115646244-d0dd9c80-a2ef-11eb-8bd4-01147a7972e8.png)

**Additional context**
this might be a simple task for the fellas at the dev team please fix when you can tho.

**Comment by LuPro** [comment]
This is not a bug; Currently the game is online only as the building and storing of builds happens on bouncyrock's servers. The devs want to implement a P2P mode in the future, but no ETA on that yet.
