### ISSUE TITLE
Wall sconces disappear on exterior walls, but leave light source behind - Edit: New update fixed issue.

### ISSUE THREAD

**Issue by Velgor55** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#848]
When attempting to put wall sconces/torches on an exterior side of awall, the torch object disappears, but the light source remains. Cannot select object since it doesn't exist and only Undo will remove the light source.

**To Reproduce**
1. Create wall.
2. Select a torch/sconce and attach to wall.
3. Torch/sconce disappears after placement with light source remaining.

**Comment by Velgor55** [comment]
No longer an issue. Disregard.

**Comment by LuPro** [comment]
I presume it was a setting of the hide plane that hid the torches but not the walls
