### ISSUE TITLE
Deleting a board

### ISSUE THREAD

**Issue by iscofeild** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#86]
**Describe the bug**
It is possible to delte you entier UI and tools 

**To Reproduce**
Delete the board you are currently on

**Screenshots/Videos/Twitch Clips**

![empty board](https://user-images.githubusercontent.com/63010099/79030099-56802580-7b8f-11ea-8cc6-47eb9a156f36.jpg)

**Comment by LuPro** [comment]
Similar to #5 and #20, pressing spacebar should reopen the left menu to make a new board, the rest of the menus should appear then
