### ISSUE TITLE
Cutbox not working. 

### ISSUE THREAD

**Issue by Howik** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#864]
**Describe the bug**
toggling cutbox does nothing when toggled on or off. 

**To Reproduce**
1. Toggle the cutbox. 
2. see nothing happen. 

**Screenshots/Videos/Twitch Clips**
https://imgur.com/a/aZgkrJn

**Additional context**
Attempted to verify integrity of game files but it came back saying everything was fine.

**Comment by LuPro** [comment]
Duplicate of #675
