### ISSUE TITLE
slab selection bug

### ISSUE THREAD

**Issue by Cregoo** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#866]
While using the slab selection, the area selected becomes a black box that can't be undone or deleted.

**Comment by LuPro** [comment]
Can you check what keybind you set to the "experimental fog of war" feature in the second tab of the settings? it sounds like you accidentally bound it to some common key and are triggering it that way

**Comment by Cregoo** [comment]
I looked into it and fiddled around and managed to sort it out, totally my mistake, sorry 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
