### ISSUE TITLE
Decorations disappearing when they shouldn't.

### ISSUE THREAD

**Issue by williamsultzer** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#868]
When placing two ground tiles, a table, and then a decoration the decoration is disappearing onto the next "floor." I've tried playing around with the decoration height but everything I do seems to produce the same results. Zooming out causes the decorations to reappear. 

![Image1](https://user-images.githubusercontent.com/78112661/116325396-0b33b780-a790-11eb-9c7c-4efe9ad5bddf.PNG)
![Image2](https://user-images.githubusercontent.com/78112661/116325399-0cfd7b00-a790-11eb-9a99-761d10fb3448.PNG)

**Comment by LuPro** [comment]
Could you try and see if this has something to do with the hide plane slider (the green one). In the screenshot it's obviously high enough to not have an effect, but there's a bug where sometimes the hide plane is actually lower than it shows and moving the slider around a bit updates the position and fixes that.
It's a bit odd that the stuff on the table can be hidden separately from the table if that's the case, but at least somewhat understandable

**Comment by williamsultzer** [comment]
That did the trick! Thank you so much for the fast reply
