### ISSUE TITLE
Hidden minis visible to players via Tab

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#869]
Regardless of whether I hide a mini individually via its Hide radial button, use a hide box, or even combine the two, players can simply hold the Tab key and see hidden minis.

**Comment by LuPro** [comment]
I presume you mean just the names of the minis? if so that'd be a duplicate of #771

**Comment by MallowOni** [comment]
> 
> 
> I presume you mean just the names of the minis? if so that'd be a duplicate of #771

Yes, that's the case.
