### ISSUE TITLE
Hidden Hide Volumes

### ISSUE THREAD

**Issue by demongund** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#877]
**Describe the bug**
I created several hide volumes and now I can't access them. They are still hiding tiles but nothing I do makes them display.

**NOTE - I RESTARTED TALESPIRE AND NOW IT IS FINE.**

**To Reproduce**
1. Import the following board - talespire://published-board/RGVhdGggSG91c2UgLSBHYW1lIFJlYWR5IC0gRmxvb3IgMQ==/735230964a06f265b396b5a1dba95cd4
2. Turn on edit hide volumes
-- Notice that there are hidden tiles without any visible hide volumes to edit

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/25164882/116511631-93db5200-a87b-11eb-8073-e26517400dec.png)

**Additional context**
This is kind of a big deal for me :( All my published and unpublished boards with hide volumes are suffering this in varying degrees.

**Comment by baggers-br** [comment]
Thanks for the excellent report. A fix shipped for this earlier this week, thanks for bearing with us for so long!
Happy adventuring
