### ISSUE TITLE
Select Bug

### ISSUE THREAD

**Issue by NekuNase** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#880]
**Describe the bug**
Can't select figures that are in "Hide" mode.

**To Reproduce**
1. Create Monster
2. Click on "Hide" in GM Tools
3. Can't select Monster
4. "H" doesnt work; RMB doesn't work; LMB doesn't work (nothing works)

**Comment by LuPro** [comment]
If you hide a mini you should be able to see (and interact with it) when you enter GM mode (by pressing Tab), I presume you are seeing the mini in build mode (as hidden minis are also displayed while in build mode) and during that you can't interact with minis at all (intended).
Could you confirm that by going to GM view interacting with the minis works?

**Comment by NekuNase** [comment]
Alright, false alarm. Next time i read tutorials before complaining :)
