### ISSUE TITLE
Objects blury on super ultrawide monitor

### ISSUE THREAD

**Issue by cvrabie** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#883]
**Describe the bug**
Objects look blurry and the grid looks duplicated towards the edge of super ultrawide monitors.

The majority of 3d games have issues in this area with the content looking stretched because of the [single-camera barrel distortion](https://www.techarp.com/articles/nvidia-simultaneous-multi-projection-explained/) but in this case, there seems to be more of a problem. Objects appear blurry and even the grid being seems duplicated in a different colour.

Objects and grid look right in the centre of the screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open TaleSpire 6614241 in 5120×1440 resolution
2. Enter build mode
3. Activate the grid if not already active
4. Move the mouse toward the edge of the screen and place an object
5. Check if you need 3d glasses

**Screenshots/Videos/Twitch Clips**
![2021-04-30_23-03-56](https://user-images.githubusercontent.com/256405/116758643-6f60b080-aa08-11eb-8ae4-2ab2fdecb9dc.jpg)

**Additional context**
Resolution: 5120×1440
Anti-Aliasing: SMAA
Shadow resolution:  High 
Shadow quality: Default
Texture Resolution: Full
Build: 6614241

**Comment by LuPro** [comment]
From the screenshot it seems to me that this is the chromatic aberration effect doing its thing - you can turn it off in the settings. The effect gets stronger the further away from the center, so I presume it's just too strong on such a wide monitor making it less of a "nice visual effect" and more of "ew everything is blurry/weird".
Can you confirm that this is the problem (= if turning off chromatic aberration fixes it)?

**Comment by cvrabie** [comment]
You are absolutely correct. Both the objects and the grid look correct if I turn off the chromatic aberration effect.
![2021-05-01_11-28-15](https://user-images.githubusercontent.com/256405/116779824-84712a00-aa70-11eb-8ebe-deeb17a0eae0.jpg)
Thank you for your help.
