### ISSUE TITLE
Stem of Speech bubble gets stuck on screen after killing the token

### ISSUE THREAD

**Issue by TDS-Meliodas** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#889]
**Describe the bug**
The speech bubble (or atleast the stem) gets stuck on the screen and cant be removed until you exit to the main menu

**To Reproduce**
1. Talk with Token 1
2. Speech bubble appears normally on the screen
3. Kill Token 1 by using the Kill Creature option while the speech bubble is still on the screen (meaning you have to do it almost simultaneously)
4. The token is killed and removed normally but the stem of the speech bubble remains

**Screenshots/Videos/Twitch Clips**
![TS_1619992570](https://user-images.githubusercontent.com/83557749/116828962-a4a50400-abaa-11eb-8ace-b3782781dcf6.png)

![TS_1619992590](https://user-images.githubusercontent.com/83557749/116828974-b686a700-abaa-11eb-89cc-5aa700ac3c96.png)

https://user-images.githubusercontent.com/83557749/116829673-bb992580-abad-11eb-8099-7b414677de35.mp4

**Additional context**
It is not a game breaking bug, but I thought ill issue it anyways. 
It would be rare to kill a token while it is talking, cuz first that would be rude, and second the speech bubble disappears quick enough most of the time (unless what is written is long then it does take time)

**Comment by baggers-br** [comment]
At long last I got to this, and a fix for this will be coming out this week.

Thanks so much for reporting it so thoroughly
