### ISSUE TITLE
GM Flashlight reveals locations of large hidden creatures

### ISSUE THREAD

**Issue by MillerMark** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#904]
When I turn on the FlashLight and move it around the board, if I have a large hidden creature beneath the light, the light will fade out and the spotlight on the floor will diffuse. 

Expected behavior: Hidden creatures should have no impact on the FlashLight beam.

1. Place a giant creature on a map.
2. Hide the creature.
3. Move the FlashLight over that hidden creature.

**Screenshots/Videos/Twitch Clips**
Let me know if you need something.

**Additional context**
You guys are doing great!

**Comment by baggers-br** [comment]
Thanks for the excellent report @MillerMark, sorry for the delay in getting to it.
I've been able to replicate this easily and will be looking into how tricky it will be this week.
Cheers!

**Comment by baggers-br** [comment]
This will be shipping in the next patch. Thanks again for the report!
