### ISSUE TITLE
Character View Hides Creatures But Not Items

### ISSUE THREAD

**Issue by LordAshes** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#928]
**Describe the bug**
When a character mini is separated from an area by walls, any creature minis in that area are hidden from the character's view. However, the same should be true for items but it seems that items are not hidden.

**To Reproduce**
1. Create a board with a wall dividing the board into two rooms. 
2. Place a character mini on one side of the wall.
3. Place creature minis on the other side of the wall.
4. Place items on the creature side of the wall.

When the character mini is on the opposite side of the wall, the creature minis are taken away but the items remain. This means that the character can see items in areas to which she does not have visibility. The expectation would be that in any area, to which the character does not have visibility, the creatures as well as the items would be hidden/removed.

**Screenshots/Videos/Twitch Clips**
The issue can be see in the following YouTube video: https://youtu.be/afrjoBiPrOk

**Comment by LuPro** [comment]
This is intended behavior, there is line of sight for minis, but that does not extend to tiles or props.
To hide tiles/props you can use hide volumes or the (very experimental) fog of war :)

**Comment by LordAshes** [comment]
Understood.

However, that seems like an odd decision. With the line of sight for minis,
a GM can lay out the various rooms on a board, place all the enemy mini
within those rooms, and assuming none of the minis are hiding then the GM
does not need to do anything else because players will not see the enemy
minis until they have line of sight. This is good. Less work for the GM
because he/she does not need to set up hidden volumes or FoW.

The issue is that if this does not extend to items, the players would
immediately see all items in all rooms of the board regardless if they
have line of sight. This then means that the GM would have to use hide
volumes or FoW to hide the items which somewhat defeats the benefit of the
line of sight for mini. Yes, I realize that the line of sight for minis is
good for combat situations (i.e. once the room has been revealed but when
minis don't have line of sight of each other) but it seems if the same
concept was added to item, it would make the GMs work a lot easier.

In my opinion as a GM that has used a number of different systems for
roleplaying, I think the line of sight should be applied to minis and items
but not tiles. Actually having an settings option to also apply this
concept to tiles would provide an alternate solution to FoW. The characters
would only see what is in their line of sight.

Just my 2 cents.

**Comment by LuPro** [comment]
the problem is that line of
