### ISSUE TITLE
Video Graphic "3d"? glitch

### ISSUE THREAD

**Issue by Veska75** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#93]
**Describe the bug**
Video graphic seems to do a trippy "duplication" on the edges of the screen

**To Reproduce**
  It did this from the start. I think it is only happening to a small number of people (idk though).
I have an AMD RADEON 480X graphics card.

**Screenshots/Videos/Twitch Clips**
![3Dish graphical error](https://user-images.githubusercontent.com/63480403/79031056-502b8280-7b6a-11ea-921c-862f34d7f608.jpg)

**Additional context**
Keep up the hard work!

**Comment by Puddinglord** [comment]
I was going to make an issue for this as well but it seems you've done it already!

**Comment by LuPro** [comment]
ah, nevermind, look closer on the screenshot now as compared to back when I was going through the issues en masse. What you're seeing there is "chromatic aberration" which is a post processing effect added to the game to give it more of a "filmic" feel. This is originally an effect of how camera lenses bend light and thus split various wavelengths (colors) up a bit. The game has this implemented on purpose, though I do think it is a bit overdone. The devs said they'll include graphical settings to change the strength (or disable at all) of this effect.

So while it can be annoying, it is not a bug

**Comment by Veska75** [comment]
@LuPro thanks for the heads up, I was worried
