### ISSUE TITLE
2X2 corner wall won't delete

### ISSUE THREAD

**Issue by Trelvania** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#933]
Just the same as I see ticket #920

**To Reproduce**
1. Punch an ogre '...'
2. Set a chair on fire '....'
3. Tried to open a door '....'
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
If it's the same please just put a comment below the other issue instead of creating a new one - but thanks for the report :)

**Comment by Trelvania** [comment]
Sorry! Brand new to github and couldn't figure out how to add to that one

**Comment by LuPro** [comment]
No worries :) Should just be able to write a comment below the original issue once you click on it
