### ISSUE TITLE
After select-deleting a lot of pieces, the group of pieces appears on every board I open.

### ISSUE THREAD

**Issue by jhardin101** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#958]
As the title says. I used the select tool to delete a section of a wall I was building. While the pieces have no collision, they are visible, and on every board in my game, even if I make a new one. They can't be interacted with in any way. This seems to resolve itself after a restart.

Original map
![20210523173431_1](https://user-images.githubusercontent.com/70728041/119280155-45f10a00-bbed-11eb-9c97-8d23b05f7f45.jpg)

New Board
![20210523173450_1](https://user-images.githubusercontent.com/70728041/119280161-48ebfa80-bbed-11eb-834e-bf3fc5b9730d.jpg)

**Comment by ugly2632** [comment]
this is nuts

lol. i have nothing to add haha

**Comment by LuPro** [comment]
Could be related to the issue where people had some builds they did appear on the main menu

**Comment by baggers-br** [comment]
Thanks for the report @jhardin101, I think this might be related to #989. I've got a fix for this coming in the next patch so hopefully this will help you too.

p.s. @ugly2632 haha agreed!
