### ISSUE TITLE
Autosave not saving some deletions

### ISSUE THREAD

**Issue by Tarn-IV** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#96]
**Describe the bug**
Upon reloading a board, some objects that had been previously deleted reappear, often clipping with other objects. Added objects are always saved, but some deletions are not.

**To Reproduce**
The issue is reproducible, in that some things will return upon reloading, but others won't. After deletions have been made, quit to desktop, and reload the board.

**Screenshots/Videos/Twitch Clips**
[Clip of Results](https://www.youtube.com/watch?v=TdLwIAE-7wE&feature=youtu.be)
The wall pieces had been previously deleted and replaced by floor tiles. Upon reloading the board, they had returned, but the floor pieces had also been saved. Clipping has never been toggled.

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
