### ISSUE TITLE
Revealing minis under suspended objects

### ISSUE THREAD

**Issue by LordAshes** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#960]
**Describe the bug**
TaleSpire implements the concept of making objects above minis disappear so that the mini can be seen underneath. This is good. However, currently this seems to be an all or nothing which is bad. For example, I created a board that had two objects suspended above the board. As soon as a mini was placed under either one of them, both the suspended object were raised. This potentially will cause players to see into parts of the board which they should not see into.

**To Reproduce**
1. Create a board.
2. In build mode, suspend a tile or prop above the board.
3. In build mode, suspend a second tile or prop above the board well away from the first.
4. In run mode (non-build mode) move a mini under one of the suspended objects.
5. Both suspended objects will be hidden to allow the mini to be seen.

**Additional context**
One would expect that only suspended objects covering the mini would be hidden to allow the mini to be seen without revealing other parts of the board.

**Comment by LuPro** [comment]
The hide plane (which is what hides things above characters) is meant to give the ability to look into buildings and as such removes a rather large area around the camera (not everything though) so in a way this is intended behavior. Something less "extreme" would be the cutbox feature (hotkeyed to "n") that removes a smaller section in a different way (similar to how sims removes walls), this is however bugged currently, so it's (at least currently) not an option.
Regardless of this, the automatic selector of what height to hide at definitely needs some tweaking as it's not ideal in many scenarios. If you want to give more agency/granularity to this you can stop the auto adjust on hide plane (padlock next to the green hide plane slider on the side) and then move it manually

**Comment by LordAshes** [comment]
Thanks for the update. I was testing on a small board and thus both of my suspended items were hidden. However, from the answer, I understand that it just hides an area of suspended objects (not the entire board). In addition, it is suggested to use the cutbox feature if more precise accuracy is needed.
