### ISSUE TITLE
No indication of how to show or hide menus with spacebar

### ISSUE THREAD

**Issue by Z-Doctor** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#967]
Title, but to further explain I had an issue because I couldn't see the menus. After playing around and reloading the world I couldn't see the menus. I eventually figured out it was the spacebar but there was no indication.

**Comment by LuPro** [comment]
The menu should be pre-expanded (with the tutorial section open) on the first time of loading into a campaign after creating it and there should be a hint for opening the menu on the first time loading into a campaign after starting TaleSpire (even if the campaign is "old"), other than this there's no indication for it, so it's not a bug. If you feel like this should be different please drop by the [discord](https://discord.gg/talespire) and enter a request in the #feature-request channel :)
