### ISSUE TITLE
Campaign keeps crashing when I try to open it.

### ISSUE THREAD

**Issue by AshcanOnline** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#968]
When I try to open the campaign, it starts to assemble the whole thing, but then it pauses and the screen shot below is the last thing I see.

**To Reproduce**
1. Open the campaign

![image](https://user-images.githubusercontent.com/85315185/120705443-7488a380-c47d-11eb-87bb-9829b8f2c2b1.png)
**Additional context**
Edit: May have been my PC, it seems to have opened with boosted by GPU Tuning and the fans.

**Comment by baggers-br** [comment]
Hi, I am sorry for how long it took me to get to you, but I was wondering if you still have this issue?
If possible I'd like to check out this board in my dev-build so I can hunt down this bug.

I hope this finds you well

**Comment by AshcanOnline** [comment]
Thank you! But I think the problem was me using far more assets than my PC
could handle, tested it on some other PCs to verify.

**Comment by baggers-br** [comment]
Thanks for the info. We'll try to make sure this fails more gracefully in future. Have a great day
