### ISSUE TITLE
Can't open Library in build mode.

### ISSUE THREAD

**Issue by Alfabravo313** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#979]
*SOLVED* The newest update fixed it.

If you click on _Boards_ and then _Go to boards_, and the go back into build mode via the _Build Mode_ button at the top you can not open the library again. Sometimes the _Open Library_ button is there and sometimes it is not.

**Maybe I am just an idiot though.**

**Comment by LuPro** [comment]
The open library button is shown even with menu hidden if I recall correctly (definitely an issue) - try pressing space to bring the menu up and the open the library

**Comment by baggers-br** [comment]
Thanks for the report @Alfabravo313. Glad to see it's fixed now. I'll close the ticket
