### ISSUE TITLE
Players can't see other player torches

### ISSUE THREAD

**Issue by pgwipeout** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#980]
**Describe the bug**
Only the player that activated the torch and the GM can see the light source from a player torch.

**To Reproduce**
1. Start a multiplayer game.
2. One player enables their torch.
3. Other players cannot see the light from the torch.
4. GM has to tag the player with a light source for other players to see it.

**Screenshots/Videos/Twitch Clips**
https://clips.twitch.tv/HeartlessSavorySlothUWot-UgivYAIvZLaFQ7UX

**Comment by baggers-br** [comment]
Hi @pgwipeout, thanks for the report. I'm looking into this and it's possible that we already fixed this. I was wondering what you meant by 'tag the player' as that might help me work out what was happening. 
Cheers!

**Comment by pgwipeout** [comment]
Good Afternoon,

We tested this in today's session and it seems to be corrected.
For reference, "tag the player" referred to the GM toggling their torch.
If the GM did it, it would be observed by all, if the player did it, it was local only.

But yes, it seems to be fixed now, so closing this ticket.
