### ISSUE TITLE
Creature Renaming Issue

### ISSUE THREAD

**Issue by Euphorrix** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#983]
**Describe the bug**
When renaming many creatures the name will jump to another non unique tokens or disappear 

**To Reproduce**
1. placed many hidden creatures
2. renamed creatures
3. moved camera away from where they were
4. names disappeared or 'jumped' to another token

**Additional context**
I was using this to place 'gm signs' for myself and they moved
![H5OIpqTBML](https://user-images.githubusercontent.com/85853643/121827266-3c007b00-cc70-11eb-81fc-bb5825a17f5f.jpg)

**Comment by Euphorrix** [comment]
upon leaving the board and re entering they are corrected

**Comment by Euphorrix** [comment]
upon reentering the board, some of the assets further away (like +64 tiles) still have their name gone, but again leaving then reentering the board being in the new area fixes it, however it is stull scuffy

**Comment by Euphorrix** [comment]
exiting to main menu then reloading campaign seems to have them all set, however placing new ones repeats the issue outlined above

**Comment by LuPro** [comment]
Related to #913

**Comment by baggers-br** [comment]
Thanks for the info @Euphorrix . We recently shipped a patch that fixed some creature name indicator issues. Are you still seeing these issues?

**Comment by Euphorrix** [comment]
have not experienced it since the patch, if I encounter it again, I will be
sure to submit a ticket. thank you for getting back to me
