### ISSUE TITLE
Can't edit pasted slab

### ISSUE THREAD

**Issue by Arafor** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#989]
**Describe the bug**
Wanted to copy and paste a building. Selected the building and cut it. Accidentally pressed the paste slab button on the UI. Building showed up but I cant interact with it in any way. I cant delete or edit any part of it. Ctrl + z also didn't undo me pasting the slab

**To Reproduce**
Steps to reproduce the behaviour:
1. Make small house
1. Select the multiselect tool
1. Select the entire house (all three dimensions)
1. Press ctrl + x on keyboard
1. Accidentally press "paste slab" on the UI
1. House is pasted but can't be edited, deleted or undone.

**Screenshots/Videos/Twitch Clips**
https://drive.google.com/file/d/1f0Qnudf8NwnkcHzIcSh3xodacxnq567G/view?usp=sharing

**Additional context**
Need to scrap my little island project now

**Comment by Arafor** [comment]
Update: Restarting the game makes those building go away. So I guess it's a visual glitch.

**Comment by baggers-br** [comment]
Oh amazing! I've been hunting for what causes this. Thank you for those excellent steps :)

I'll look into this immediately

**Comment by baggers-br** [comment]
And I've fixed this internally. This will be in the next patch.
Thanks again!
