### ISSUE TITLE
exiting and joining texture issue

### ISSUE THREAD

**Issue by Brayo12466** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#99]
**Describe the bug**
When exiting and joining it added walls that weren't there before and also got rid of the intersection tile as well as the plowed field tile
**To Reproduce**
1.  'place down tile said above'
2.  'exit game'
3.  'Join game'
4.  'Tiles will be glitching or disappear'

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
