### ISSUE TITLE
Boards corrupting

### ISSUE THREAD

**Issue by msifton** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#990]
**Describe the bug**

I was adding the new fireplace asset to a large board (meant as a tileset to construct city buildings... it had a lot of stuff in it). I noticed the fire VFX in the fireplace wasn't functioning, and became concerned. 

I decided I should reload the program, and attempted to quit Talespire - in hindsight, this was a terrible idea. It immediately hard crashed while trying to quit. When I tried to open my board after the crash, I received an Unhandled Exception window, and was ejected to the place between boards. The board now refuses to load.

This bug has happened to me twice now, on two different boards, both heavy with buildings, lights, and other assets. Interestingly, the first time the board was only partially corrupted - about half of the buildings and assets loaded correctly, but a large region of the board would not load, and was replaced with the large white grid you of the place between boards.  I couldn't draw a selection box or even pan the viewport into this blank grid area, and some of my buidlings were sawed in half at the border.

I have a partial screenshot of this board as it attempts to load (see Talespire_Error_03.png). I'd send you a better visual, but the half-corrupted board is now fully corrupted and won't load.

**To Reproduce**
1. Add a light or fireplace to a large board with a lot of existing assets
2. Notice the light's fire VFX is missing

3. Try to quit Talespire, and suffer hard crash while quitting (perhaps trying to save)
5. Reload Talespire, try to open board
6. Get Error: Board Update Failed: Unhandled Exception. 
7. Get thrown into the Place Between Boards.

**Screenshots/Videos/Twitch Clips**
![Talespire_Error_01](https://user-images.githubusercontent.com/84896889/122937930-56a5b480-d340-11eb-8ab1-dc94371df5f6.png)
![Talespire_Error_02](https://user-images.githubusercontent.com/84896889/122937948-59080e80-d340-11eb-9c4b-208a67f77cd0.png)
![Talespire_Error_03](https://user-images.githubusercontent.com/84896889/122937966-5ad1d200-d340-11eb-83ff-ad0315c4e0e7.png)

**Additional context**
I have 2 other boards in the campaign, including another large one that my players are currently adventuring through. For now, this board still loads correctly, but if it ever corrupts, this would really screw up my D&D campaign.

Kicking myself for not reporting the bug earlier, on the first board, as soon as I got it. I'd previously had Talespire loading difficulties that vanished after a day or so, and hoped this problem might just go away. Nope!

**Comment by msifton** [comment]
Okay! After several hours passed, and a cold boot of my PC, 2 of the 3 corrupted boards have loaded properly again, fire VFX and all. So that's great. However... my last board is still bugged. I'm able to open it (partially) but only half the buildings and assets load, many of them sawed in half. I was able to take a few screenshots.
![Talespire_Error_04](https://user-images.githubusercontent.com/84896889/123006219-58de3200-d385-11eb-9595-11b4942b8633.png)
![Talespire_Error_05](https://user-images.githubusercontent.com/84896889/123006237-5c71b900-d385-11eb-91ac-3a7990c0dc2b.png)
![Talespire_Error_06](https://user-images.githubusercontent.com/84896889/123006348-83c88600-d385-11eb-8107-388628b261e7.png)

**Comment by LuPro** [comment]
If you are on the discord it would probably be a good idea to get in touch with baggers - campaigns are backed up with the 3 newest revisions so even if something is completely broken it should still be recoverable. Other than that the logs might help with diagnosing the issue, you can find them in `%AppData%\..\LocalLow\Bouncyrock Entertainment\TaleSpire\` as "player.log" and "player-prev.log" (note: the logs contain your windows username, if you don't want that, search and replace it with something like "<user>"

**Comment by msifton** [comment]
Thanks for the quick reply.
Unfortunately I've done some work since the bug (beyond 3 revisions), and if the whole campaign was regressed beyond that, I'd lose more than the bug took from me. That said, if an individual board can be recovered, that might save me.

The damage to the board is frustrating, but really my own fault for not reporting immediately. I don't mind rebuilding. That said, if the bug continues to be a source of instability within the campaign, that's more dangerous, especially if it starts eating boards my players are actively going through.

Here are the logs.
 
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6702433/Player.log)
[Player-prev.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6702435/Player-prev.log)

**Comment by msifton** [comment]
Forgot to close this back in June. Received backups and assistance from baggers on discord. Also followed these steps: 
- close talespire
- browse to C:\Users\<YOUR_USER_NAME>\AppData\LocalLow\BouncyRock Entertainment\TaleSpire
- delete the `Persistence` folder
- delete the `Sync` folder
- restart TaleSpire
