### ISSUE TITLE
Water is invisible if you have water build display on and not in build mode.

### ISSUE THREAD

**Issue by Clickeddaisy** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#992]
Like the title says, When the "water build display" is toggled on and you are not in build mode the water disappears.

1. Toggle water build display on
2. go out of build mode

![Water Bug](https://user-images.githubusercontent.com/78590813/123266723-f57b0e00-d504-11eb-9374-7cd040bf5d43.png)

**Comment by baggers-br** [comment]
Hah, well would you look at that! Thanks @Clickeddaisy, I'm able to replicate this bug and will look into fixing it now

**Comment by baggers-br** [comment]
I've fixed this internally. We'll get this fix shipped in the next patch
