### ISSUE TITLE
No way to play without internet

### ISSUE THREAD

**Issue by Swatacular** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#994]
**Describe the bug**
Thought id be able to make maps while offline.

Game just stuck in loading screen before begin button appeared (Possibly after)

**To Reproduce**
1. Run the game without an internet connection

**Comment by LuPro** [comment]
The devs want to look into a P2P mode that would also allow offline/local play, but as of right now it's online only, so this is not a bug
