### ISSUE TITLE
Hidden Fowl Horror

### ISSUE THREAD

**Issue by PyroRegia** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#997]
Goose doesn't show up in any of the creature lists, but when I filter for Goose it does. And appears to be tagged Wild, which is one of the groups under Beasts, but it is definitely not there. Filtering for Wild shows all the Wild Beasts, but no geese.

Filter generally has some quirks, filter for fire doesn't turn up the animated fire. Filtering by tag works on some things, but not others.

**Comment by baggers-br** [comment]
It appears that the goose is present and correct in the latest update. Is this still not showing correctly for you?

https://user-images.githubusercontent.com/88878193/129786996-9f9ed906-6554-42b3-93d9-514935ff90ab.mp4

**Comment by baggers-br** [comment]
This still seems to be working in the current build so I'm going to tentatively close this ticket. If you find this still is an issue please feel free to reopen it.
Thanks again!
