### ISSUE TITLE
Clicking on the same campaign twice in the lobby breaks it 

### ISSUE THREAD

**Issue by natigrundle** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#998]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
If i click on the same campaign twice. It erases the players and send me to in between the boards screen. 
**To Reproduce**
1. Click on campaign works fine. 
2. click on same campaign breaks it 
3. open campaign sends you inbetween boards screen
4. 
3. 
4. 

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by baggers-br** [comment]
Hi @natigrundle, I've been able to replicate a bit of this but not all of it. 

* If I click the campaign in the list and then click it again it closes the campaign info as expected
* If I click it again it opens again, but the players list is just `...` (which is a bug)
* If I then click the `Play` button the campaign launches and I join the default board (I couldn't replicate the 'inbetween boards' part of your report)

Do the campaign in question have a default board? Is there anything in my steps that I missed?

Thanks for the excellent report!

**Comment by baggers-br** [comment]
I've fixed the `...` issue internally. This will be in the next patch

**Comment by baggers-br** [comment]
I'm going to tentatively close this as fix has been out for a while and I'm no longer able to replicate the issue
