### ISSUE TITLE
Cannot "Open in Talespire" while in "Place between Boards"

### ISSUE THREAD

**Issue by CaptainBaummann** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#999]
Found this behavior while browsing boards and could reproduce the behavior on multiple campaings and pcs.

**Describe the bug**
While beeing in the "Place between Boards" (deleting the board you are currently viewing) I cannot open a Board from Chrome Browser using the "Open in Talespire"  button of the talesbazaar website.

**To Reproduce**
1. Create New Board "Unknown Realm 1"
2. View Board "Unknown Realm 1"
3. Delete "Unknown Realm 1"
<img width="1921" alt="Step 2" src="https://user-images.githubusercontent.com/33952742/124090880-8e55e000-da55-11eb-9996-26606f33a86a.PNG">
4. Press "OK"
<img width="961" alt="Step 3" src="https://user-images.githubusercontent.com/33952742/124090914-97df4800-da55-11eb-8bf4-1ef2371ce4f2.PNG">
4. Go to talesbazaar.com
5. Click "Open in Talepsire" on any Board
<img width="1920" alt="Step 5" src="https://user-images.githubusercontent.com/33952742/124090929-9ca3fc00-da55-11eb-93f1-54e48f7a5843.PNG">
6. Accept Popup (Allow Relay URL)
<img width="1920" alt="Step 6" src="https://user-images.githubusercontent.com/33952742/124090873-8c8c1c80-da55-11eb-9e6c-83b47ad355ea.PNG">
7. The Board is not added to the Talespire Campaign

**Comment by baggers-br** [comment]
Oh good catch (and a fantastic report)

I can see the issue and should have a fix for this in the next patch

**Comment by baggers-br** [comment]
I forgot to come back and let you know this was fixed. Sorry about that!
I've just tested and can confirm that this works in the latest build.
